- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change addresses two major issues we've seen with the current implementation of the authentication APIs:
1. The call to microsoftTeams.authentication.authenticate is often triggering the browser's popup blocker because we are calling window.open from the Microsoft Teams window in response to a posted message as opposed to the click handler of the element responsible for kicking off the authentication flow.
2. Authentication is failing in Edge and IE11 for certain tabs that trigger redirects in the authentication popup across different security zones.
The change fixes these issues as follows:
1. The call to window.open will now happen inside the iframe and as long as microsoftTeams.authentication.authenticate is called from a click handler browsers will not block the popup.
2. Instead …
> Fix authentication issues

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
In the short term this is mainly for instrumentation so we can easily see how many tabs are using which version. Longer term we might have breaking changes which we'll need to hand back-compat support for, so this proactively helps with that if we can't just infer the version by the way the call looks.
> Send the SDK version with the initialize call

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This is based on feedback from @WrathOfZombies. I would still imagine that most users would want to call initialize onready, but I can imagine scenarios where there is a valid reason to potentially call it more than once. In any case I'd rather err on the side of flexibility for the developer.
> Allow multiple initialize calls

- src/MicrosoftTeams.ts
This change whitelists the https://ssauth.skype.com domain so that extension tabs work in our scenario test environment.
> Enable extension tab scenario tests

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
In cases where the initialize response or parent ping haven't come in before notifySuccess/notifyFailure are called, the authentication window will close itself before it has managed to post the message to its parent. This is a common scenario since code in the authentication window will typically call notifySuccess/notifyFailure immediately after initialize.
This change fixes the issue by ensuring that the authentication window waits for the parent message queue to be empty (i.e. all messages sent) before closing itself.
> Don't close the authentication window until it has finished sending the notifySuccess or notifyFailure message to its parent

- src/MicrosoftTeams.ts
This is the initial proposal for the API surface needed to enable AAD single sign on for Teams Apps. I've tried to closely mirror the corresponding APIs in the AuthenticationService of Microsoft Teams and underlying ADAL library:
https://github.com/AzureAD/azure-activedirectory-library-for-js
The AAD user object definition is based on the spec found here:
https://docs.microsoft.com/en-us/azure/active-directory/active-directory-token-and-claims
> Add new authentication APIs in order to enable AAD SSO for Teams Apps

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This is fixing a minor memory leak where the callbacks map just grows forever the more calls that are made. It also prevents a callback from getting called multiple times, although in practice that shouldn't really happen.
> Clean up callbacks once they're called

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change addresses a couple of issues that were preventing the popup authentication flow in v0.3 of the SDK from working correctly in the Microsoft Teams desktop client. It also adds a unit test case that exercises the end-to-end authentication flow in the desktop client in order to catch issues like these in the future.
I verified the end-to-end authentication flow in the desktop client and all supported browsers (i.e. Chrome, Edge, Firefox, and IE).
> Fix desktop client auth

- .gitignore
- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change allows developers to provide their own entity id as opposed to just always using the content url as the unique identifier.
This allows developers to use multiple urls which may have minor differences (param ordering, presentation-related query params, etc.) which all should be considered to point to the same underlying entity. This also makes it easier for things like bots to create deep links to existing tabs without knowing the exact content url for example.
As a reminder, we had originally decided that we wouldn't need an entity id since we could generate it from the content url, and if we had the content url we wouldn't need an entity id, but this makes assumptions about a url exactly and uniquely identifying an entity, which as described above isn't necessarily a good …
> Allow developers to provide their own entity id

- src/MicrosoftTeams.schema.json
- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change gets us ready to release v0.4 of the MicrosoftTeams SDK.
I also snuck an id field into the app manifest schema because I already know we will need it.
> Prepare to release v0.4 of the SDK

- src/MicrosoftTeams.schema.json
Refactored to make gallery tabs, static tabs and bots as top level app properties, each of which also have a defined scope.
> Schema changes to rationalize gallery tabs, static tabs, and scopes

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
In @types/node which is auto-installed in the CI builds, `setInterval` returns a `NodeJS.Timer` object instead of just a number.
I'm not clear on why this is just now suddenly manifesting and only in the CI build, or why the node typings are being downloaded for a web project (based on logs I suspect it has something to do with the gulp-typings install; we should move to use the @types pattern instead in the future), but being explicit about using the `setInterval` on the window object should disambiguate properly.
See details here: https://github.com/Microsoft/TypeScript/issues/842
> Fix intermittent build errors caused by conflicting definitions for setInterval

- src/MicrosoftTeams.ts
This change prevents calls to navigateCrossDomain from the authentication popup since that's not a supported API from that context.
> Prevent navigateCrossDomain calls from authentication popup

- src/MicrosoftTeams.ts
Hiding the *Impl classes from the documentation by marking them private.
> Hiding *Impl classes from docs as they are private

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This new API will allow apps to request a file be opened in the most appropriate Teams client preview mechanism available.
> Add openFilePreview API

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
**Align the configuration experience of 3rd party developed connectors with the existing configuration experience of Tabs across all connector clients.**
**Changes:**
Connectors will return a newly added `SaveResult` object as argument to `settings.save` event which will contain the `webhookUrl` that can be accessed by the 3rd party in their `registerOnSaveHandler` like such: 
```
microsoftTeams.settings.registerOnSaveHandler(function (saveEvent) {
var webhookUrl = saveEvent.result["webhookUrl"];
...... 
}
```
For **Outlook Desktop**, the authentication flow does not contain a pop up because of technical limitations of the client itself. The user experience would be:
> 1. User clicks on Authenticate/Login button on the 3rd party iframed page
> 2. Instead of a pop up, the complete …
> Add support for connectors inline configuration experience

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
Add a new teamSiteUrl Context field that provides a quick pointer to the root SharePoint folder associated with the current team.
> Add a new teamSiteUrl Context field

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
In order to debug various issues our developers have encountered with their apps we have found the need to correlate events between the Teams telemetry and that of the app. We plan to implement this by sharing the Teams sessionId with the tabs we host via the getContext API of our SDK.
> Add sessionId to SDK context to allow for better correlation of telemetry events between Teams and tabs

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This is my first attempt to fix #49, which is caused by a race condition that exists between the notifySuccess/notifyFailure logic running in the authentication window and the code monitoring its lifetime in the parent window. We have two options here:
1. Add an arbitrary wait in the authentication flow after sending the success/failure message before closing the window; this should give the parent window more time to handle the message and complete the flow.
2. Don't call window.close() in the authentication flow at all and always let the parent take care of closing the child window. In the past this has occasionally resulted in child windows failing to close so I would rather avoid this fix for now.
> Add close delay to notifySuccess/notifyFailure calls

- package.json
This change will make package name under Microsoft scope to be publish as npm packages through Microsoft account.
> updating package scope to @microsoft

- src/MicrosoftTeams.ts
Adding a new namespace under microsoftTeams.task. 
Adding a couple of functions: start() to launch the task module and complete() when the task is done
> Changes to the sdk to support the launch and dismissal of the task module

- src/MicrosoftTeams.ts
- Add loginHint, userPrincipalName and userObjectId to tab context.
* loginHint = value suitable as login hint for Azure AD
* userPrincipalName = current user's UPN, whether in-tenant or externally-authenticated
* userObjectId = current user's AAD object id in the current tenant
- Deprecate upn, now superseded by loginHint or userPrincipalName.
> Add richer identity hints to tab context

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change adds two more parameters to openFilePreview:
- editFile - a boolean value indicating whether to open the file directly in edit mode or not
- subEntityId - the ID of the sub-entity to return to after the file file preview is closed
> Add support for file editing and return context in openFilePreview API

- src/MicrosoftTeams.ts
Exception happen when developer open app config URL(that is calling sendMessageRequest) in browser and they haven't implement nativeInterface. Adding a null check before callings its function.
> fixing null exception in sendMessageRequest

- README.md
- gulpfile.js
- package.json
- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
- yarn.lock
The HostClientType must be exported as a const enum so that it gets compiled down to vanilla strings.
> Fix HostClientType enum and prepare to release v1.3.3 of the SDK

- README.md
- package.json
- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change revs the SDK version to v1.3.4 in preparation for release. The release will be done from a different branch.
> Prepare to release v1.3.4

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This PR adds a new exported function `sendMessage` which allows tabs to send custom messages to Teams.
> Added sendCustomMessage function for sending custom messages to Teams

- README.md
- package.json
- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change renames the underlying serialized function name of the tasks.submitTask API to tasks.completeTask so that the SDK library can remain backward compatible with the Teams Mobile clients. This change will be released as v1.3.5 of the SDK.
> Make tasks.submitTask backwards compatible

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change allows the authentication.authenticate and navigateCrossDomain calls to be invoked from the task task modules. Currently they are blocked because the frame context for task modules is set to "task" and these APIs only allow calls in the "content", "settings", or "remove" frame contexts.
> #135 - Allow authenticate and navigateCrossDomain calls from the task module frame context

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change adds the completionBotId field to the TaskInfo structure. This filed allows the developer to specify a bot ID to send the result of the user's interaction with the task module. If specified, the bot will receive a task/complete invoke event with a JSON object in the event payload.
This matches the documentation for our TaskInfo structure here:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview#the-taskinfo-object
> #133 - Need to add completionBotId as a member of TaskInfo

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
adding print capability to client sdk, 
1. By default we it will be disabled App need to call microsoftTeams.enablePrintCapability()
2. microsoftTeams.printHandler: 
App can register custom print handler otherwise by default it will call window.print.
It support
2.1. Ctrl+P 
2.2. Cmd+P (mac)
and 2.3. by calling explicit microsoftTeams.printHandler
> adding print capability to client sdk, App can register custom print handler.

- gulpfile.js
This change will fix issue related to duplicate modules issue in documentation.
this change will replace declare module “@microsoft/teams.js” {
export = microsoftTeams;
}
with 
export = microsoftTeams;
in microsoftTeams.d.ts file use by documentation.
> fixing duplicate module issue

- package.json
- src/MicrosoftTeams.ts
- yarn.lock
adding SharePoint context to teams client sdk context
- adding optional 'sharePointContext' to client sdk Context interface will be use by teams apps in SharePoint context
> adding SharePoint context to teams client sdk context

- package.json
- src/MicrosoftTeams.ts
- yarn.lock
Reverts OfficeDev/microsoft-teams-library-js#149
Reverting this changes in order to fix Typescript errors.
> Revert "adding SharePoint context to teams client sdk context"

- src/MicrosoftTeams.ts
This change allows the settings.getSettings and settings.setSettings APIs to be called form the tab content page. It also adds callback handling to the setSettings call allowing us to return an error to the developer if they try to make a change that doesn't pass validation.
> Add support for calling get/setSettings from tab content page

- src/MicrosoftTeams.ts
Adding two new properties to the teams context to expose the SKU / Azure licenses the user currently has.  Example like EDU license type with either teacher or student category.
> Update the Teams context to include SKU / license properties

- src/MicrosoftTeams.ts
- test/MicrosoftTeams.spec.ts
This change:
1. Adds support for a new beforeUnload event that Teams clients will fire before unloading a tab. The handler for this event will be passed a readyToUnload function that should be called as soon as the tab is ready to be unloaded.
2. Adds handler registration messages that the tab will now send to the Teams client whenever it registers for an SDK event like fullScreen, themeChange, etc.
> Add support for before unload event

- src/public/authentication.ts
- src/public/constants.ts
- src/public/interfaces.ts
Adding 'Rigel' as a supported HostClientType to allow consumers to detect if they are being projected by a Rigel device.  
This will allow users to detect if they are running on a Rigel device by checking the HostClientType returned in GetContext().  
Fix #183
> Adding 'Rigel' as a supported HostClientType

- src/private/index.ts
- src/public/index.ts
exporting private and public api explicit in index.ts file
This change will give control to export subset of functions/vars from a file. It will enable use keeping promise based api in same file with callback and bases on different index file we will export different function.
> exporting private and public api explicit in index.ts file

- src/internal/constants.ts
- test/MicrosoftTeams.spec.ts
Some of our app partners are rolling out support for GCCH and DOD environments so we need to make sure our SDK works there.
> Add GCCH and DOD domains to valid origins list

- .vscode/settings.json
- src/public/interfaces.ts
- test/MicrosoftTeams.spec.ts
This change adds a few missing fields to to the Context object:
- teamSiteDomain
- teamSitePath
- parentMessageId
These have already been implemented in the Teams client but are missing from our library.
> #207 - Add missing fields to context

- src/public/appInitialization.ts
- src/public/constants.ts
- src/public/index.ts
- src/public/interfaces.ts
- src/public/publicAPIs.ts
adding explicit app load, initialization success/fail api
This api can be use by tab to hide loading indicator before notifying appInitialization success/fail.
> adding explicit app load, initialization success/fail api

- src/internal/globalVars.ts
- src/internal/internalAPIs.ts
- src/private/conversations.ts
- src/public/interfaces.ts
- test/MicrosoftTeams.spec.ts
Changes to allow the API to be used in the personal app scope:
- The developer can now send in the thread Id and the entity Id while calling openConversation. This is so that in a personal scope we can start / open a conversation for the subentity in a tab in a particular team.
- We will send back the threadId and the entity Id along with the conversation Id and the subentity Id so that the developer can use it when opening the conversation in a personal app scope.
> Add the capability to use conversational subentity APIs in a personal app scope

- src/internal/globalVars.ts
- src/internal/internalAPIs.ts
- src/public/interfaces.ts
Made the entity Id in the open conversation response as optional.
Also now sending back a ConversationRequest object instead of individual parameters. 
This will be a breaking change but we should be good since the conversational subentity APIs are still in beta and is not being currently used by a lot of devs.
> Changes to the SDK to make the entity Id optional and make the response send an object instead of individual parameters

- generate-dts.js
- package.json
- tsconfig.json
- webpack.config.js
- yarn.lock
This will bundle all individual definition files into one that can be use to provide typing support whne library is not use as import module 
- as triple slash reference (for example in Teams web Client code)
Note: Use same custom logic that is used by office js helpers project
> Bundle all .dts file into one to provide better typing support

- src/public/interfaces.ts
- test/private/privateAPIs.spec.ts
- test/public/publicAPIs.spec.ts
We will stop using the app session Id for telemetry purpose. We will generate a new session Id everytime a tab is created. This will be used for telemetry investigation
> Added the tab session Id in the sdk Context interface

- .eslintrc.js
- .prettierrc.js
- .vscode/settings.json
- generate-dts.js
- package.json
- src/internal/globalVars.ts
- src/internal/internalAPIs.ts
- src/internal/utils.ts
- src/private/privateAPIs.ts
- src/public/authentication.ts
- src/public/publicAPIs.ts
- src/public/settings.ts
- test/private/bot.spec.ts
- test/private/conversations.spec.ts
- test/private/logs.spec.ts
- test/private/privateAPIs.spec.ts
- test/public/authentication.spec.ts
- test/public/publicAPIs.spec.ts
- test/public/settings.spec.ts
- test/public/tasks.spec.ts
- test/utils.ts
- webpack.config.js
This change adds a callback to the initialize API that will be called once initialization completes. This can be used as follows:
```
microsoftTeams.initialize(() => {
// Initialization complete
});
```
Or turned into a promise-based API like so:
```
return new Promise(resolve => {
microsoftTeams.initialize(() => {
resolve();
});
});
```
> #172 - Add callback to initialize

- src/internal/constants.ts
- test/private/privateAPIs.spec.ts
Adding local.teams.microsoft.com as valid host domain for teams sdk
> Adding local.teams.microsoft.com as valid host domain for teams sdk

- src/public/interfaces.ts
For apps which can execute the `placeCall` deeplink adding the following properties in the `Context` 
1. `isCallingAllowed`
2. `isPSTNCallingAllowed`
to check beforehand whether calling & pstn calling is allowed for the current logged in user
> adding isCallingAllowed & isPSTNCallingAllowed in the Context Interface

- src/internal/constants.ts
- src/internal/globalVars.ts
- src/internal/interfaces.ts
- src/internal/internalAPIs.ts
- src/private/bot.ts
- src/private/conversations.ts
- src/private/index.ts
- src/private/logs.ts
- src/private/menus.ts
- src/private/privateAPIs.ts
- src/public/appInitialization.ts
- src/public/appWindow.ts
- src/public/authentication.ts
- src/public/publicAPIs.ts
- src/public/settings.ts
- src/public/tasks.ts
- test/private/privateAPIs.spec.ts
- test/utils.ts
This implements API that allows app channel tabs and personal app to communicate with any child iframes/windows using custom action messages
- (new) (public) initialize() now accepts a list of valid domains from which this window can accept messages
- (new) sendCustomEvent() enables message sending to child
- (new) registerCustomHandler() enables listening to messaging from child
- child window can send message to parent using already existing sendCustomMessage()
- add optional callback to sendCustomMessage()
- add some type safety to message handling logic, handler result tested against undefined instead of truthy
- add Teams domains as valid message origins to allow postMessage processing
- Rename internal API to be parent/child specific
- MessageRequest is only meant for parent
- …
> Enable cross-frame custom messaging in tabs and personalApp

- src/public/interfaces.ts
Add the defaultOneNoteSectionId attribute to the Context interface. This is a new attribute that will be published by the MiddleTier
> Add defaultOneNoteSectionId attribute to the Context interface

- src/public/interfaces.ts
This change adds the localeInfo property to the Context interface in preparation for enabling the Teams Client to provide this information to our hosted apps so that they can respect the OS date & time format settings when displaying this kind of data. Formatting can be handled via the @microsoft/globe library found here:
https://www.npmjs.com/package/@microsoft/globe
> Add localeInfo to the Context interface

- src/public/interfaces.ts
This change adds isArchived, isLocked and TeamType to the private getUserJoinedTeams SDK callback. 
The teams WebClient change is already merged.
> Add isArchived, isLocked, and TeamType info to getUserJoinedTeam

- src/public/authentication.ts
- src/public/interfaces.ts
- test/public/authentication.spec.ts
This change adds a couple of new parameters to the getAuthToken call:
1. `claims` - an optional list of claims which to pass to AAD when requesting the access token; used for SSM/LLT support
2. `silent` - an optional flag indicating whether to attempt the token acquisition silently or allow a prompt to be shown
It also makes the getAuthToken API public since it's now supported for 3P apps as well.
> Add claims parameter to getAuthToken API in Client SDK

- src/internal/constants.ts
- src/public/authentication.ts
- src/public/publicAPIs.ts
- src/public/tasks.ts
- test/public/authentication.spec.ts
- test/public/publicAPIs.spec.ts
- test/public/tasks.spec.ts
Support new frame context for tab rendered in side panel
1. initialize
2.  authenticate APIs, getAuthToken, getUser, 
3. navigateCrossDomain, registerThemeChangeHandlers
4. shareDeepLink
5. executeDeepLink
6. Tasks APIs
1. Conversation APIs
2. enterFullscreen, exitFullscreen
3. openFilePreview
4. showNotification
5. registerChangeSettingsHandler, setFrameContext,
6. Settings APIs
> Support new frame context for tab rendered in side panel

- src/public/interfaces.ts
- test/public/publicAPIs.spec.ts
exposing meetingId as part of tab sdk which will be use by tabs running in meeting context.
> exposing meetingId as part of tab sdk

- src/public/publicAPIs.ts
This change allows the `microsoftTeams.executeDeepLink` API to be called from the tab configuration dialog (i.e. `settings` frame context)
> Allow the executeDeepLink API to be called from the tab configuration dialog

- src/public/media.ts
- test/public/media.spec.ts
This is a minor fix on top of the selectMedia API. When objects are sent over from native layer (Android or iOS) they are just objects and do not have a type. In selectMedia callback, we promise to deliver Media objects. Sending the objects as received from native layer does not really send Media objects, they do ducktype Media, but will be missing getMedia method.
The fix is to have one level of indirection, receive the array from native in our callback and create new Media objects which confirms with the promise and return those.
> Fix the type in Media[] returned in selectMedia callback

- src/private/menus.ts
Upcoming versions of the teams mobile client require icon to be set for the Action Menu to work properly.
> Align interface with Teams mobile client

- .gitignore
- src/private/interfaces.ts
- src/public/appInitialization.ts
- src/public/constants.ts
- src/public/interfaces.ts
- src/public/media.ts
The change is only to have imported const enum to be just enum.
https://github.com/OfficeDev/microsoft-teams-library-js/issues/267
I do not see an issue if we just import enum rather than const enum
Few useful references on why const enum does not work in some scenarios:
https://ncjamieson.com/dont-export-const-enums/
microsoft/TypeScript#5243
> Removed const enum as it creates issue with some projects

- src/public/index.ts
- test/public/publicAPIs.spec.ts
Media API enums were not exposed properly for API consumer. Corrected that.
Also one of the test had hard coded version number, which is now moved into a reference to version from constants.ts
> Expose media API enums properly

- src/internal/globalVars.ts
- src/internal/internalAPIs.ts
- src/public/index.ts
- src/public/publicAPIs.ts
- test/public/publicAPIs.spec.ts
Previous single app button hover api was not sufficient. Both a hover enter and hover leave API are now added to allow the sdk consumer to engage functionality both when entering hover and leaving hover.
> App button hover enter and leave APIs

- src/public/navigation.ts
Limit returnFocus API to content FrameContext
> Limit returnFocus API to FrameContexts.content 

- src/public/index.ts
When we moved from const enums to enums in #267, the exported list did not have ChannelType. Earlier when it was a const enum, it worked without this export. Now this export is needed.
> Export ChannelType from index.ts

- src/private/index.ts
- src/private/interfaces.ts
- src/private/privateAPIs.ts
- test/private/privateAPIs.spec.ts
Previously teams used to support opening a file only in view/edit mode. Hence we were using a boolean `editFile`.
Teams, can now support multiple modes.(`"view" | "edit" | "editNew"`). Adding a new filePreviewParameter to enable this.
> Update filePreviewParameters for openFilePreview

- src/internal/internalAPIs.ts
- src/internal/mediaUtil.ts
- src/public/media.ts
**Scenario**
Currently callbacks were supported for request/response but only one response could be sent for a callback. We have modified the pattern by introducing a new field isPartialResponse. If isPartialResponse is set to true callback will not be deleted on teams js sdk library and multiple callbacks can be sent back using the same id. When the platform doesn't need to send anymore callback, in the final one it can remove the isPartialResponse field and use the existing postIDResponse() or use postCompleteResponse() function to send the final callback. (which will get deleted on the platform)
getMedia needs to send more than one response. It was using handlers before but now we have onboarded getMedia() to callbacks with isPartialResponse.
[comment]: # "What is the user scenario …
> Adding partial response infra to postIDResponse callback and Change getMedia API's postResponse from handler to callback with backward compatibility

- src/public/media.ts
- test/public/media.spec.ts
ScanBarCode API is only available for mobile platform and not supported on Desktop and web platform
ErrorCode.NOT_SUPPORTED_ON_PLATFORM (i.e 100 errorcode) will be returned in the callback on desktop and web platform.
Tests:
Did manual testing using a custom app, tested the following:
- ScanBarCode API works on mobile platform
- ScanBarCode API returns ErrorCode.NOT_SUPPORTED_ON_PLATFORM (i.e 100 errorcode) on desktop and web platform
> Scan BarCode API to return NotSupported Error on desktop and web platform

- src/public/interfaces.ts
- test/private/privateAPIs.spec.ts
This will be used by the WPX apps mostly to understand where the tab was opened from and the timestamp when the tab was opened
> Add the sourceOrigin and userClickTime in the getContext call

- src/internal/constants.ts
This change allows Teams Apps to be hosted in the Teams For Life Client.
> Add TFL domain to valid origins list

- src/public/meeting.ts
As discussed in 1CS team meeting, we are going to hide `getAuthenticationTokenForAnonymousUser` from public so marking it as private
> hide skype token

- src/public/settings.ts
Both configuration and removal of connectors happens in the settings context and therefore the `registerOnRemoveHandler` API should be supported there.
> #435 - registerOnRemoveHandler is not allowed in the settings context

- src/public/interfaces.ts
- test/private/privateAPIs.spec.ts
This PR adds the field teamTemplateId to the context object, which is an optional field to be populated if the team object was created with a Team Template.
> adding teamTemplateId to getContext

- src/public/constants.ts
Add surfaceHub2 platform to HostClientType with value='surfaceHub'.
Use this value for SurfaceHub 2s specific scenarios/workflows.
> Add surfaceHub platform to HostClientType

- src/internal/constants.ts
- src/private/privateAPIs.ts
- src/public/location.ts
- src/public/media.ts
- src/public/people.ts
- test/public/location.spec.ts
Explain Defect
- The android client released support for a private JS SDK API userJoinedTeams(), support for the same was released at around August 2020.
- However, the released native implementation had a bug that did not return the correct user role. It returned Admin as the role for all TeamInformation.userTeamRole returned. This impaired critical workflows in the Assignments app, wherein they show different UI based on whether a user is a teacher or a student, leading to a student seeing UI meant for a Teacher.
- The bug was fixed for the android client release in January 2021, for the build version number 1416/1.0.0.2021022202.
- However even with the fix, there are customers who are on an older version of the android client, due to the critical nature of the impact, assignments is …
> Added check for clientSupportedSdkVersion and hostclient for `getUserJoinedTeams` execution on android

- src/public/meeting.ts
- test/public/meeting.spec.ts
- Adding error property to liveStreamState, so that we can expose streaming errors to the apps.
- Removing liveStreamState property from the start, stop callback as the developer will anyway need to use registerLiveStreamChangedHandler to subscribe to changes from service side.
> Adding error to LiveStreamState and updating start, stop APIs

- src/private/remoteCamera.ts
Adding another enum to handle an additional potential remote camera session termination reason
> Adding new session terminated enum

- src/private/teams.ts
- test/private/teams.spec.ts
The following PR introduces the following new private API
`teams.getTeamsChannels`
This will be privateAPI that will be nested under `teams` namespace. It will be allowed only for 1P apps.
> Get a team's channels by providing teamId API

- src/public/meeting.ts
- test/public/meeting.spec.ts
Incoming Audio APIs will only be supported in side panel
getAuthenticationTokenForAnonymousUser API will only be supported in side panel
getMeetingDetails API will be supported in sidePanel, meetingStage, setting*, content contexts
*setting context is available in in-meeting and also in pre/post meeting. meeting details is only supported in pre/post meeting and not in-meeting settings context. API will still be a no-op when called from in-meeting context.
> Add frame context check for meeting APIs

- src/public/interfaces.ts
- test/private/privateAPIs.spec.ts
- test/public/publicAPIs.spec.ts
Problem: Currently we have the appSessionId that is used to understand availability issues and debug them. Its a unique id that is shared with the developer (via getContext). When an issue happens then we can correlate the two telemetry pipelines (Teams and Developer's Telemetry) and understand what the actual issue was.
But with app caching, the appSessionId will persist across sessions. So its difficult for some teams (like WPX) to understand which session actually failed.
Solution: We are introducing a new id called appLaunchId which will be different across different cached sessions.
> Add the app launch id to the getContext call.

- src/public/meeting.ts
- test/public/meeting.spec.ts
This PR adds the `stopSharingAppContentToStage` API to the Teams Client Library.
The `stopSharingAppContentToStage` API is used for terminating a current stage sharing session during a meeting. 
In the event of an error, an `SDKError` error will be returned. In the event of a successful stage sharing termination, `true` will be returned
> Add stopSharingAppContentToStage API

- src/private/teams.ts
Removed `threadId` from callback, which is no needed.
> Removed threadId from callback

- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/constants.ts
- packages/teams-js/src/internal/interfaces.ts
- packages/teams-js/src/internal/internalAPIs.ts
- packages/teams-js/src/internal/mediaUtil.ts
- packages/teams-js/src/internal/utils.ts
- packages/teams-js/src/private/appEntity.ts
- packages/teams-js/src/private/bot.ts
- packages/teams-js/src/private/chat.ts
- packages/teams-js/src/private/files.ts
- packages/teams-js/src/private/interfaces.ts
- packages/teams-js/src/private/legacy.ts
- packages/teams-js/src/private/logs.ts
- packages/teams-js/src/private/meetingRoom.ts
- packages/teams-js/src/private/menus.ts
- packages/teams-js/src/private/notifications.ts
- packages/teams-js/src/private/privateAPIs.ts
- packages/teams-js/src/private/remoteCamera.ts
- packages/teams-js/src/private/teams.ts
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/meeting.ts
- packages/teams-js/src/public/monetization.ts
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/people.ts
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/src/public/sharing.ts
- packages/teams-js/src/public/teamsAPIs.ts
Turns out that the @privateRemarks tag is not currently supported by TypeDoc generator used by MS Docs for TypeScript documentation. To suppress comments from publish on docs.microsoft.com, the recommendation is to use @hidden.
> Rename @privateRemarks TSDoc tag to @hidden

- azure-pipelines.yml
Pipeline failed due to incorrect syntax of yaml. Did a no-brainer merge when saw all green.
Erin has updated policies and included our pipelines to check on every PR. Thank you Erin.
> Build pipeline yaml syntax correction

- apps/teams-test-app/webpack.config.js
Currently, we cannot debug source files in orange-hub by inspecting. Adding `devtool: 'inline-source-map',` in webpack in appSDk allows it to do so.
> adding inline-souce-map to make dubgiing easier

- packages/teams-js/src/private/meetingRoom.ts
In MeetingRoomCapability and MeetingRoomState interfaces, fields are restricted to only some string values. However, we are not enforcing this in code (only written in comments). This PR restricts these fileds to take only values they suppose to take. 
I used `type` to limit a variable to only some certain strings. Please let me know if there is a better way to achieve the same purpose (e.g. using eums)
> Lakhveer/meeting room capabilities/state restriction 

- packages/teams-js/src/internal/internalAPIs.ts
- packages/teams-js/test/private/chat.spec.ts
- packages/teams-js/test/private/files.spec.ts
- packages/teams-js/test/private/pages.spec.ts
- packages/teams-js/test/private/teams.spec.ts
- packages/teams-js/test/public/app.spec.ts
- packages/teams-js/test/public/authentication.spec.ts
- packages/teams-js/test/public/config.spec.ts
- packages/teams-js/test/public/dialog.spec.ts
- packages/teams-js/test/public/locationLegacy.spec.ts
- packages/teams-js/test/public/media.spec.ts
- packages/teams-js/test/public/navigation.spec.ts
- packages/teams-js/test/public/settings.spec.ts
- packages/teams-js/test/public/tasks.spec.ts
- packages/teams-js/test/public/video.spec.ts
This fixes a recent suggestion: https://github.com/OfficeDev/microsoft-teams-library-js/issues/688
Sample error message with the change:
> Uncaught Error: This call is only allowed in following contexts: ["settings"]. Current context: "content".
> Include expected FrameContext in error message from ensureInitialized

- apps/teams-test-app/README.md
- apps/teams-test-app/src/components/AppAPIs.tsx
- apps/teams-test-app/src/components/CalendarAPIs.tsx
- apps/teams-test-app/src/components/utils/ApiContainer.tsx
- apps/teams-test-app/src/components/utils/ApiWithCheckboxInput.tsx
- apps/teams-test-app/src/components/utils/ApiWithTextInput.tsx
- apps/teams-test-app/src/components/utils/ApiWithoutInput.tsx
- apps/teams-test-app/src/components/utils/index.ts
This PR adds a new set of utility React Components which should be used to add API support to Test App. These Components contain a bunch of shared logic around input parsing and handling. It also allows for better validation of said input using TypeScript's type system. This way a lot more errors we've seen only at runtime would show at compile time.
I also added a *Contributing* section in Readme which has a bit of information on how these should be used.
~Things I'd still like to do:~
- ~move some of the shared HTML elements to a base component to make sure they stay consistent no matter what kind of input is expected for the API~
- ~E2E scenario test validation~
- ~documentation on how to use these when adding new API support to Test App~
> New React components for TestApp with better input validation

- README.md
Root readme and readme in package folder don't match, and this one was missing a required step.
Also, I *think* this one should pass all the checks finally since it's no longer a personal fork merging back into the main repo. I hope.
> Add missing yarn install line to README

- apps/teams-test-app/src/components/SharingAPIs.tsx
1. Adding input box in test app for shareWebContent API (API takes an input) 
2. Adding a new frame in test app to check whether or not sharing module is supported
> Fixing Sharing in test app

- apps/teams-test-app/src/components/DialogAPIs.tsx
- packages/teams-js/src/public/dialog.ts
- packages/teams-js/src/public/tasks.ts
Addresses https://github.com/OfficeDev/microsoft-teams-library-js/issues/444 in 2.0-preview branch for both the new `dialog.open` and backwards-compatible `tasks.startTask`.
> Type `result` as `string | object` in `dialog.submitHandler`

- azure-pipelines-with-e2etests.yml
- package.json
- packages/teams-js/webpack.config.js
- yarn.lock
Update webpack-dev-server types to match webpack 5 versions and stop generating module wrappers in MicrosoftTeams.d.ts
> Documentation fixes for release

- packages/teams-js/src/public/appInitialization.ts
- packages/teams-js/src/public/appWindow.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/src/public/constants.ts
- packages/teams-js/src/public/index.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/location.ts
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/meeting.ts
- packages/teams-js/src/public/navigation.ts
- packages/teams-js/src/public/people.ts
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/src/public/settings.ts
- packages/teams-js/src/public/tasks.ts
Update each @deprecated tag to point to the replaced API and use the @link tag inside the @deprecated comments with full signature.
For example:
` @deprecated As of 2.0.0-beta.1. Please use {@link app.initialize app.initialize(validMessageOrigins?: string[]): Promise\<void\>} instead.`
> Update each @deprecated tag to point to the replaced API

- packages/teams-js/src/public/index.ts
These tags caused a warning during doc generation because in the MicrosoftTeams.d.ts file the things they were referencing were removed, which meant we just had 5 deprecated comments in a row at the top of the file. I checked, and each function/module marked as deprecated in index are ALSO marked as deprecated in their actual files, and removing the deprecated tags from index appears to have no impact on the actual documentation (other than fixing the warning)
If the @deprecated tags in index are doing something else that I don't know about let me know!
> Remove unnecessary deprecated tags from index

- apps/teams-test-app/src/components/privateApis/MeetingRoomAPIs.tsx
I fixed meetingAPI in my last PR where instead of calling states update handler, we were calling capabilities handler for states. It was most likely a typo).  But somehow, we are back to the previous errors stage (A new push (https://github.com/OfficeDev/microsoft-teams-library-js/commit/bb52fd3ea108e84195094ef6a5eafd6755865e1d#diff-2fe57e8385413dc51d9a46541abea26d2919811b266f80e28a143a6bb1285d7c
reverted these changes back to the error state.
> Fixing StatesHandler in MeetingRoom

- apps/teams-test-app/src/components/PagesAPIs.tsx
- packages/teams-js/src/internal/utils.ts
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/internal/utils.spec.ts
- packages/teams-js/test/public/pages.spec.ts
* Create new NavigateToApp API that can navigate to a given App ID, Page ID, and with an optional Web URL, Sub-page ID and Channel ID
* Detect if we are running against a legacy Teams client, and if so, build the corresponding deep link and call the ExecuteDeepLink API instead
* Tests for both flows
> NavigateToApp API and tests

- README.md
- packages/teams-js/README.md
Add 2.0-preview branch information to the README that is published with the npm package. Also cleaned up Getting Started commands.
> Add 2.0-preview branch information to the README

- src/public/meeting.ts
This PR makes all programmatic app sharing APIs. Affects:
- `shareAppContentToStage`
- `getAppContentStageSharingCapabilities`
- `getAppContentStageSharingState`
Note: `stopSharingAppContentToStage` was previously privatized
> Privatize all programmatic app sharing APIs

- apps/teams-test-app/src/components/RemoteCameraAPIs.tsx
In test-app, the capability check box was missing for remote camera. Adding that!
> Adding capability check in remoteCamera in test app

- packages/teams-js/src/public/navigation.ts
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/src/public/settings.ts
- packages/teams-js/test/public/navigation.spec.ts
- packages/teams-js/test/public/publicAPIs.spec.ts
There are few places in v1(master) where the return of the method getGenericOnCompleteHandler used when the user doesn't provide a callback.
appWindow.ts
- ChildAppWindow.postMessage
- ParentAppWindow.postMessage
navigation.ts (deprecated)
- navigateToTab
- navigateCrossDomain
- navigateBack
publicAPIs.ts (deprecated)
- executeDeepLink
settings.ts (deprecated)
- setSettings
I have updated the deprecated code with the generic handler. 
For appWindow.ts functions, they throw an error when the promise fails, so no need to update it.
> Update v2 with getGenericOnCompleteHandler when the user didn't provide a callback.

- azure-pipelines.yml
The publish to CDN Feed step requires us setting a variable in the release pipeline to set the version as a blob prefix. 
This is not allowed on prod pipelines for compliance reasons. The alternative is to create a folder structure as: CDNFeed/{version}/js, and then upload the CDNFeed folder directly. 
This should result in www.{cdnDomain.com}/{version}/js
> Adding version folder to cdnfeed artifact

- apps/teams-test-app/src/components/AppAPIs.tsx
- apps/teams-test-app/src/components/utils/ApiWithoutInput.tsx
Modified the onClick property to contain to separate function handlers, withPromise and withCallback. withPromise will function as it currently does, while withCallbacks will be used by API's that are run in backwards compatibility mode
> Modified ApiWithoutInput to account for callbacks

- packages/teams-js/jest.config.js
- packages/teams-js/prepNextDevRelease.js
- packages/teams-js/src/internal/constants.ts
- packages/teams-js/webpack.config.js
Instead of having the version set in two places, we can rely on webpack to pull the value from package.json and inject it in the constants file during build time.
This makes life easier when bumping versions. Only one value will need to be updated.
> Setting version constant in one place

- apps/teams-test-app/src/components/AppAPIs.tsx
- apps/teams-test-app/src/components/LocationAPIs.tsx
- apps/teams-test-app/src/components/privateApis/MonetizationAPIs.tsx
- apps/teams-test-app/src/components/utils/ApiWithTextInput.tsx
- apps/teams-test-app/src/components/utils/ApiWithoutInput.tsx
Update `withCallback` utils in `ApiWithTextInput` and `ApiWithoutInput`, avoid redundant of using `noHostSdkMsg` at every call.
> Update withCallback utils

- src/public/index.ts
Erin checked with Yuri and it sounds like not exporting this was an oversight in the main branch.
> Add FrameContext to public\index.ts exports

- packages/teams-js/src/public/authentication.ts
- packages/teams-js/test/public/authentication.spec.ts
getAuthToken took in a parameter that was an array that contained only optional values. Made the array an optional parameter as well and added two new unit tests to verify that passing in no array still works as expected.
This is a fix for bug #5377609
> Made getAuthToken's param optional

- package.json
I think this is the only script command we have that isn't happy when you run it on a Mac. Tested it on Mac and Windows and it works on both.
> Make the clean command work on non-Windows platform

- apps/teams-test-app/src/components/MeetingAPIs.tsx
> liveStreamState interface of meeting has error response struct which is used to notify incase of error. This PR contains changes in test app to print error response in output for testing
> Test App: Print error response in the output of liveStreamState Handler

- apps/teams-test-app/tsconfig.json
- packages/teams-js/package.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/handlers.ts
- packages/teams-js/src/internal/telemetry.ts
- yarn.lock
This change is a first stab at adding trace logging to TeamsJs v2. It integrates [debug ](https://www.npmjs.com/package/debug) package and uses it to add trace logging around app->parent communication: sending, queuing, receiving and handling messages between the application and the parent host.
The logging is disabled by default and can be turned on by setting a logging pattern in local storage:
```
localStorage.debug = "teamsJs:*"
```
Sample output for a test app loaded successfully, followed by `getContext` call, `registerThemeChanged` and host notifying the application about the theme changing:
In subsequent changes, assuming there's an agreement around this change, I'll add similar trace logging around app->child communication and other important aspects of the SDK.
Open questions:
> Add trace logging to TeamsJs

- package.json
- tools/cli/prepNextRelease.js
With this script, we can just run `yarn release` from the root of the repo, and that will automatically do all the following steps: 
1. Checkout 2.0-preview and pull it from origin
2. Update the package.json version by incrementing the beta value
3. Build teams-js and copy the new integrity hash back into the readme
4. checkout a release/{newVersion}, commit the changes, and push that branch.
Once a branch with release* gets pushed, the CI pipeline will trigger and build artifacts. If the CI pipeline passes, the production release pipeline triggers and publishes the respective artifacts to npm/cdn. The prod release pipeline will require approval if we want to sanity check the artifacts before we allow the publishing.
#793 Note: This is related to this PR too. That PR will also update the …
> Updating prepRelease script

- apps/teams-test-app/src/components/PagesAPIs.tsx
- apps/teams-test-app/src/components/PagesAppButtonAPIs.tsx
- apps/teams-test-app/src/components/PagesBackStackAPIs.tsx
- apps/teams-test-app/src/components/PagesTabsAPIs.tsx
Added in callback capability for the navigation API depending on if we are in Teams JS v1 mode or TeamsJSv2 mode.
Update one of `pages.tabs` titles to `pages.appButton` since `RegisterAppButtonClickHandler`, `RegisterAppButtonHoverEnterHandler`, and `RegisterAppButtonHoverLeaveHandler` have been moved to a new sub-capability pages.appButton.
> Backwards compatibility for navigation API and update pages.appButton title

- src/private/menus.ts
Introduced Display Mode Enum & corresponding property to `MenuItem` part of `setNavBarMenu` 
- This feature is required by both iOS and Android platforms as part of **setNavBarMenu** API
- Adding capability for Web Apps to define how a menu items should appear in the NavBar, either on the NavBar or inside the Overflow Menu.​
- JS SDK Changes
- Added DisplayMode enum, consisting of the following options.
- ifRoom – Only place this item in the NavBar if there's room for it. If there's no room, item is shown in the overflow menu.​
- never - Never place this item in the NavBar. The item would always be shown in NavBar's overflow menu. ​
- Adding new property displayMode as part of MenuItem.​
- If null, the behavior would default to ifRoom.​
- API is modelled on similar lines as showAsAction …
> Added DisplayMode Property to MenuItem as part of setNavBarMenu API

- README.md
Still need to fix the coverage badge. 
Build badges look like this:
> Fixing build badges and moving them to top

- apps/teams-test-app/src/components/MeetingAPIs.tsx
Previously we JSON stringified a string value, this was unnecessary and led to failures in tests
> Fixed a bug with getAuthenticationTokenForANonymousUser callback

- apps/teams-test-app/src/components/utils/ApiWithTextInput.tsx
-  In Android UI testing, we found Reacts internal state of maintaining _input_ did not get updated with correct values because the onChange event does not fire when Android copies the value directly to DOM while testing. This change ensures the Input is always read from DOM.
> Reading input in test app directly from DOM element using ref

- azure-pipelines.yml
First step in taking our numerous yaml files and combining them into one. This PR will allow for us to not only avoid depending on several pipeline runs but also keep the jobs parallelized and efficient.
A few notable/potentially confusing points explained:
- Newly introduced pipeline variables `$(AppHostingSdkGitPath2)`, `$(AppHostingSdkGitPath3)`, etc. (Example: Line 317)
- These `$(AppHostingSdkGitPath#)` variables actually contain the same value as the original `$(AppHostingSdkGitPath)` variable. This is the best getaround I've found to YAML's issue which doesn't allow for checking out the same repository defined by the same variable more than once in the same file. 
- If we're combining the yaml files, why aren't the old ones being deleted?
- Before this PR is merged, all of this …
> Combine our yaml files

- .github/workflows/prerelease.yml
This will add the manually triggerable workflow to master. The workflow on master will not really do anything now. 
However for the same workflow in 2.0-preview to become available for invoking, we need to add this file to master.
For context, we are creating these workflows in 2.0-preview to facilitate the release process, and automate all manual steps that would need to be done by developers when a new version is to be released. More details in #865
> Adding prerelease yml to master

- src/public/meeting.ts
This PR makes release-ready programmatic app sharing APIs. Affects:
- `shareAppContentToStage`
- `getAppContentStageSharingCapabilities`
- `getAppContentStageSharingState`
Note: stopSharingAppContentToStage will be kept `private`
> Publicize release-ready programmatic app sharing APIs

- beachball.config.js
- change/@microsoft-teams-js-e47e48ff-feb5-4cf2-989a-a7e830948544.json
- change/@microsoft-teams-js-eb072478-2fb7-4472-8af2-5c8fbfa6e30d.json
- change/@microsoft-teams-js-f11bf3ab-5159-4a30-8cfe-6a1ef412b684.json
- packages/teams-js/CHANGELOG.md
- tools/cli/preRelease.js
- tools/cli/readChangelog.js
Changelog modifications: 
- Removed the 2.0.0-beta.3 part into changefiles. We can rely on beachball bump to add them on the next release.
- Updated older parts to match the formatting beachball creates
Added beachball bump to release script and made respective changes to update the version value accordingly
Added a beachball config to not render the author into the changelog. _These will still show up in the temporary changefile artifacts however, and get deleted once the bump happens_
> Hooking up beachball to release scripts

- apps/teams-test-app/src/components/CalendarAPIs.tsx
- change/@microsoft-teams-js-744961a1-af6b-4a44-b128-31e9e6f0c4e9.json
- packages/teams-js/src/public/appInstallDialog.ts
- packages/teams-js/src/public/calendar.ts
- packages/teams-js/src/public/call.ts
- packages/teams-js/src/public/mail.ts
- packages/teams-js/test/public/appInstallDialog.spec.ts
- packages/teams-js/test/public/calendar.spec.ts
- packages/teams-js/test/public/call.spec.ts
- packages/teams-js/test/public/mail.spec.ts
- tools/cli/preRelease.js
- tools/cli/readChangelog.js
Solves bug number #5720429 in ADO.
While Javascript allows throwing objects that aren't Error objects, it is still good style to throw Errors to capture all of the properties that can typically be expected from what is thrown and also to have a more descriptive stack trace.
> Replace instances of throwing strings to throw errors instead

- .github/workflows/main.yml
- .github/workflows/postrelease.yml
- .github/workflows/prerelease.yml
- azure-pipelines.yml
- tools/yaml-templates/security.yml
Change summary: 
- Changed Azure Pipeline CI trigger to run on v2.0.0-beta tags, and updated respective asset retention conditions.
- Removed the trigger in the GitHub Azure pipeline for release branch since we don't use that as a status check
- Removed the automated PR create to merge the release branch back into 2.0-preview. Release manager will just create the PR manually to bypass Github workflow recursive trigger issue.
- Removed the default version from 2.0.0-beta.x to reduce the chance of a typo. Release manager would have to type it all in.
> Updating release triggers

- beachball.config.js
- change/@microsoft-teams-js-828b759f-2466-4a17-9110-350aee8e7a35.json
This change includes a fix for using a cross-plat compatible path separator so that when the preRelease.js script runs on Ubuntu machines, we will detect and delete the CHANGELOG.json.
Also clean up a change comment before it's included in the CHANGELOG for beta.3.
> Minor fixes before beta.3 release

- src/private/index.ts
- src/private/privateAPIs.ts
- src/public/index.ts
- src/public/menus.ts
- src/public/publicAPIs.ts
Making the following API's public 
- setUpViews
- setNavBarMenu
- showActionMenu
This is an ask from the Product as they want to increase usage of the API by 3rd Party App Developers
Verified tests are passing locally by running `yarn test`
Queries
- Is there anything we need to consider from Desktop as the ask is from Mobile Side
> Making Menu APIs Public

- src/private/files.ts
- test/private/files.spec.ts
This PR contains improvements to openDownloadFolder API which is added in [this](https://github.com/OfficeDev/microsoft-teams-library-js/pull/858) PR. The improvements are :
1. Added file path open support 
2. Added callback to openDownloadFolder
> Improvements to openDownloadFolder API

- change/@microsoft-teams-js-1aa1bef9-f735-4ec8-8750-c52beaefc9cc.json
- packages/teams-js/src/internal/constants.ts
Considering this is a very small change, I thought it wouldn't make sense to create an issue for it.
Unable to load any multi-host app in OWA at office365 domain.
Navigate to any app using office365's domain, e.g. https://outlook.office365.com/host/f3a6e67f-850d-4dd9-960a-04c6638ded36/browse?actSwt=true
For every message an App receives from the Host (sender), i[t's performed a check as to whether it is sent by a verified sender](https://github.com/OfficeDev/microsoft-teams-library-js/blob/690a641386b2e37dc166837fdcdc52d2ef951462/src/internal/communication.ts#L122). Among other things, it [checks whether the sender's origin matches a list of valid origins](https://github.com/OfficeDev/microsoft-teams-library-js/blob/690a641386b2e37dc166837fdcdc52d2ef951462/src/internal/communication.ts#L15 …
> Adds office365 domains to whitelist

- CODEOWNERS
- CONTRIBUTING.md
The CODEOWNERS file now reflects the updated internal team structure in the 2.0-preview branch.
Also fixed a small typo.
> Update codeowners file (2.0-preview)

- tools/yaml-templates/build-test-publish.yml
Disable the command that posts the bundle analysis report because it's failing due to an external issue. Prefer that we stop seeing a failure to post, which we might get used to. 
When that issue is resolved, I will re-enable the task.
> Disable the post bundle analysis task

- src/public/meeting.ts
- test/public/meeting.spec.ts
Enabling below API's in meeting stage.
1. shareAppContentToStage
2. getAppContentStageSharingCapabilities
3. stopSharingAppContentToStage
4. getAppContentStageSharingState
There are apps who want to switch from one url to another and stage will be replaced with new url.
One of the sharing api provides capabilities and app want to know on stage "Am I the current presenter?" This helps app to change the UI based on presenter and attendee.
Co-watch wants this capability.
> Enabling Share App Content to Stage in Meeting Stage

- src/public/interfaces.ts
The enum in `constants.ts` has the `surfaceHub` value, but the comment in `interfaces.ts` does not. This change fixes the comment.
> Add missing hostClientType value in comment

- change/@microsoft-teams-js-05fb4856-6573-46c7-bcf9-5398222e0a3b.json
- packages/teams-js/src/internal/chatConstants.ts
- packages/teams-js/src/internal/chatUtilities.ts
- packages/teams-js/src/internal/constants.ts
- packages/teams-js/src/public/chat.ts
- packages/teams-js/test/internal/chatUtilities.spec.ts
Create utility function for constructing a chat deep link URL
This utility function will be used to create a deep link URL that will
be sent to the host if it is determined that the host is "legacy teams"
and would not understand the chat capability messages.
This change does not actually execute the deep link (that will be in
the next change), it only constructs the deep link. It also includes
unit tests to validate the construction.
> Create utility function for constructing a chat deep link URL

- change/@microsoft-teams-js-ecfa8660-07cf-4fd0-95e9-8403185cddb3.json
- packages/teams-js/src/public/chat.ts
- packages/teams-js/test/internal/chatUtilities.spec.ts
- packages/teams-js/test/public/chat.spec.ts
Older versions of Teams will not understand standard chat messages when functions on the `chat` capability are called. When running in older versions of Teams, these function calls will be converted to the older-style deep links and sent that way instead.
> Send chat requests to legacy Teams as deep links

- src/public/interfaces.ts
- src/public/meeting.ts
- test/public/meeting.spec.ts
This PR adds an additional type of MeetingDetailsCallType to support calls in meetings. This keeps the original MeetingType of getMeetingDetails, while adding the types of oneOnOneCall and groupCall to possible types returned by the getMeetingDetails API.
> Adding call types to meeting details

- azure-pipelines.yml
This build step only runs on release builds, so I'm updating the display name in case people get confused about why it was skipped for their build.
> Update CDN test name for clarity

- src/public/constants.ts
Feature: https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1774162
iPad Experience 
As a part of above feature we are sending the hostClientType via getContext as "ipados" if the client device is iPad.
Hence adding the same constant on the enum HostClientType.
> Added ipadOS to HostClientType

- change/@microsoft-teams-js-aa2116d9-a745-445b-8ff6-e9acf702cd08.json
- packages/teams-js/src/public/dialog.ts
- packages/teams-js/test/public/dialog.spec.ts
Sending an empty array is less error prone than sending `undefined` in an array.
> dialog.submit sends an empty array in case of no appIds

- change/@microsoft-teams-js-a1c16808-8fc1-4d4d-8638-ff5b68c0e802.json
- packages/teams-js/src/internal/deepLinkConstants.ts
According to this, should be topicName: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links
> topic param name was wrong for group chat deep links

- packages/teams-js/CHANGELOG.md
This change was introduced prior to Public Preview, however it was never documented in the changelog.
We recently discovered they may be other side effects of outputting ES6 modules from TypeScript instead of CommonJS, so this may be useful for developers.
> Add info to changelog about outputting ES6 modules from TS

- src/private/privateAPIs.ts
This change allows the openFilePreview API to be called from task modules.
> Allow openFilePreview calls from the task frame context

- change/@microsoft-teams-js-4eaeabce-50a9-4ef9-af6b-a1d1da4d1309.json
- packages/teams-js/src/public/tasks.ts
the host should size the dialog to fit the requested adaptive card if no size is specified. This is how it was in v1.
> adaptive card based dialogs shouldn't have small (default) dialog height, if the height is not provided. 

- change/@microsoft-teams-js-ccca7dc2-0d2d-45a2-b7e7-74463ea5fb5f.json
- packages/teams-js/src/private/appEntity.ts
- packages/teams-js/src/private/conversations.ts
- packages/teams-js/src/private/interfaces.ts
- packages/teams-js/src/private/meetingRoom.ts
- packages/teams-js/src/private/remoteCamera.ts
- packages/teams-js/src/public/appInstallDialog.ts
- packages/teams-js/src/public/appWindow.ts
- packages/teams-js/src/public/calendar.ts
- packages/teams-js/src/public/call.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/location.ts
- packages/teams-js/src/public/mail.ts
- packages/teams-js/src/public/monetization.ts
- packages/teams-js/src/public/people.ts
- packages/teams-js/src/public/sharing.ts
- packages/teams-js/src/public/teamsAPIs.ts
- packages/teams-js/src/public/video.ts
Remove @alpha tags as they are not supported in the SDK reference doc generation system.
As far as I can tell, they were added when we made the code changes to support TSDoc instead of JSDoc for Public Preview, however we later learned that the documentation generation tools support TypeDoc with a few exceptions.
I believe the motivation when we added these tags was to identify APIs that were newer, but I don't think we  have a formal approach for this, we did not use alpha or beta tags in v1, and the selection seems rather arbitrary, so I am just removing them.
> Remove @alpha tags from docs comments

- change/@microsoft-teams-js-c0aa6182-1a47-4745-bb95-33ef415bb07e.json
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/meeting.ts
We received feedback that while the functions in media.ts will not currently work in a cross-host environment, there is still active 3P development occurring involving these APIs and it would be confusing for developers to have them marked `@deprecated` without pointing to replacement functions.
The functions in meeting.ts aren't actually problematic, but the current structure doesn't lend itself to the capability model across all hosts. We don't really need the `@deprecated` tag to convey this to developers.
> Remove deprecated tags from media.ts and meeting.ts

- change/@microsoft-teams-js-7bb78d87-087d-498a-aede-24ea1245c3c3.json
- packages/teams-js/src/public/appInitialization.ts
- packages/teams-js/src/public/constants.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/location.ts
- packages/teams-js/src/public/monetization.ts
- packages/teams-js/src/public/navigation.ts
- packages/teams-js/src/public/people.ts
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/src/public/settings.ts
- packages/teams-js/src/public/sharing.ts
- packages/teams-js/src/public/stageView.ts
- packages/teams-js/src/public/tasks.ts
We received guidance that in preparation for release v2.0, all @deprecated tags that were introduced in 2.0 beta versions should now point to v2.0. This should be clearer for developers who upgrade from v1 to v2.
> Update all deprecated tags to reference version 2.0.0

- .github/workflows/main.yml
After `master` was renamed to `archive/v1`, the status checks that are triggered on the branch need to be updated to trigger on the new branch name.
> Update GitHub actions for archive/v1

- src/public/index.ts
- src/public/publicAPIs.ts
- test/public/publicAPIs.spec.ts
This change reverts an accidental rename of an existing API.
> Reverting to original name - registerChangeSettingsHandler

- change/@microsoft-teams-js-6cfdd495-e295-4ae6-b1a2-1721a2f1eae8.json
- packages/teams-js/src/public/interfaces.ts
Since the global `Context` interface is deprecated, this change provides a link to more information about the differences between the deprecated `Context` and `app.Context` interfaces.
> Added a link to info about the updated Context

- yarn.lock
Running `yarn install` on a clean checkout of `main` produces this change in yarn.lock. The `azure-devops-node-api` is used by the `bundle-size-tools` package - looks like something caused it to get removed from yarn.lock at some point, however.
> Add azure-devops-node-api to yarn.lock

- change/@microsoft-teams-js-fad26258-8531-4882-98d5-8df4e225fba8.json
- packages/teams-js/src/private/appEntity.ts
- packages/teams-js/src/private/files.ts
- packages/teams-js/src/private/legacy.ts
- packages/teams-js/src/private/privateAPIs.ts
- packages/teams-js/src/private/teams.ts
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/src/public/stageView.ts
- packages/teams-js/src/public/teamsAPIs.ts
- packages/teams-js/src/public/video.ts
There were several places in the SDK where we still refer to "Teams", but since the SDK supports multiple hosts, these should be changed to "host". 
While I was editing these files, I made the additional updates:
- Cleaned up instances of app -> application
- Added doc comments for several isSupported functions
- Made other minor doc updates in edited files for consistency and completeness
> Updated reference doc comments to rationalize "Teams" vs "host" occurrences

- README.md
- change/@microsoft-teams-js-927f99f5-92fd-4a8b-979f-11b6a9e7a6e2.json
- packages/teams-js/README.md
- packages/teams-js/package.json
The [npm docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository) suggest that you can specify a github repo with a link to the specific directory when your repo is a monorepo using the `directory` field.
Also made two small tweaks to the README files to remove redundant references to the "main branch" and added a reference to the Contributing section from the Getting Started section to hopefully help distinguish between when you should clone and fork the repo.
> Add directory to repository info in package.json

- apps/teams-test-app/src/components/StageViewAPIs.tsx
- change/@microsoft-teams-js-a1117fe3-9c1f-4d89-8020-c75903495d39.json
- packages/teams-js/src/public/stageView.ts
- packages/teams-js/test/public/stageView.spec.ts
`stageView.open` is a relatively new API that is still under development. On the path to v2, we have converted APIs that take callbacks to instead return Promises. As such, the `open` function that takes a callback has already been deprecated, despite being under development still.
Would be a clearer message to developers if we just had the `open` function that returns a `Promise`.
> Remove callback version of stageView.open

- azure-pipelines.yml
- change/@microsoft-teams-js-164b1aca-b91a-42e1-82dc-1b04b06640fb.json
- change/@microsoft-teams-js-b8534d5d-068f-4ccc-8f59-482a8f11e76c.json
- packages/teams-js/CHANGELOG.md
Consolidate change log entries across all the beta releases into major, minor, patch notes.
Do we think this is clearer for developers than keeping change log entries separated by beta releases?
> Consolidate change log entries across all the beta releases

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- azure-pipelines.yml
- change/@microsoft-teams-js-b8534d5d-068f-4ccc-8f59-482a8f11e76c.json
- change/d.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
Release 2.0.0 was done in PR #1184 
Merging through an intermediate branch because we don't want to merge the azure-pipelines.yml change in the release branch into main.
---
Releasing 2.0.0
Consolidate change log entries across all the beta releases (https://github.com/OfficeDev/microsoft-teams-library-js/pull/1180)
Consolidate change log entries across all the beta releases into major, minor, patch notes and keep per-beta comments for reference
Change files
> Merge release/2.0.0 into main

- apps/teams-test-app/src/components/MeetingAPIs.tsx
Adding a test for the `registerSpeakingStateChangedHandler` API to the MeetingAPIs.tsx component in test app.
> Update test app with meeting API

- yarn.lock
I noticed that the [PR from dependabot](https://github.com/OfficeDev/microsoft-teams-library-js/pull/1198) for updating the eventsource dependency including a lot of deleted lines from the yarn.lock file. This seemed strange to me and searching for what command dependabot uses yielded nothing useful to find out exactly how to repro the update process.
I found an issue that suggested that yarn doesn't have a great way of updating subdependencies (dependencies of dependencies that are in your package.json file) and tried the [step suggested by someone in the issue](https://github.com/yarnpkg/yarn/issues/4986#issuecomment-395036563).
This produced a yarn.lock file that makes much more sense to me for updating eventsource.
> Manually bump eventsource from 1.1.0 to 1.1.1

- packages/teams-js/test/public/appInstallDialog.spec.ts
Currently `toMatch` does not test against regressions for the unnecessary `/`. Changing this to `toEqual` will ensure that regressions are found during the unit testing phase.
> Changing toMatch to toEqual in appInstallDialog legacy test

- apps/teams-test-app/src/components/privateApis/FilesAPIs.tsx
- apps/teams-test-app/src/components/utils/ApiWithCheckboxInput.tsx
- Fix the validation of getExternalProviders API
- Extend the ApiWithCheckBoxInput to ingest setResult callback which allows callback based APIs to set the result of the text box.
> Test app: Fix the validation of getExternalProviders API

- .npmrc_publish
We can't dereference the old value with Lockbox requests without manually setting an environment variable with the value. Testing if dereferencing the generated secret variable instead.
> Modified npmrc file to read the more secure secret for NPM-TOKEN

- packages/teams-js/devdocs/logging.md
The logging docs were super helpful in diagnosing some recent test failures. I was stuck momentarily enabling the logging until I kept reading and saw that after disabling the logging you had to refresh the app. Sure enough you need to refresh the app after enabling too. Adding that step in case it's helpful for someone else.
> Added refresh step to logging documentation

- change/@microsoft-teams-js-cd1a5a1d-7289-4987-bd29-944865d42a6a.json
- packages/teams-js/src/public/index.ts
- packages/teams-js/src/public/media.ts
- packages/teams-js/typedoc.json
I finally figured out how to resolve errors that were previously worked around in the typedoc.json file. We need to explicitly export interfaces (and types, etc.) defined in the global namespace in order to have the referring documentation show up correctly.
Note my change in the media.ts file in order to make sure that `MediaControllerEvent` appears in the docs, since it's already referenced by other public documentation. The alternative would be to hide the documentation that refers to it.
> Remove intentionallyNotExported exceptions from documentation validation

- change/@microsoft-teams-js-2219bf05-bb8d-41a0-96d6-5ce594cb08ca.json
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/tasks.ts
We discovered after the 2.1.0 release that the documentation system doesn't like the links we used in the deprecated comments for the global `Context` interface properties. Updating the links so that they work with the typedoc system.
> Update global Context documentation comments

- apps/teams-test-app/src/components/AuthenticationAPIs.tsx
- apps/teams-test-app/src/public/auth_end.html
- apps/teams-test-app/src/public/auth_start.html
- apps/teams-test-app/webpack.config.js
- package.json
- yarn.lock
> Added the test flow for 3rd party auth via auth_start.html and auth_end.html static html files.
> Added `mockOAuth` in auth params to recognise the test flow and redirect to auth_end.html directly with appropriate expected params.
> Modified the type of `Authentication.Authenticate` API in test app to take `mockOAuth` into account and change the url accordingly
> Adding test flow for External Authentication

- tools/yaml-templates/android-test.yml
Android E2E test task will timeout if it runs more than twice. When the task times out the tests results are not published and we cannot see which tests failed. Reducing retry number to 1 to avoid timeout.
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
<Yes/No>
> List the next …
> Change the number of retries on the Android E2E pipeline

- apps/sample-app/src/components/PeopleAvatars.tsx
- change/@microsoft-teams-js-0f43576d-6006-404f-a65b-a8328c022626.json
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/src/public/settings.ts
- packages/teams-js/src/public/teamsAPIs.ts
- packages/teams-js/test/public/publicAPIs.spec.ts
- packages/teams-js/test/public/settings.spec.ts
Previously, the v1 versions of the `register*Handler` functions would throw if the v2 version of the API's capability was not supported, breaking backwards compatibility.
E.g.,:
If `pages.config` was not supported, calling `registerChangeSettingsHandler` would throw `ErrorCode.NOT_SUPPORTED_ON_PLATFORM`. 
This changes ensures that the v1 versions do not throw if the v2 capability is not supported, while keeping the v2 version's `isSupported` check present.
Fixes #1331 
1. Added a register*HandlerHelper function in the v2 version of the API's capability. This helper takes an additional optional closure parameter that represents the …
> Register handler fix

- change/@microsoft-teams-js-ced9c7db-ddda-4b9e-806f-1bf25773315f.json
- packages/teams-js/src/public/app.ts
The documentation for the `theme` property on the `AppInfo` object was too terse and did not provide possible values.
Update TSDocs for `theme` property to enumerate possible values.
Ran unit tests; E2E tests will be run as part of publishing this PR.
No additional unit tests are necessary since there are no tests that validate our documentation is "complete."
No.
Yes
None, although documentation could always be improved.
Before:
After:
> Theme docs

- change/@microsoft-teams-js-68e20fff-dd6d-40c6-9246-1e859e1f6c84.json
- packages/teams-js/src/public/tasks.ts
> Since the functions `getBotUrlDialogInfoFromTaskInfo` and `getUrlDialogInfoFromTaskInfo` functions are not used by developers and don't need to be exported. 
> No unit test has been added because there are no API changes.
> NO e2e test has been added because there are no API changes.
Yes
> Deleting unnecessary export keywords from tasks.ts helper functions

- change/@microsoft-teams-js-ea1fbc8a-654d-4410-8191-321b66d8f2d8.json
- packages/teams-js/src/internal/handlers.ts
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/publicAPIs.ts
Based on the PR feedback from #1335, this change removes several register\*HandlerHelper functions in favor of using a common `registerHandlerHelper` function. I chose to keep several of the specific register\*HandlerHelper functions (`pages.config.registerOnSaveHandlerHelper`, `pages.config.registerOnRemoveHandlerHelper`, `pages.backStack.registerBackButtonHandlerHelper`, `teamsCore.registerOnLoadHandlerHelper`, and `teamsCore.registerBeforeUnloadHandlerHelper` due to the unique code patterns they each have). I think this approach is cleaner overall.
1. Added `registerHandlerHelper` function to src/internal/handlers.ts. Included …
> Refactor register*Handler APIs calls to use a common helper function where possible

- change/@microsoft-teams-js-8b731aef-816c-49f6-9435-5b79bc5b99ca.json
- packages/teams-js/src/public/constants.ts
Add a new value (`OutlookWin32`) to `HostName` enum.
1. Add a new value (`OutlookWin32`) to `HostName` enum.
N/A
No
No
Yes
> Add OutlookWin32 to HostName enum

- change/@microsoft-teams-js-2cfa7e83-7b34-4723-8d88-4e9a4e2f9b77.json
- package.json
- packages/teams-js/.eslintrc.js
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/constants.ts
- packages/teams-js/src/internal/mediaUtil.ts
- packages/teams-js/src/private/teams.ts
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/src/public/geoLocation.ts
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/menus.ts
- packages/teams-js/src/public/monetization.ts
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/people.ts
- packages/teams-js/src/public/sharing.ts
- packages/teams-js/src/public/tasks.ts
- packages/teams-js/tsconfig.strictNullChecks.json
- tsconfig.strictNullChecks.json
- yarn.lock
Enabling the `strictNullChecks` TS compiler flag is a good thing; it results in better overall code and avoids bugs. You will find many resources on the internet extolling its virtues.
Enabling it in this project is not straightforward as there are many violations and some are complex to fix.
Unfortunately, the TS compiler does not allow a way to enable a compiler flag like `strictNullChecks` and then selectively suppress it (and only it) in your files/code lines. However, eslint does have such an ability -- and there's an npm package to enable `strictNullChecks` violations as an eslint rule (rather than a compiler flag). This allows us to turn on and get the benefit of `strictNullChecks` without having to fix them all at once (and it doesn't require us to disable all ts errors in our …
> Enable strictNullChecks as an eslint rule (not a compiler setting) and disable violations

- apps/teams-test-app/src/App.tsx
- apps/teams-test-app/src/components/Version.tsx
- change/@microsoft-teams-js-f23c5eb2-1636-4234-b6ed-e18dbca67463.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/constants.ts
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/index.ts
- packages/teams-js/src/public/version.ts
- packages/teams-js/test/public/app.spec.ts
- packages/teams-js/test/public/appInitialization.spec.ts
- packages/teams-js/test/public/pages.spec.ts
- packages/teams-js/test/public/publicAPIs.spec.ts
Make the version of TeamsJS a public constant, rather than an internal one. Then, display it on the main page in the test app so it can be validated by an E2E test.
In a subsequent change, I want to write the E2E test that checks this version to ensure it was "properly" set. The version is set by a plugin in webpack at compile time. Today it would be very easy for someone to write the bug that stopped replacing that version and it's not clear how we would ever discover that without a bug report from a user. Maybe some test would fail, but it would be best if we had a specific test for this so that we could see directly see the failure.
1. Move the version constant from the internal section to the public section.
2. Write a component in the test app that displays the version. This needs to …
> Make version number public in TeamsJS and display it in the test app

- azure-pipelines.yml
> With recent changes to how E2E tests are run, there is no need for an explicit back-compat targeted run.
1. Remove a Job that uses `latestBackcompat` sdk checkpoint.
N/A
No
No
No - "No change files are needed" from `yarn changelog`
> Remove Latest BC run from build

- change/@microsoft-teams-js-7a2e000c-6c51-4469-9ba1-e3dc2a4ce51c.json
- packages/teams-js/src/public/menus.ts
- packages/teams-js/src/public/monetization.ts
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/sharing.ts
Some of the locations in our code that were failing the `strictNullChecks` check were easy to fix by just adding `| undefined` to the type declaration, since the code already handled the case where those variables were `undefined.` This change fixes those places.
Build, run unit tests, run e2e tests
No because functionality is being added/changed. This is a type-decoration-only change.
No, see above.
Yep
#1352 
Fix more `strictNullChecks` warnings. Most will not be as easy as this.
> Fix some places where undefined was tolerated but not explicitly part of the type declaration

- change/@microsoft-teams-js-98d7ca14-14e6-4abe-b79a-c08d1da0dc2c.json
- packages/teams-js/src/private/files.ts
- packages/teams-js/test/private/files.spec.ts
This PR has following changes and corresponding test code update
1. Changed datatype of field **lastModified** from Date to number : This is required because of type incompatibility between the calling app API and SDK API, and  because of which the integration fails.
2. Added a new field named **size** representing the file size in bytes, being congruent with the calling app API. 
Below PRs contain the original 3P API changes.
https://github.com/OfficeDev/microsoft-teams-library-js/pull/1152
https://github.com/OfficeDev/microsoft-teams-library-js/pull/1251
File uploads to 3P providers should work as expected after this change.
Unit Tests added:
No, Modified the unit tests as applicable.
Change file added:
Yes
> 3p cloud storage provider Upload API bug fix

- azure-pipelines.yml
- tools/yaml-templates/android-test.yml
- tools/yaml-templates/build-app-host.yml
- tools/yaml-templates/build-test-publish.yml
Remove v1-targeted E2E test from TeamsJs CI run.
N/A
No
No
No
> Don't run v1 tests as part of TeamsJs CI

- apps/teams-test-app/src/components/PagesAPIs.tsx
In a previous pr (#1248) I updated some outdated references to the `core` namespace. Because one of these references was in the test app, I had to maintain the control with the old name and simultaneously create a new one while the E2E tests were updated to look for the new name. I have now updated the E2E tests to look for the new name, so I'm removing the control with the old name.
E2E tests will run as part of this PR.
No because the only code changing here is the test app which is only consumed by E2E tests
Yes, in a separate change.
No since this change does not affect the published package.
#1248 
None. This completes the rename.
> Remove old shareDeepLink control from test app

- change/@microsoft-teams-js-5b701dc1-c6e8-4d61-acde-7b786b791a59.json
- packages/teams-js/src/public/app.ts
The documentation for the `sharepoint` property on the `Context` object did not provide enough detail for someone to actually use it (e.g., what data would be in it and what would be the shape of that data?)
This change elaborates and provides a link to the docs when a developer can see the data available in the property.
Generated typedocs locally and observed that they looked correct and that the link worked.
No, there is no functionality change with this fix.
No, there is no functionality change with this fix.
Yes
| <img width="662" alt="image" src="https://user-images.githubusercontent.com/36546967/192070803-cb0ae591-03a1-4be6-9530-a13ce5e4aa04.png"> | <img width="605" alt="image" …
> Clarify documentation for sharepoint property on Context object

- README.md
- apps/sample-app/src/App.tsx
- change/@microsoft-teams-js-428c45d4-9a6f-46ff-8c5a-33db61803db2.json
- packages/teams-js/README.md
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/profile.ts
> The docs.microsoft.com URL was changed to learn.microsoft.com. This PR updates any direct links in markdown or comments that used docs.microsoft.com. Also, ensured that the updated links did not use a hardcoded language path (en-us, etc) and that use of msteams-client-js-beta in the URL was now msteams-client-js-latest. 
1. Updated all links that used the docs.microsoft.com URL to now use learn.microsoft.com
1. Clicked links to ensure navigation was equivalent to prior docs.microsoft.com link …
> Link updates

- README.md
Made a few small changes to our root README file
1. Removed the "Coverage Status" badge. It was pointing to a service that hasn't been used in years.
2. Updating the language in "Getting Started" to say that developers should *fork* the repo instead of *clone* the repo
3. Fixed the "Contributing" link so it actually takes developers to Contributing.md
1. Verified the "Coverage Status" service hadn't had any updates since July 2018
2. Made sure the new Contributing link worked
None needed, documentation only
No
No changefile needed for changes outside of `packages/teams-js`
> Updating the README file with some slight changes

- change/@microsoft-teams-js-57a0030b-c4bf-427f-9a3f-cf218d6c4bc3.json
- packages/teams-js/src/public/app.ts
In issue #1365, it was shown that the `message` property is unused. The documentation (here and elsewhere) does not explicitly state that the message is show in the UI, but it's natural for someone to expect that.
In this change the documentation for the `message` is updated to indicate that it's unused. Separately we have the issue tracking the work to either make it show up in the UI or decide that we don't want to enable that and then remove the `message` property altogether.
- Ensure build and tests succeeded
- Generate documentation, verify it looks as expected.
No. There are no unit tests that validate documentation content.
No. There are no E2E tests that validate documentation content.
Yes
| <img width="658" alt="image" …
> Update documentation for message property on app.IFailedRequest to indicate that it is unused

- change/@microsoft-teams-js-8b6459b8-aa6f-4f83-a71c-47b3d6022114.json
- packages/teams-js/src/public/dialog.ts
There was no explicit documentation on what value `ISdkResponse.result` has if the user closes the dialog instead of submitting (e.g. using the X in the corner). This change adds documentation to indicate that it is `undefined` in that case.
Create docs locally, ensured they looked correct.
No unit tests for documentation content.
No E2E tests for documentation content.
Yes
| <img width="667" alt="image" src="https://user-images.githubusercontent.com/36546967/195481796-3806ea45-a0f3-4b9c-85d3-521829d74c2d.png"> | <img width="608" alt="image" src="https://user-images.githubusercontent.com/36546967/195482455-a346f625-4cb0-4737-8fd0-06a8aba1e8ea.png"> |
> Update documentation for what result is returned when user closes dialog

- README.md
One of the links in the README file did not actually go to the CONTRIBUTING.md file. I fixed it so that it works now.
1. Update the first link to CONTRIBUTING.md in the top-level README file to actually take users to that file.
1. Clicked the link in the README file and made sure it works
2. Manually verified that the link is now the same as another link to the same file that already works correctly.
None necessary, README update only
No
No, README update only
None
> Fixing broken link to CONTRIBUTING.md

- change/@microsoft-teams-js-8835237b-4a82-4082-b65a-5db37e32c03e.json
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/src/public/chat.ts
- packages/teams-js/src/public/dialog.ts
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/profile.ts
Our use of the @beta tag in this repo was not consistent for a couple of reasons. We initially thought that the @beta tag would cascade down and apply to things contained within something marked with @beta, but it does not.
After this change, I believe we now correctly have applied the beta tag everywhere. This means:
- If a namespace has a @beta tag on it, all children also have the @beta tag
- We no longer mark certain namespaces with @beta because we feel that making breaking changes there would now require bumping the major version of the package
- @beta tags indicate to readers of documentation that the item in question could change shape or disappear at any time and we will not bump the major version if something like that happens. When we feel that new things are sufficiently …
> Making our use of the @beta tag consistent

- change/@microsoft-teams-js-51980b95-c86a-4b3c-a2d0-1b9e475014b3.json
- packages/teams-js/src/internal/handlers.ts
- packages/teams-js/src/internal/internalAPIs.ts
- packages/teams-js/src/private/logs.ts
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/src/public/liveShareHost.ts
- packages/teams-js/src/public/pages.ts
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/src/public/teamsAPIs.ts
- packages/teams-js/test/private/files.spec.ts
- packages/teams-js/test/public/app.spec.ts
- packages/teams-js/test/public/appInstallDialog.spec.ts
- packages/teams-js/test/public/authentication.spec.ts
- packages/teams-js/test/public/call.spec.ts
- packages/teams-js/test/public/location.spec.ts
- packages/teams-js/test/public/meeting.spec.ts
- packages/teams-js/test/public/navigation.spec.ts
- packages/teams-js/test/public/pages.spec.ts
- packages/teams-js/test/public/publicAPIs.spec.ts
- packages/teams-js/test/public/tasks.spec.ts
Make sure `initialize` call finishes and runtime information is correctly set up before other APIs can be used. There are exception for APIs I think people are most likely calling right after calling `initialize`, potentially before it finishes. I also had to allow `register*Handler` calls with `null`/`undefined` handler to go through, to keep UTs working (we clean registrations between many tests, some of which didn't run `initialize` at all (by design).
1. Update `ensureInitialized` to check that `initialize` finished, not just got called.
2. Add `ensureInitializeCalled` to be used by APIs that we want to allow to be used before `initialize` finishes.
3. Update said APIs to use `ensureInitializeCalled` instead of `ensureInitialized`
4. Fix UTs
1. UTs updated
Yes, added tests to validate …
> Make sure initialize completes before most API calls are allowed

- CONTRIBUTING.md
- README.md
- packages/teams-js/README.md
Update terminology in repo and NPM readme landing pages to refer to TeamsJS as a _library_ rather than SDK. This lays the groundwork to integrate the story of Office Add-ins/Extensions ([OfficeJS library](https://github.com/OfficeDev/office-js)) with multi-hub Teams apps [in the future](https://devblogs.microsoft.com/microsoft365dev/ignite-2022-highlights-for-microsoft-teams-app-builders/#whats-next)   and help head off potential confusion.
1. Change title/text instances of "SDK" to "library" in repo README
2. Change title/text instances of "SDK" to "library" in README for NPM package
3. Change text instances of "SDK" to "library" in CONTRIBUTING
NA
No
No
None
No
https://github.com/MicrosoftDocs/msteams-docs/pull/7306
https://github.com/OfficeDev/msteams-client-docs-ref-typescript/pull/106 …
> Update terminology (SDK->library) in readme

- packages/teams-js/test/public/pages.spec.ts
- packages/teams-js/test/resultValidation.ts
As part of fixing the lint errors in the `pages` unit tests, I moved many repeated blocks of code which validated `MessageRequest` objects into a single, shared, helper. These tests now consistently validate their `MessageRequest` objects and have many of their lint errors fixed/removed.
Some of the validation places in pages still remain because they use a different type, also called `MessageRequest`. This type is only used by the "frameless" tests. Rather than also write another validator for these, it seemed like a future change would be to understand if these two types could be shared/reused since they are identically named (but not actually defined identically). I left those tests alone for the purposes of this change.
1. Create request validation helper methods
2. Make the pages …
> Create a common request message validator and use it in the pages test

- packages/teams-js/test/private/privateAPIs.spec.ts
- packages/teams-js/test/public/pages.spec.ts
- packages/teams-js/test/utils.ts
There were two `MessageResponse` types in the library. One was used by the product code and one was used by the unit test code. This change updates the unit test code to use the one defined in the product code. The product code version had an extra (optional) property, which won't harm anything in the unit tests since it will just be unused. FOR NOW.
Delete `MessageResponse` type in unit test code and update all references to product code version.
Ensured unit tests passed
No.
No.
beachball told me it was not required for this change
> Unify MessageResponse objects

- apps/teams-test-app/src/App.tsx
- apps/teams-test-app/src/components/ProfileAPIs.tsx
Adding support for profile.showProfile calls to the test app.
1. Add support for profile APIs to test app
1. Tested manually in locally running test app and inside test hub
None, there is no test coverage for test page UI
This change is to support end to end tests in hubs
No
> Added showProfile to test app

- tools/yaml-templates/android-test.yml
Post Android E2E test results on cancellation so that we can see test results after timeout. Remove retry from Android E2E tests since the second run may not have enough time to finish before timing out
1. Remove retry from Android E2E tests
2. Add on cancelled condition to test results publishing
1. Run Android E2E tests, tests should complete and post results on success or failure.
No unit tests necessary: YAML change
No
No
Going to try implementing per-test retries on the Android side for more efficient flakey test mitigation
> Post Android E2E Test Results on Cancellation and Remove Retry

- packages/teams-js/test/framelessPostMocks.ts
- packages/teams-js/test/utils.ts
I was trying to understand how the framelessPostMock stuff in the unit tests work and one thing I kept tripping over was the whole `that = this` thing it was doing (with no explanation). After some more poking around I decided it was being done because the original author wanted to properly capture a `this` pointer to use in the callback methods. In this change, I have updated the callback methods to use arrow functions notation instead, which automatically captures the `this` pointer correctly and doesn't require any this/that stuff.
It's possible that really the whole thing needs to be reworked but, if that's true, at least it's something I can do iteratively by making the code less and less confusing until I understand better what it's doing and why.
I also fixed the other lint errors …
> Fix all lint errors in framelessPostMocks, remove unnecessary that=this

- change/@microsoft-teams-js-848281b2-f558-438a-a404-c6b53ae7d496.json
- packages/teams-js/src/public/runtime.ts
IsSupported was set to true incorrectly when platform support in Teams was not correctly in place. This PR reverts it back to false until platform support is confirmed.
fixes #1450 
1. Set IsSupported to false in Teams web and desktop clients.
1. Checked that IsSupported returns false in Teams
No
No
Yes
> Fix incorrect profile.IsSupported check

- change/@microsoft-teams-js-45469888-55eb-44b9-b72b-cb92a212e84b.json
- packages/teams-js/src/private/videoEx.ts
- packages/teams-js/test/private/videoEx.spec.ts
Add a `notifyFatalError` function in videoEx to enable video apps to notify the host of fatal errors.
1. Add `notifyFatalError` function in videoEx
1. <Step 1>
2. <Step 2>
Yes
No
Yes
> Export notifyError function

- apps/teams-test-app/src/components/utils/ApiWithTextInput.tsx
- azure-pipelines.yml
Spectron tests relies on chrome driver/node js started failing as it was unable to open chrome browser. Recent migration to of tag ubuntu-latest to 22.04 is buggy as can be seen reported at below link. Reverting to old to unblock work and until the latest one gets stable by ADO team.
https://github.com/actions/runner-images/issues/6399 
1. Keep the native tests in only one job of E2E test to remove redundancy.
2. Explicitly Pooled to ubuntu-20.04 because of the reason mentioned above. 
> E2E Tests with electron tests should work fine
1. <Step 1>
2. <Step 2>
NA
No, NA
Yes …
> Use ubuntu-20.04 explicitly for native electron tests

- change/@microsoft-teams-js-9e642ffe-0bf6-4775-a92f-99a31e897e32.json
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/test/public/authentication.spec.ts
1. Added `dataResidency` interface in teams-js SDK within `getUser` API. Exposed a limited set of data residencies information to 1P app developers.
1. <Step 1>
2. <Step 2>
Yes.
No.
Yes.
> Add dataResidency interface in the SDK within getUser API

- change/@microsoft-teams-js-7c96f1b9-e26e-4ac8-85be-f7b602a68543.json
- packages/teams-js/src/public/app.ts
Fixed missing slash in URL in comment on `app.initialize`
The documentation for this parameter could certainly be improved but at least I can fix the typo easily.
Automated tests passed.
No because there's no unit tests that validate the content of documentation.
No because there's no e2e tests that validate the content of documentation.
Yes sir or m'am.
|![image](https://user-images.githubusercontent.com/36546967/206797702-effbde9d-78cd-4e68-9bba-4e0240377abd.png)|<img width="575" alt="image" src="https://user-images.githubusercontent.com/36546967/206797737-5c0af0da-0ff3-478b-829e-bcaeefc81dc9.png">|
> Added missing slash in URL in comment on `app.initialize`

- packages/teams-js/webpack.config.js
1. Changed globalObject to 'this' in the webpack config. This is to allow for use of teams-js with nextjs. Without the change, nextjs conflicts with nodejs as they both use the 'self' reference
1. <Step 1>
2. <Step …
> changed webpack globalObject to 'this'

- change/@microsoft-teams-js-57c14eb2-51df-4f2a-b20a-c99a73f235d4.json
- packages/teams-js/src/private/interfaces.ts
Remove entityId and title as required fields from openFilePreview parameters. This is currently enforced at the hubSDK level but will be removed following this change.
Automated tests passed.
No
No
Yes
> Remove entityId and title as required fields from openFilePreview parameters

- packages/teams-js/test/public/pages.spec.ts
- packages/teams-js/webpack.config.js
>Reverted globalObject: "this" webpack change due to reports of it breaking C#/Blazor Teams Tab apps
1. Webpack globalObject: this revert
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
<Yes/No>
> noahdarveau/reverted webpack globalObject: this

- apps/teams-test-app/src/components/utils/ApiWithCheckboxInput.tsx
- apps/teams-test-app/src/components/utils/ApiWithTextInput.tsx
> Adding placeholder to make sure iOS gets the resource ID. Whenever we add a UI component to test app the iOS pipeline fails because iOS web view doesn't allow us to get UI components by resource ID, we have to come up with a workaround which is to add place holder to the input fields in the test app by which on the iOS side we can access those by placeholder value. 
> Make iOS pipeline test different version
Adding a placeholder to test app
N/A
N/A
> Adding placeholder to test app

- apps/teams-test-app/src/public/auth_end.html
- apps/teams-test-app/src/public/auth_start.html
Changes to the test app to utilize the revised OAuth flow. auth_start.html will try to retrieve the redirect URL from the query parameters and redirect to this instead of the msorange URL currently used if it is present. These changes enable E2E testing for this flow.
1. Update OAuth test flow to try to use the hostRedirectUrl query parameter, keeping original url as a fallback to test the original flow.
1. Tested against new redirect flow
No unit tests added as this only affects the test app.
No
No
> add redirectUrl to oauth test flow

- change/@microsoft-teams-js-9a93c2f8-94c4-415d-adb3-5fb8d8b16692.json
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/test/private/files.spec.ts
- packages/teams-js/test/public/navigation.spec.ts
- packages/teams-js/test/public/publicAPIs.spec.ts
- packages/teams-js/test/public/settings.spec.ts
Removed deprecated _initialize and _uninitialize methods only used by unit tests, then updated the unit tests to use the non-deprecated versions.
No, but I ensured these unit tests passed.
Yes.
> Removed deprecated _initialize and _uninitialize methods only used by unit tests

- change/@microsoft-teams-js-ccce9925-3c49-48bc-96bd-3aa8a0247dd6.json
- packages/teams-js/src/public/meeting.ts
Updating the RaiseHand and MeetingRection Meeting APIs with the @hidden and @internal tag in order to hide the documentation and let app developers know that it may not work in 3p apps yet.
1. Add @hidden and @internal tags to the 
1. None
No, just adding tags
No
No, no file was generated when running the changefile command.
> add internal and hidden tags to RH and Reaction APIs

- change/@microsoft-teams-js-2210d153-a06d-4432-9da4-5a47febbc045.json
- packages/teams-js/src/public/publicAPIs.ts
- packages/teams-js/test/public/publicAPIs.spec.ts
Facts:
1. We have V1 and V2 version of getContext() call. 
V1 is in /packages/teams-js/src/public/publicAPIs.ts, V2 is in /packages/teams-js/src/public/app.ts
2. V2 getContext() call should return app.Context() object
V1 getContext() call should return LegacyContext object (=packages/teams-js/src/public/interfaces.ts#L257)
3. Host sdk returns LegacyContext
4. For V2 getContext() call, since host sdk returns LegacyContext, it needs a map between legacyContext to app.Context. 
This logic is currently correct in our code base
Issues:
The current bug happens in V1 getContext() call. Since V1 getContext() expects LegacyContext object and host sdk returns LegacyContext, it should be just straightly call into host sdk. Currently what it does: V1 getContext() -> call V2 app.getContext() -> which …
> Fix a getContext() bug where it does incorrect conversion and causing properties loss

- change/@microsoft-teams-js-427db183-7770-469e-bb2e-b9b7803b56ce.json
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/tasks.ts
The reference documentation for the [url property](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/urldialoginfo?view=msteams-client-js-latest#@microsoft-teams-js-urldialoginfo-url) used when opening a dialog mentioned the `validDomains` property in the manifest but did not link to the documentation for it. As a convenience, I've added that link.
As part of generating documentation for this change, I coincidentally found that the documentation generator was showing this error:
```
Warning:
[MarkedLinksPlugin]: Found invalid symbol reference(s) in JSDocs, they will not render as links in the generated documentation.
In tasks: {@link dialog.submit}
```
To address this, I also updated the documentation link for the `tasks.submitTask` method to refer to the correct …
> Update some dialog related documentation links

- change/@microsoft-teams-js-c1a77265-c9b2-400a-93e8-54e461fcc1fb.json
- packages/teams-js/typedoc.json
While making a code change for a recent PR (#1551) I discovered that there was a documentation error in the code (that I didn't cause with my change). To prevent this from happening again, this change updates the documentation generation code to treat warnings as errors and fail the step.
*Before*
```
yarn run v1.22.15
$ yarn workspace @microsoft/teams-js docs
$ yarn typedoc
$ D:\repos\tjsfork\node_modules\.bin\typedoc
Warning:
[MarkedLinksPlugin]: Found invalid symbol reference(s) in JSDocs, they will not render as links in the generated documentation.
In tasks: {@link dialog.submit}
Info: Documentation generated at ./docs
Done in 11.87s.
```
*After*
```
yarn run v1.22.15
$ yarn workspace @microsoft/teams-js docs
$ yarn typedoc
$ D:\repos\tjsfork\node_modules\.bin\typedoc
Warning: …
```
> Treat Typedoc warnings as errors

- tsconfig.common.json
The version of typescript used by this repo is very old (> 2 years). I tried updating typescript to the latest version, just to see what would happen. One of the problems I ran into is that it started finding errors in the node_modules type files from another library.
From some searches online, it seems like the best way to workaround this is to enable the `skipLibCheck` option. From [the TS docs](https://www.typescriptlang.org/tsconfig#skipLibCheck):
> Skip type checking of declaration files.
> 
> This can save time during compilation at the expense of type-system accuracy. For example, two libraries could define two copies of the same type in an inconsistent way. Rather than doing a full check of all d.ts files, TypeScript will type check the code you specifically refer to in your app’s …
> Enable typescript's skipLibCheck option to make it possible to upgrade typescript in the future

- change/@microsoft-teams-js-7bd9ac03-29ae-40f5-93ce-f96b2aa8cccc.json
- packages/teams-js/package.json
As part of the build, typedoc was being run with the `--emit:none` parameter. This is supposed to run documentation validation but just not output any documentation. Despite this being the documented typedoc behavior, having `--emit:none` as a parameter was causing typedoc errors to be suppressed. Once `--emit:none` was removed, the errors show up again (and correctly fail the build).
For now, to ensure that errors do fail the build, I'm just removing the `--emit:none` parameter. Someone suggested earlier that this is just a bug in the old version of typedoc we are using and if I just upgraded then the behavior of `--emit:none` would be correct. I tried upgrading typedoc but it requires a newer version of typescript, and upgrading typescript is non-trivial. As such, I'm just removing …
> Enable typedoc warnings and errors to fail the build

- change/@microsoft-teams-js-042f478a-ce62-4e29-8ae5-d7918506bb95.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/test/internal/communication.spec.ts
Finished writing unit tests for all exported functions in communication.ts
1. Stopped exporting processMessage and shouldProcessMessage from communication: they were only being called by the test files
2. Added unit tests for `sendMessageToParent`, `sendAndUnwrap`, `sendAndHandleStatusAndReason`, `sendAndHandleStatusAndReasonWithDefaultError`, `sendAndHandleSdkError`, `waitForMessageQueue`, and `sendMessageEventToChild`.
1. Ran all unit tests.
Yes
No
Yes
> Adding more communication unit tests

- package.json
- yarn.lock
The version of Typescript used by this repo is very old. I tried updating it to the latest version but it causes some build errors that are non-trivial to investigate. For now, I'm upgrading it as far as I can, to 4.6.4. Going to the next version (4.7.2) is where the errors start appearing.
Fortunately 4.6.2 is far enough along where I can update typedoc to the latest version in a subsequent PR and see if it fixes the `--emit:none` problem described in #1555 
Ensure builds succeed and tests pass.
> Update Typescript to 4.6.4

- .github/workflows/main.yml
@shrshindeMSFT is in the process of retiring node 12 from this repo. The typedoc updates I'm trying to make in #1558 don't work with node 12. As such, I'm removing the node 12 build step and requirement from the repo to unblock #1558.
Remove node 12 from the matrix of node versions that builds are run against.
Ensure builds succeed and tests pass.
> Remove node 12 from the matrix we use for pipeline builds

- change/@microsoft-teams-js-fb7d03a6-a374-4fc3-a9cd-6f72c9b0952a.json
- package.json
- packages/teams-js/package.json
- packages/teams-js/src/public/adaptiveCards.ts
- packages/teams-js/src/public/dialog.ts
- packages/teams-js/src/public/pages.ts
- yarn.lock
This change updates the repo to the latest version of the typedoc package and fixes documentation issues it flagged that the previous versions did not.
I was also able to put back the `--emit none` parameter on the `docs:validate` step in `package.json`. Recall that in a previous PR (#1555) I removed this parameter because it was causing all errors and warnings to be silenced for some reason. It seems like it was a bug because with this newer version of typedoc I can replace that parameter and still see the errors/warnings (I verified it).
Ensured builds pass, ensured tests pass, ensured documentation successfully validates.
> Update typedoc package to latest version and fix documentation issues raised by it

- change/@microsoft-teams-js-5ffb59b5-7122-4ab8-912f-7fdd2e7d62c7.json
- packages/teams-js/src/public/app.ts
The `licenseType` property on the `UserInfo` interface said it was a string but did not provide possible values. I have added those possible values in this change.
Ensured builds and tests pass.
No because there are no unit tests which validate correctness of documentation content.
> Add possible values to documentation for licenseType property on UserInfo interface

- change/@microsoft-teams-js-99eca3fb-24d8-4c34-95d3-d83b96469721.json
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/sharing.ts
External links to other documentation pages (i.e., documentation that is not within this teams-js library) should avoid using the locale in their URLs. The Microsoft documentation site will automatically redirect to the correct locale for the user.
Also, per [the typedoc documentation](https://typedoc.org/tags/link/#:~:text=%7B%40link%7D%201%20TSDoc%20Compatibility%20TypeDoc%20implements%20the%20beta,other%20links.%203%20See%20Also%20The%20%40template%20tag), external links should use markdown and not the `@link` tag. I fixed the one instance of this.
1. Built the documentation locally and tested each of the three updated URLs to ensure they worked and navigated to the correct place.
2. Ensured builds and tests passed
> Updated documentation links to avoid using locale in URLs and use markdown format for external links

- change/@microsoft-teams-js-856c0e77-b263-4d92-ba73-eeb35a3c66b1.json
- packages/teams-js/prepBetaRelease.js
1. Converting pkgParts and betaParts values into numbers before comparisons. String comparison checker was comparing '10' to '9' and that caused '10' < '9' due to checking each character at a time rather than the …
> Fixing incorrect version name being chosen in prepBetaRelease script

- change/@microsoft-teams-js-0921e3b3-3094-48eb-9bc3-26740e08336f.json
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/public/sharing.spec.ts
During my last DRI session, there was a bug reported on sharing.isSupported() returning true while we can repro that it is not  supported on mobile. The root cause is: if host doesn't send empty object to app sdk during runtime, app sdk will provide a default empty object, meaning that capability is supported. Sharing is in the list of this default setting regardless platform. In this PR, we are removing the default support and instead we start to specify in which version that it gets supported and also provide platform info(currently, sharing is only supported on desktop and web)
> If this Pull Request should close/resolve any …
> Bug fix on sharing.isSupported() returning true while not supported on mobile

- change/@microsoft-teams-js-ad46a5c7-5cc0-4176-8539-0b126be3e1f5.json
- packages/teams-js/src/public/video.ts
- packages/teams-js/test/public/video.spec.ts
When incidentally calling both video.registerForVideoFrame and video.mediaStream.registerForVideoFrame, two events with the same name are sent to the host and the host can't identify what triggered the event.
Changed the event name to "video.mediaStream.registerForVideoFrame" in the API `video.mediaStream.registerForVideoFrame`.
Yes
No
Yes
> Use a different event name when calling video.mediaStream.registerForVideoFrame

- tools/yaml-templates/build-app-host.yml
Disabling cache for App Hosting SDK for now, it'll be enabled when migration from `yarn` to `pnpm` is completed in teams-js-sdk.
Commenting cache for now.
> Disable cache for App hosting sdk .

- apps/teams-test-app/src/components/BarCodeAPIs.tsx
- apps/teams-test-app/src/components/GeoLocationAPIs.tsx
Renamed the `Has Permission` and `Request Permission` buttons for GeoLocation API and BarCode API.
What changes: Renaming button labels (which is the `title` field in the codebase) of `Has Permission` and `Request Permission` the same as the button name.
Why made this change: iOS UI test lib `XCTest` can get the item by label only. If more than one button have the same label name, we could use index for accessing different buttons with same label name but then the UI layers change may break index order, which cause E2E test failure. This is a scenario we hope could be avoided, thus, in iOS side, we would like to edit button label name to make them to be unique and function as what box selector id does.
1. Renaming `Has Permission` and `Request Permission` buttons under GeoLocationAPI to …
> Change buttons' name to unblock iOS UI tests

- apps/blazor-test-app/package.json
- pnpm-lock.yaml
Updated the Blazor test app's package.json file to transition to use pnpm style workspaces instead of yarn style workspaces.
> fixed blazor test app's package.json

- apps/blazor-test-app/package.json
- package.json
- tools/yaml-templates/android-test.yml
- tools/yaml-templates/build-app-host.yml
- tools/yaml-templates/build-test-publish.yml
- tools/yaml-templates/ios-test.yml
Added pnpm commands so Lerna does not build the blazor-test-app when simply running `pnpm build`. Instead, I added a `build-force-blazor` option that will build everything, including the blazor-test-app. I then changed all of the build commands that get run in the pipeline to use the `build-force-blazor` command instead.
> added pnpm commands to force blazor build in pipeline

- .github/workflows/prerelease.yml
- README.md
- package.json
- tools/yaml-templates/android-test.yml
- tools/yaml-templates/build-app-host.yml
- tools/yaml-templates/build-test-publish.yml
- tools/yaml-templates/ios-test.yml
Using different `pnpm` versions creates a different lock file version, which leads to inconsistency in `pnpm-lock.yaml` file. 
Add specific version to `pnpm` to avoid inconsistency.
N/A
N/A
> Specify version for pnpm

- change/@microsoft-teams-js-3adbd356-cd9d-4e1d-81f3-e10c19920ba6.json
- packages/teams-js/src/public/app.ts
The documentation for some `enum` properties was wrong (out of date) and unnecessary since it was just literally listing the enum values. I have removed said documentation.
> Remove unnecessary documentation on enums properties

- change/@microsoft-teams-js-566f31c2-a1bc-4ac2-b16a-06ce2ca5f7ef.json
- packages/teams-js/src/public/meeting.ts
- packages/teams-js/test/public/meeting.spec.ts
Per the partner team Polls feedback, they would like to access the getAuthenticationTokenForAnonymousUsers in task context (content bubble and task modules).
1. Added tadk context as an acceptable context to call …
> Adding context task to getAuthenticationTokenForAnonymousUserToken API

- tools/yaml-templates/android-test.yml
> Android tests failing in the pipeline due to the dependency on the 64bit Java after recent upgrade in Hosts layer.
1. Added a yaml step in the android tests pipeline to set Java 11 x64 bit as default when running the Android tests.
1. Android E2E tests should run fine in all pipelines.
No, NA
No, NA
<Yes/No>
> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete …
> Fix android tests failure due to Java version

- apps/teams-test-app/src/App.tsx
- change/@microsoft-teams-js-04be2fe1-06e4-4f4b-ad33-425646831a7e.json
- packages/teams-js/src/public/app.ts
Some of the user info properties in the context came with a warning against misuse but were not clear on exactly what type of misuse should be avoided and the preferred alternative approaches.
There were also some items automatically reordered in the `App.tsx` file that appear to have been leftover from previous developers who did not check in the automated prettier changes.
> Clarify proper usage of user identity properties in context

- .github/workflows/codeql.yml
- azure-pipelines.yml
Enabled CodeQL static analysis in this repository, for javascript/typescript and C#. Most of the code is Javascript, but the SSR test app is C#. The "interesting" part of the configuration is here:
This says that we will run CodeQL in the following cases:
- whenever we push to a branch that matches one of those 4 regular expressions
- whenever a pull request is prepared or changed for a change going into the main branch
- once a week, saturday at 2am UTC
1. Enabled CodeQL workflow for javascript/typescript and C#
Ran pipelines and made sure codeQL was running and that issues were reported in github
No, no code changes that are testable included in this change
No
None needed, change not in code
> Update yml files to enable CodeQL scanning

- apps/teams-test-app/src/components/GeoLocationAPIs.tsx
- apps/teams-test-app/src/components/privateApis/ChatAPIs.tsx
Updated the title for Deprecated OpenConversation capability. In IOS, UI test will fail if we have duplicate title for same capability. Need to change the title for conversation api UI test case in IOS.
1. Change the title to Deprecated Open Conversation in test app.
1. Test the open conversation in test app
N/A
N/A
<Yes/No>
> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).
| < image1 > | < …
> Update the title for the deprecated OpenConversation api in teams app

- packages/teams-js/test/public/appWindow.spec.ts
- packages/teams-js/test/utils.ts
> Unit Test Case update: appWindow.spec.ts

- .github/workflows/codeql.yml
The regular expression I was trying to use to only check pushes to 1.13.* or later for CodeQL issues was causing CodeQL to not run properly. I'm not sure what *exactly* the problem was, but I don't think there's any reason for a regex that complicated so I simplified it greatly. This change means that we'll now run codeql on any pushes to 1.* including branches earlier than 1.13, but that really shouldn't ever happen so I propose we do this for now and we can do something more complicated in the future if needed.
1. Updated CodeQL yaml to now run on pushes to any 1.* release branches instead of just 1.13 or later
1. Ran old yaml through yaml linter and verified there was a problem with that regular expression. Updated yaml as seen here and ran it through the same linter and verified that …
> Removed complicated regular expression that was breaking our CodeQL YAML file

- change/@microsoft-teams-js-e88ee082-6fb3-4779-9727-777bd3b56814.json
- packages/teams-js/src/public/appInstallDialog.ts
- packages/teams-js/src/public/appWindow.ts
- packages/teams-js/src/public/constants.ts
- packages/teams-js/src/public/index.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/test/public/people.spec.ts
> Unit Test Case update people.spec.ts

- packages/teams-js/test/public/app.spec.ts
> Unit Test Case update: app.spec.ts

- apps/teams-test-app/src/components/GeoLocationAPIs.tsx
- packages/teams-js/test/public/barCode.spec.ts
> Unit Test Case update: barcode.spec.ts

- packages/teams-js/test/public/menus.spec.ts
> Unit Test Case update: menus.spec.ts

- packages/teams-js/test/public/monetization.spec.ts
> Unit Test Case update: monetization.spec.ts

- packages/teams-js/test/private/videoEx.spec.ts
- packages/teams-js/test/utils.ts
> Unit Test Case Update: videoEx.spec.ts

- azure-pipelines.yml
Adding another variable to our azure pipeline yaml that will mark pipelines driven by that yaml as being ones that generate production assets. This is needed to correctly tag our pipeline.
1. Added new tags variable to pipeline following internal guidance
1. Ran pipeline and made sure it worked
No
No
No, none needed for yaml update
> Mark our pipeline as something that generates prod assets

- change/@microsoft-teams-js-6fa795d7-0fc0-4847-8537-676a2be140ee.json
- packages/teams-js/src/internal/videoUtils.ts
- packages/teams-js/src/private/videoEx.ts
1. Removing `export type = other type` convention from `videoEx.ts`. This is because exporting a type that was imported as {insert name here} can not properly generate the type when making a .d.ts file. Replacing it …
> Fixing video import/export naming

- package.json
- pnpm-lock.yaml
- tools/bundle-size-tools/package.json
1. Updating package.json because `@types/jszip` package is deprecated and `jszip` versions 3.7.1 and lower have a security vulnerability.
> Removing deprecated @types/jszip package and upgrading jszip package

- apps/teams-test-app/src/components/GeoLocationAPIs.tsx
Small updates to the test app for Android E2E tests. We need to add some parameters to the `navigator.geolocation.getCurrentPosition()` call to make the call work on Android WebViews. This PR also adds an error callback that we need to test the permission denied scenario.
1. Add enableHighAccuracy, timeout, and maximumAge parameters to the Web API geolocation control in the test app
2. Add an error callback to the Web API geolocation call in the test app.
1. WebAPI get position control tested against web, Android, and iOS hosts
No unit tests added, test app change only
Android E2E tests can be checked in after this change
No, test …
> Refactor Web API Geolocation for Testing

- change/@microsoft-teams-js-d2dd363b-e9f0-4ea2-ac07-2f772a296990.json
- packages/teams-js/prepBetaRelease.js
Description
Summarize the changes, including the goals and reasons for this change. Be sure to call out any technical or behavior changes that reviewers should be aware of.
If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.
Main changes in the PR:
Added in a throw error statement if getNewerPrefix completes the for loop without returning.
> Error handling for getNewerPrefix in prepBetaRelease script

- tools/yaml-templates/build-test-publish.yml
1. Publish bundle analysis task hasn't been executing for a while now, this is because it was running on a condition that always returned false. Modified the condition to now only run on PR targeting the main …
> Modified condition for publishing bundle analysis

- README.md
Change README instruction to say to make a branch instead of a fork
1. Change README instruction to say to make a branch instead of a fork
None
No
No
No
> Change incorrect instruction in top level readme

- apps/teams-test-app/src/App.tsx
- tools/yaml-templates/ios-test.yml
There are two parts of bash scripts in YAML file missed semicolons so that the prompts are not properly processed and the failure cannot be thrown as a task failed. Thus, semicolons are added as a fix.
1. add semicolons for separating bash scripts in iOS-test.yml file
Check this example run(after fix): https://office.visualstudio.com/ISS/_build/results?buildId=20898393&view=logs&j=a19010f7-e5b6-5d4e-f3f8-d8dc77971e5f&t=75310659-ec5b-5afc-1cb9-4cce342f4b2f
task failed without prompting "exit 1" at the end of task "iOS UI/E2E Test".
The behavior before fix can be seen here: https://office.visualstudio.com/ISS/_build/results?buildId=20885082&view=results
iOS E2E test actually failed but the task still showing successful because the "exit 1" bash script is not properly handled as semicolon is …
> iOS CI Yaml File Task Bash Script Fix

- apps/teams-test-app/e2e-test-data/search.json
Web Host SDK side just had a change on adding new testing case data for searching capability. Migration is half-way done so I created PR in this place to update testing json data as well.
1. a new test case is added in search.json data
Added API and test for closeSearch
> add a new test case data for search capability

- apps/teams-test-app/src/components/MediaAPIs.tsx
- change/@microsoft-teams-js-94b44717-e417-43af-846a-5afe86c8f2bb.json
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/public/media.spec.ts
1. Added permission functions(`hasPemrission()`, `requestPermission()` and `isSupported()`) for media capability.
2. Added media permission section test boxes for teams-test-app.
3. Added `readonly media?: {};` in `IRuntimeV2` interface.
1. Open teams-test-app, we should see three new boxes for testing has media permission, request media Permission, and media capability support check.
Yes
No, don't have e2e tests.
Yes
> Added permission functions for media capability.

- apps/teams-test-app/src/components/MediaAPIs.tsx
- change/@microsoft-teams-js-2108cec9-a31e-42f0-a93e-23364d5bafaa.json
- change/@microsoft-teams-js-7c9a6aae-faac-439e-9929-82bb4fb2f573.json
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/public/media.spec.ts
1. Added `@beta` tags for media permission functions 
2. Removed support check for media capability in the teams test app.
3. checked `isPermissionSupported()` before has/request permission in media capability.
1. <Step 1>
4. <Step 2>
Yes.
No, don't have e2e tests
Yes
https://github.com/OfficeDev/microsoft-teams-library-js/pull/ …
> Added beta tags for media permission functions and removed support check for media capability

- apps/teams-test-app/e2e-test-data/video.json
- apps/teams-test-app/e2e-test-data/video.sharedFrame.json
Update testing json data under video capability to support videoEX API, which is to keep sync with the change in Web Host SDK for testing.
1. Video E2E testing Json data is updated.
2. 
1. Please search in internal Web Host SDK repo with PR title "support new videoEx API" for validation of the change
> Update video testing json data to support new videoEX API

- apps/blazor-test-app/Interop/TeamsSDK/TeamsContext.cs
- change/@microsoft-teams-js-33fc2e0b-a980-483b-998c-f0cc73805956.json
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/src/public/call.ts
- packages/teams-js/src/public/chat.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/people.ts
- packages/teams-js/src/public/profile.ts
- tools/bundle-size-tools/src/ADO/AdoArtifactFileProvider.ts
AAD has been renamed to Microsoft Entra. See [here](https://www.microsoft.com/en-us/security/business/identity-access/azure-active-directory) for more details. I've updated that name in our comments and docs.
1. Updated comments/docs to refer to Microsoft Entra instead of AAD.
None
No
No
Yes
> Update comments referring to AAD to now refer to Microsoft Entra

- packages/teams-js/test/public/authentication.spec.ts
This test has been a little flaky in the past, primarily because the path we are unit testing has a currently unavoidable 300ms wait in it (100ms from communication.waitForMessageQueue and 200ms from authentication.notifySuccess. There is probably a clever way to track shortening those delays when using unit tests specifically, and we do have that tracked on our backlog. For now, let's extend this timeout so we have more than 50ms of wiggleroom.
1. Extend timeout of authentication unit test from 350ms to 400ms so that we have more time to execute the unit tests without timing them out and failing them unnecessarily.
1. Unit tests …
> Extend timeout of authentication unit test by 100ms

- apps/teams-test-app/e2e-test-data/clipboard.json
- apps/teams-test-app/src/components/Clipboard.tsx
- change/@microsoft-teams-js-160c4fe1-6197-4ca0-b2da-23878826bebe.json
- packages/teams-js/src/public/clipboard.ts
- packages/teams-js/test/public/clipboard.spec.ts
While completing the MacOS and Android feature for clipboard, there were two issues one with `blob` type in Android API 27 as it was not able to read the `blob.text()` function, so this PR resolves it by using `FileReader` instead of blob functions, second one was related to MacOS platform which is the communication should be frameless rather than framed added a check in the `clipboard` api.
> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a …
> Code update for android and macOS

- apps/teams-test-app/e2e-test-data/clipboard.json
Add `platforms` parameter in `Clipboard.json` E2E test file to work with iOS backcompact
1. Add `platforms` parameter
N/A
N/A
N/A
> Update the iOS compact tests

- change/@microsoft-teams-js-4dccb2aa-4ca1-4b62-a68b-68237502f40e.json
- change/@microsoft-teams-js-6a9e9685-b682-40f3-abe9-3a5c94c35f21.json
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/public/app.spec.ts
- packages/teams-js/test/public/runtime.spec.ts
- packages/teams-js/test/public/sharing.spec.ts
- packages/teams-js/test/public/webStorage.spec.ts
When I was investigating an issue, I found that some of the functions and structures that support building a runtime object for Teams back-compat scenarios were confusing and unclear. This change renames some of them to be clearer. No functional changes.
Ensure everything still builds and tests pass.
No, since there is no functional change.
No, since there is no functional change.
Yes
> Rename some functions/structures supporting the Teams back-compat config

- tools/yaml-templates/ios-test.yml
Add auto-retry for failed test case in YAML file to make E2E test more stable.
> Add auto-retry (up to 3) for iOS E2E testing

- .vscode/settings.json
This change enables jest to automatically run all tests when VSCode starts, and then watch for any changes thereafter. Without this, it can make it difficult to debug tests because they haven't already run and you have to figure out how to go get them to run, etc. This just makes the experience easier and more instantaneous (with a small perf hit when launching VSCode since the tests run now)
Ensure that tests pass.
No, because I'm only changing VSCode environment behavior, not the actual product code being tested.
No, because I'm only changing VSCode environment behavior, not the actual product code being tested.
No, the tool said it was not needed.
> Auto run tests when starting VSCode

- packages/teams-js/test/public/app.spec.ts
- packages/teams-js/test/public/navigation.spec.ts
- packages/teams-js/test/public/stageView.spec.ts
Some of the unit tests make assumptions that the capability they are testing will always be supported (i.e., they don't explicitly ensure it is supported as part of their set up). This is fine today, when the default runtime does support them. But it's not fine tomorrow when I update the default runtime to no longer support them (i.e., a future change will remove pages.tabs and from being default supported, since it's not correct for it to be supported on Teams mobile).
This change makes their assumptions explicit by ensuring they are always setting that their capability is supported (in the case of navigation and stageView) and ensuring that the default runtime being tested against is actually specific to the version and platform being specified (in the case of app).
1. Update navigation …
> Fix unit tests that assume the runtime always supports them

- jest.config.common.js
- packages/teams-js/jest.config.js
- tools/bundle-size-tools/jest.config.js
When running jest tests in this repo, this warning would show up multiple times:
```
@microsoft/teams-js: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
@microsoft/teams-js: transform: {
@microsoft/teams-js:     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
@microsoft/teams-js: },
```
When you are investigating unit test failures, noise like this can make it hard to track down issues.
Move the ts-jest config from the `globals` section to the `transform` section, as the warning indicates.
Verified that all jest tests still pass and that the warning is now gone.
No.
No.
None needed.
There's one remaining warning
```
@microsoft/teams-js: ts-jest[config] (WARN) message TS151001: If you have issues related to …
```
> Fix ts-jest globals deprecation warning

- packages/teams-js/test/public/runtime.spec.ts
Today, the runtime unit tests validate that the Teams default runtime gets applied by using strings and regex on the objects. This was fine for the need at the time, but it has limitations. In particular, the code does not support subcapabilities, only comparing top level capabilities (foreshadowing).
Before adding subcapabilities to the runtime objects in a subsequent change, I'm updating this code to use the actual objects when doing comparisons (rather than trying to extend the string-based comparisons) so that it can now support subcapabilities (to any level of nesting).
Update the runtime tests to use object comparisons rather than strings and regex
* Ensure tests continued to pass
* Broke something to ensure the tests failed when they should
No new unit tests were added since this …
> Update runtime unit tests to use objects instead of strings

- jest.config.common.js
The last remaining jest warning in the teams-js repo was this:
```
@microsoft/teams-js: ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
```
It would show several times when running jest tests, adding noise to any attempt to debug issues. With this change, I am fixing that warning and there are now no longer any warnings showing when running jest tests.
Note: I haven't yet figured out if there is a way to make ts-jest warnings show up as errors, to prevent anything like this from being …
> Fix ts-jest warning about esModuleInterop not being true

- apps/teams-test-app/e2e-test-data/clipboard.json
This PR is to change the input type in clipboard json file for e2e test cases from `""` to `{}`.
1. Change the input type in clipboard
N/A
N/A
N/A
N/A
N/A
> Clipboard Test Data fix

- apps/teams-test-app/e2e-test-data/clipboard.json
- azure-pipelines.yml
This PR reverts the changes in clipboard Json as the issue was in parsing in iOS side. Also, as the e2e test data is being pulled from main branch and not taking the updated branch data from the PR, so to fix this issue e2e test cases have been disabled for local and default tags, once the PR is merged, I'll create a new PR to enable e2e test cases.
> Revert back the changes (Hot Fix)

- azure-pipelines.yml
Add useDataFromLocal (additional argument) for Web Hub SDK E2E testing to make sure when PR is triggered from Teams-Js library side, E2E test will pull data from local teams-js library repo rather than remote main branch.
Validation: check CI pipeline job of this PR, it will some prompts like this:
```
Path of microsoft-teams-library-js folder has been found which is /home/......./microsoft-teams-library-js.
Data will be pulled from local Teams-Js Library( path: /home/....../microsoft-teams-library-js ) in ADO virtual machine directly.
```
> Trigger E2E test by using local data when PR raised from Teams-Js library

- tools/yaml-templates/android-test.yml
The "Install emulator" task on the Android E2E testing pipeline is a bit flaky. When it succeeds, it usually takes under 5 minutes, but if it fails it will take the entire 60 minutes allotted to the pipeline. This PR just adds a 10 minute timeout to the task so we can fail this task faster when it doesn't succeed.
1. Add 10 minute timeout to the install emulator task on the Android test pipeline
1. Android E2E tests continue to pass when emulator installs successfully
No, no code changes
No, no code changes
No, pipeline change only
I think we can retry starting the emulator in a separate task after the initial task times out. I'm …
> Timeout install Android emulator task after 10 minutes

- apps/teams-test-app/src/App.tsx
- apps/teams-test-app/src/components/VisualMediaAPIs.tsx
- change/@microsoft-teams-js-f497aa57-1549-40c6-a0f7-89b4c59a2e1f.json
- packages/teams-js/src/public/constants.ts
- packages/teams-js/src/public/index.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/src/public/visualMedia.ts
- packages/teams-js/test/public/visualMedia.spec.ts
Create a new API named visualMedia which will support image sub-capability.
The goal of these changes is to introduce a new API called the 'visualMedia API'. It includes an image sub-capability that allows the host app to upload and capture up to 10 images for the Mos Apps.
1. Implemented the visualMedia API
2. Implemented the image sub-capability with two functions: captureImages() and uploadImages()
1. Build teamsjs code and start-test-app
2. Build orange ios app (host app) and open local test app
4. Scroll to the Visual Media API section, click on "check visual media image capability" to make sure image sub-capability is supported by the host app.
5. Click on "request visual media permission" if the result is false from "has visual media permission"
6. Use the testing inputs:  
For …
> [Task8134448] Implementing the visualMedia API in teamsjs

- change/@microsoft-teams-js-2fa564a4-011e-483c-b49f-4f2d2405da60.json
- packages/teams-js/src/public/runtime.ts
In my previous [PR](https://github.com/OfficeDev/microsoft-teams-library-js/pull/1878/files#diff-85dddae2b8eeec9b3e380ecace89b971146adc53725c2dbf478591f5c5c7730d), we decided to combine two handlers (beforeSuspendOrTerminateHandler and onResumeHandler) into app.lifecyle instead of having a subsubcapability (caching). The runtime file was left unchanged by mistake. This PR update the runtime file to indicate there is no subsubcapability called `caching`
> If this Pull …
> Fix runtime interface for app.lifecycle

- change/@microsoft-teams-js-9e85c1d2-7ae8-4f04-8fb5-867873552c98.json
- packages/teams-js/src/internal/mediaUtil.ts
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/secondaryBrowser.ts
- packages/teams-js/test/public/media.spec.ts
Continuing down the path of fixing more violations of `strictNullChecks` violations across teamsjs, this change fixes the violations in the media*.ts family of files.
I've annotated the PR with specific comments at the areas where the changes are made. That said, the general theme of the changes is to just update the code/types to reflect what the code is already doing -- e.g., the code is already returning `null` in places where it's not allowed, just update the code to reflect that said value is allowed and how it handles it, documenting appropriately.
Ensure all tests continue to pass.
Yes.
#2012 
Fix more violations of `strictNullChecks` across the next set of files.
> Fix strictNullChecks violations in media.ts and mediaUtil.ts

- change/@microsoft-teams-js-0b842417-16fe-4c54-b9f5-70f530257d55.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/videoFrameTick.ts
- packages/teams-js/src/internal/videoPerformanceMonitor.ts
- packages/teams-js/src/internal/videoPerformanceStatistics.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/test/internal/communication.spec.ts
Continuing the journey of fixing `strictNullChecks` violations...
In this change I am mostly just updating the stated types to match the types actually being used. E.g., if the code is actually returning `null` or `undefined` in places, then the type signature should now reflect that.
There are two places (in `authentication.ts`) where I updated the return value to be set to `undefined` instead of `null` because the actual return type was already defined to allow for `undefined` -- so we should just actually use that! I added comments inline in the code review to point these out.
Because of this new, correct, types, some of the communication unit tests now started to trigger violations of `strictNullChecks` because the compiler now realizes that the now-correctly-annotated types might be …
> Fix more "easy" strictNullChecks violations -- ones which just require adding already in-use types

- change/@microsoft-teams-js-e65900ef-5cbc-4129-a931-b3443a53b827.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/handlers.ts
- packages/teams-js/src/private/conversations.ts
This fixes the last of the "easy" fixes of `strictNullChecks` violations in the product code.
The code is directly annotated in this PR to describe the individual fixes.
Ensured all existing tests continued to pass.
Yes
#2012, #2014, #2020, #2024
There still remain a few violations in the product code that will be more invasive to fix and will come next. They will require some refactoring or other functionality changes (or changes that are theoretical functionality changes but likely never get hit in production)).
There are also still a ton of violations in the test code that will also be fixed, but likely not until the product code is fully clean.
In case you're curious, here are the stats for the remaining violations in the product code:
```
Errors  Files
5 …
```
> Fix the last of the remaining "easy" strictNullChecks violations

- change/@microsoft-teams-js-54e1bba3-9307-4dd5-bbab-e3c92d531d39.json
- jest.config.common.js
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/public/app.ts
- packages/teams-js/tsconfig.json
After all the recent PRs to fix violations of `strictNullChecks`, the product code is now down to only 6 remaining violations. These are more invasive to fix and so not to be taken lightly. There are also still a ton of violations in the test code.
However! There are so few violations now that I am comfortable actually enabling `strictNullChecks` for the product code and just suppressing the compiler warning for the specific remaining violating lines! This is a big step forward because it will prevent any new code from adding new violations!
1. Enable `strictNullChecks` in the `tsconfig.json` file for the product code -- this will ensure the compiler now enforces `strictNullChecks` for all product code.
2. Suppress the remaining violations of this in `communication.ts` and `app.ts`. Note …
> Enable strictNullChecks for product code!

- apps/teams-test-app/src/App.tsx
- apps/teams-test-app/src/components/Custom.tsx
Adding a module for custom API in the test app which will facilitate e2e testing for the custom message service that is being added to the host SDK. 
N/A Test tab update
N/A
<Yes/No>
> Add test tab module for custom message api

- change/@microsoft-teams-js-26de76b6-42fd-440a-a405-705efdaf1089.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/interfaces.ts
- packages/teams-js/src/internal/messageObjects.ts
- packages/teams-js/test/private/privateAPIs.spec.ts
- packages/teams-js/test/private/videoEffectsEx.spec.ts
- packages/teams-js/test/public/meeting.spec.ts
- packages/teams-js/test/public/pages.spec.ts
- packages/teams-js/test/utils.ts
There are some violations of `structNullChecks` remaining in `communication.ts` that are fundamentally unfixable without program flow changes. For example, the `MessageRequest` structure has some properties which are optional, but there is code in `communication.ts` that assumes they are always defined. Generally speaking, fixing these will require one-by-one incremental changes to the code structure.
This first change is the easiest. 😜 
1. Create a new message request interface, `MessageRequestWithRequiredProperties`, which derives from the old interface (`MessageRequest`) that marks the previously optional properties as requred. Since this new interface derives from the old, it can be used interchangeably in any place the old interface was used.
2. Update the `createMessageRequest` …
> Create new, alternate, MessageRequest structure with expected required properties

- apps/teams-test-app/e2e-test-data/app.json
This PR doesn't do too much change but updated some inputs and outputs under app capability. I believe those test cases have real inputs and outputs before, which are okay. The problem it raised is that the real inputs and outputs are too long and typing input in iOS simulator sometimes is finished after clicking corresponding buttons, which will cause flaky failure.
So, this PR is to shorten those inputs and outputs, which will help to decrease flaky failure rate.
1. Shorten inputs and outputs in app.json file
1. E2E checking from this PR (running on latest branch of TJS) should pass
2. E2E checking against on this PR in Web Host SDK passes: https://office.visualstudio.com/ISS/_build/results?buildId=24212677&view=results
PR:https://office.visualstudio.com/ISS/_git/metaos-hub-sdk/pullreque …
> Update App capablity E2E testing json data with shorten inputs and outputs

- apps/teams-test-app/src/components/privateApis/ChatAPIs.tsx
- change/@microsoft-teams-js-aae140c3-b4de-4ac4-b3cc-e590c4af6bc5.json
- packages/teams-js/src/public/chat.ts
- packages/teams-js/test/promiseTester.ts
- packages/teams-js/test/public/chat.spec.ts
The contract for communicating between teams-js and the host library for opening chat requests (`chat.openChat` message) is that the desired users will be passed as an array in the `members` property. The `chat.openChat` function, used when only a single user is intended to be specified, was not doing that. It was passing the single user as a string. Consequently, when the host library (and/or the host) received the message, it could not handle it correctly because it was expecting `members` to be an array of strings and not a single string.
Relatedly, the `chat.openGroupChat` function was similarly broken when a single user was passed to it, since it deferred to `chat.openChat` in that case.
As part of testing, I also discovered these issues:
- When `chat.openGroupChat` defers to …
> Fix calls to chat capability when only a single user is specified

- apps/teams-test-app/e2e-test-data/meeting.json
- apps/teams-test-app/src/components/MeetingAPIs.tsx
- change/@microsoft-teams-js-162b7ca7-85cf-4fe6-b75d-2f978e74d906.json
- change/@microsoft-teams-js-e24f0888-8dce-4502-b900-4e4ab7eb1f64.json
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/meeting.ts
- packages/teams-js/test/public/meeting.spec.ts
- packages/teams-js/test/utils.ts
**This change was originally committed with PR #2030. It had to be reverted with PR #2069. This PR fixes the problem (adds version constraint to two new tests added in `meeting.json`). Other than that change, everything in this PR is identical to #2030. You can verify this by running `git diff 6f23f92877165e7909c202d039aa0db6fa481248 origin/bingliang/audio-device-selection-sync` which will compare the commit of the original PR with this branch**
This is a continuous PR of the original [PR](https://github.com/OfficeDev/microsoft-teams-library-js/pull/1931) by [shilcare](https://github.com/shilcare). There is another outdated PR from a fork [here](https://github.com/OfficeDev/microsoft-teams-library-js/pull/2008), change to this branch PR because of security issues.
Give Teams apps the …
> Extend RequestAppAudioHandling to support for audio device selection sync

- change/@microsoft-teams-js-ffdf93d1-4a5d-4c9c-abbd-620b88478b53.json
- packages/teams-js/src/private/externalAppAuthentication.ts
Make composeExtension a required property on `IQeuryMessageExtensionResponse`
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No> …
> Make composeExtension a required property on query message extension response in external app auth capability

- apps/teams-test-app/e2e-test-data/externalAppAuthentication.json
- apps/teams-test-app/e2e-test-data/externalAppCardActions.json
Nothing will be added here because we need to let test app to be presented as external app without exposing appId. So we will add all of test cases in web host sdk side.
1. Add testing json file for compiling
> Adding E2E Testing Json files for external app Capabilities

- change/@microsoft-teams-js-17e23500-2b46-429a-83cc-62548c0a1e5e.json
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/public/runtime.spec.ts
The unit tests for versioned runtime application function (`generateVersionBasedTeamsRuntimeConfig`) were confusing to understand, wrong, and incomplete.
- There was a lot of nesting both inside and outside of the tests, making it hard to read and understand.
- The tests only tested for one version lower, and not all versions in the map
- The tests which tried to validate that unsupported platforms were always unsupported were broken in the case where one capability was supported on some platforms and then later that same capability was added for other platforms.
 
1. Refactor and rewrite the tests to, hopefully, be more readable.
2. Write a new test that properly validates the unsupportedness of platforms
Reviewers may find it easier to ignore the diff and just look at the "right side" …
> Fix and enhance readability (hopefully) of unit tests for versioned runtime 

- azure-pipelines.yml
- tools/yaml-templates/build-test-publish.yml
1. Separating validDomains from CDNFeed to allow us to decouple validDomains list being updated on every PROD/SDF release
1. Artifact generated by build pipeline creates a new validDomains artifact in the top level …
> Moving validDomains into a separate artifact for new release pipeline

- change/@microsoft-teams-js-d1b21769-c65c-4536-a016-0f0231541e66.json
- packages/teams-js/.eslintrc.js
Prefixing unused parameters/variables with underscore is a very common convention to indicate "this parameter is intentionally not used." Our own tooling in VSCode even auto-suggests doing it as a "fix" for unused parameters when it sees them. Unfortunately, our linting rules do not recognize the leading-underscore as meaning anything special and still errors about unused parameters.
This change updates our lint rules to allow for a leading underscore and ignores any unused violations in those specific cases.
Make a parameter unused with a leading underscore and validate that no lint error is triggered.
Yes.
> Allow underscore for unused parameters

- .gitignore
VSCode will (often? usually?) suggest you install the C# tools because it sees the Blazor app. If you accept (and why would one know any better?), it causes a VS solution file to be put at the root of the repo. This file does not exist in the repo, so it means everyone will have it showing up in their PRs until it either gets added or ignored. @noahdarveau-MSFT, the resident Blazor expert, says the right thing to do is to .gitignore it.
Add the .SLN file to the .gitignore file
No, not required.
> Add Blazor solution to .gitignore

- beachball.config.js
- change/@microsoft-teams-js-8fa5d255-6960-4bce-a06f-19369f4b72c7.json
- package.json
- packages/teams-js/src/public/dialog.ts
Updated the beachball experience for changefile creation so that *common* types of changes now have easy options developers can pick which will add standardized changefile descriptions to your the changefile in your branch. This will hopefully encourage more consistent patch notes for external developers.
1. Added 4 common options to the beachball change description field, as seen below:
Choosing one of these options will add a description to your changefile that may have simple placeholders you need to fill in manually.
2. Updated the beachball description prompt so that it encourages developers to fill in placeholders.
3. Made it so the `pnpm changefile` command no longer auto commits changefiles and instead just puts them in your branch's uncommitted files (which will hopefully …
> Updated the beachball experience to encourage more consistent changefile messages

- README.md
We used to require *exactly* pnpm version 7.30.1. Now we require 7.30.1 _or greater_. I've updated the README to reflect this change.
1. Updated README
None
No
No
No, README only change doesn't require changefile
> Update README.md with new pnpm installation instructions

- apps/teams-test-app/e2e-test-data/meeting.json
Recent PR #2158 added some expected values that are only valid in the most recent teamsjs source. Those expected values are not correct for earlier versions. This is my attempt at properly versioning the expected values.
Note: this problem is currently breaking all check-ins to a certain other unnamed repo
Beachball says none is required.
> Fix meeting tests so they are version-aware

- .github/workflows/main.yml
All unit test publishing steps are failing now; it looks like this is related to the recent token changes. I am going to disable the publish UT step for now (so we don't train people to get used to ignoring failures) and in parallel investigate how to fix/re-enable it
1. Commenting out the Publish UT step from our build pipelines temporarily
> Disabling unit test publishing temporarily

- apps/teams-test-app/e2e-test-data/meeting.json
When the meeting tests are run against older host SDKs, the alerts are in a different format. This change accounts for that.
> Update meeting.json to account for different alert formats in host SDK versions

- package.json
- pnpm-lock.yaml
This repo has a CG violation for the `ip` project. The `ip` project has a published security vulnerability:
https://github.com/indutny/node-ip/issues/136 
https://github.com/advisories/GHSA-78xj-cgh5-2h22 
Unfortunately, there's no fixed version of the `ip` project. Moreover, there are questions in the "Issues" section of that project asking whether there's even a maintainer for it.
We indirectly use `ip` because we use lerna, which has a whole chain of dependencies which eventually leads to `ip`
The package in that chain which depends on `ip` is `socks.` The socks package [HAS been …
> Updated socks package to a version that doesn't use the IP package

- change/@microsoft-teams-js-50106ba4-7db7-4113-ae30-1fa99d4cc0b3.json
- packages/teams-js/src/internal/videoEffectsUtils.ts
- packages/teams-js/src/private/externalAppAuthentication.ts
- packages/teams-js/src/public/chat.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/teamsAPIs.ts
1. Fix doc URL links to remove hardcoded locale (en-us) and allow the docs site to redirect to the current user's locale. This is a best practice from the docs team
2. Fix the documentation on the `user` property of `OpenSingleChatRequest` to reflect that it's only a single UPN
3. Fix the markdown on the URL in the documentation for `SecondaryM365ContentIdName` which had reversed brackets/parentheses
Yuppers
> Fix a few doc bugs I discovered

- change/@microsoft-teams-js-5cc77b90-8226-4b99-8dd7-e9f697b4c5d9.json
- packages/teams-js/src/artifactsForCDN/validDomains.json
- packages/teams-js/test/internal/validOrigins.spec.ts
- packages/teams-js/test/private/privateAPIs.spec.ts
No longer need one of the valid origins.
1. Removed `*.teams.microsoft.com` from the list of valid origins we store. (`teams.microsoft.com` is still there though)
2. Updated unit tests.
1. Ran unit tests
No
No
Yes
> Remove valid origin that is no longer needed

- apps/teams-test-app/e2e-test-data/meeting.json
When the `meeting.joinMeeting` tests were added in 2203, the new tests were set to run on any version of the host runtime >= 2.12.0. This was done due to a problem with how tests are run in these pipelines:
- The most recently released version of the host runtime is 2.12.0.
- The code in the host runtime that knows how to run these tests was checked in after 2.12.0 is released, therefore, these tests cannot run against 2.12.0 or anything earlier
- However, due to a problem in the test infrastructure, the "latest" version of the host runtime always thinks it is the last released version, EVEN when new code has been added to "latest" (but not yet released).
- Consequently, if I restricted the new tests to ">2.12.0", they would not have run during check-in because the latest host runtime …
> Updated version spec on new joinMeeting tests to be correct

- change/@microsoft-teams-js-66c6dadf-b3af-4de0-b855-89376c0f873a.json
- packages/teams-js/src/internal/utils.ts
- packages/teams-js/src/private/externalAppAuthentication.ts
- packages/teams-js/src/private/externalAppCardActions.ts
- packages/teams-js/test/internal/utils.spec.ts
- packages/teams-js/test/private/externalAppAuthentication.spec.ts
- packages/teams-js/test/private/externalAppCardActions.spec.ts
GUID checks are removed for app Id because apps are not promised to have Id in GUID format.
We had a bug ticket saying that appID works in Teams but failed in Teams-JS library because it is not GUID format. That is to say we are too strict to App Id format so we need to loose it a little bit to be aligned with Teams.
https://github.com/OfficeDev/microsoft-teams-library-js/issues/2223
1. Remove everything related to GUID check.
1. isValidAppId function is removed so it should be compiled successfully and no where is using that function.
> Removed all of GUID checks

- change/@microsoft-teams-js-1f05f3e0-286f-4831-8747-649c0e47e551.json
- packages/teams-js/src/public/clipboard.ts
- packages/teams-js/test/public/clipboard.spec.ts
Currently developers are facing [issue ](https://github.com/OfficeDev/microsoft-teams-library-js/issues/2196) in desktop clients on clipboard capability. This PR adds changes to how `App` interacts with parent window over JSON string rather than `blob`.
1. Added desktop to use JSON string to read response from clipboard.
2. Added desktop to unit tests.
> Unit tests are …
> Bug Fix:  Clipboard capability throwing error `DOMException: Document not focused` 

- change/@microsoft-teams-js-889e1105-9a8b-468a-94d7-ed8253cdf569.json
- packages/teams-js/src/internal/telemetry.ts
1. Made the telemetry string enum `const` to reduce package size. By making the enum `const` the minified code will symbolize the enum, reducing the package size by ~10%. In typescript, enums by default, have …
> Telemetry string size reduction

- apps/teams-test-app/src/App.tsx
- apps/teams-test-app/src/components/privateApis/ExternalAppCommandsAPIs.tsx
- change/@microsoft-teams-js-2759cb8f-9b8e-42d5-91f1-9328285f396e.json
- packages/teams-js/src/internal/telemetry.ts
- packages/teams-js/src/private/constants.ts
- packages/teams-js/src/private/externalAppCardActions.ts
- packages/teams-js/src/private/externalAppCommands.ts
- packages/teams-js/src/private/index.ts
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/private/externalAppCardActions.spec.ts
- packages/teams-js/test/private/externalAppCommands.spec.ts
- packages/teams-js/test/private/privateAPIs.spec.ts
- packages/teams-js/test/public/app.spec.ts
Adds the 1P internal-only externalAppCommands API for delegating certain actions to the host.
1. Add externalAppCommands capability
2. Add externalAppCommands.processActionCommand API
1. Unit tests
2. Capabilities added to the teams test app …
> Implementing the externalAppCommands API

- change/@microsoft-teams-js-23031b9f-4c4f-460b-8d82-3e0cdbb78e6c.json
- packages/teams-js/src/internal/nestedAppAuth.ts
- packages/teams-js/src/internal/telemetry.ts
- packages/teams-js/src/internal/videoEffectsUtils.ts
- packages/teams-js/src/private/constants.ts
- packages/teams-js/src/private/externalAppAuthentication.ts
- packages/teams-js/src/private/externalAppCardActions.ts
- packages/teams-js/src/private/files.ts
- packages/teams-js/src/private/interfaces.ts
- packages/teams-js/src/private/remoteCamera.ts
- packages/teams-js/src/private/teams.ts
- packages/teams-js/src/private/videoEffectsEx.ts
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/src/public/call.ts
- packages/teams-js/src/public/constants.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/liveShareHost.ts
- packages/teams-js/src/public/mail.ts
- packages/teams-js/src/public/marketplace.ts
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/meeting.ts
- packages/teams-js/src/public/menus.ts
- packages/teams-js/src/public/stageView.ts
- packages/teams-js/src/public/videoEffects.ts
1. I decided to go through the teams-js package and make as many enums `const` as possible. You can read the description for [this PR](https://github.com/OfficeDev/microsoft-teams-library-js/pull/2237) for an …
> More package size reductions

- change/@microsoft-teams-js-46bb0b2e-b9eb-4242-8a86-665f5cb915ba.json
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/src/public/call.ts
- packages/teams-js/src/public/constants.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/src/public/liveShareHost.ts
- packages/teams-js/src/public/marketplace.ts
- packages/teams-js/src/public/media.ts
- packages/teams-js/src/public/meeting.ts
- packages/teams-js/src/public/menus.ts
- packages/teams-js/src/public/stageView.ts
- packages/teams-js/src/public/videoEffects.ts
1. Initially when making the const enum changes , I made the changes with the understanding that string enums inherently did not get reverse mappings, so it would not be an issue to make all of the public string …
> Backed out const enum changes to public api

- apps/teams-test-app/e2e-test-data/messageChannels.json
- apps/teams-test-app/src/components/privateApis/MessageChannelAPIs.tsx
This change updates the test app and adds JSON for E2E tests for the MessageChannels.getTelemetryPort function.
A follow up PR will add the capability test for MessageChannels once the test app changes are tied to a published version.
1. Update test app to have capability check box
2. Create test JSON
1. Test JSON was validated with an external test runner
No, this is follow up to the main change [here](https://github.com/OfficeDev/microsoft-teams-library-js/pull/2140), where the unit tests were added.
Yes
Not required for adding an E2E (no changes to published packages)
[https://github.com/OfficeDev/microsoft-teams-library-js/pull/2140](https://github.com/OfficeDev/microsoft-teams-library-js/pull/2140)
> MessageChannels.getTelemetryPort: Add E2E Test JSON

- azure-pipelines.yml
- tools/yaml-templates/ios-test.yml
**Summary:**
Separating iOS E2E testing pipeline to be 2 to reduce executing time and avoid hitting time limitation.
**Main Changes:**
Passing test plan name to yaml template to execute E2E test separately in two different pipelines.
**Validation Steps:**
For each of pipeline, you could click 'IOS UI testing' task and at the top of the console, you can read script to figure out which testing plan is executed.
For example, `/usr/bin/xcodebuild -configuration Release -workspace ... -scheme ... -testPlan iosE2ETestPlanA** -sdk iphonesimulator -parallel-testing-enabled YES -parallel-testing-worker-count 2 -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' -screenshot-enabled="YES" test`
> Split iOS E2E Testing pipeline to two

- change/@microsoft-teams-js-51421b73-089f-43de-9076-75563e1f064c.json
- packages/teams-js/src/public/pages.ts
Removed the beta tag as we decided pages.currentApp namespace and the APIs can graduate to stable
1. Removed all beta tags under pages.currentApp namespace
> Removing beta tag - Vikramtha/update pages current app

- change/@microsoft-teams-js-4460db5d-e36a-40b9-8df7-0c61833d18d8.json
- packages/teams-js/src/public/authentication.ts
Adds a comment to `openAuthenticationWindow` function inside `authentication.ts` file, explaining why this function is needed.
1. Added comment to `openAuthenticationWindow`
> Add description for pop-up auth window.

- apps/teams-test-app/e2e-test-data/webStorage.json
@KangxuanYe originally said this should be blank, so that's what I did. It turns out that blank actually breaks the tests so I have now updated it to be "almost blank," per @KangxuanYe's recommendation. When testing locally, this does not exhibit the same failure.
> Update webStorage.json to not be blank, but almost blank

- change/@microsoft-teams-js-d2040181-a9a1-42d2-9080-35acb3a380cd.json
- packages/teams-js/src/public/pages.ts
API version tag for Pages.NavigateToApp should use ApiName.Pages_NavigateToApp.
> Fixed incorrect API telemetry label for Pages_NavigateToApp API

- .github/workflows/main.yml
- .github/workflows/prerelease.yml
- README.md
- package.json
- pnpm-lock.yaml
- tools/yaml-templates/android-test.yml
- tools/yaml-templates/build-app-host.yml
- tools/yaml-templates/build-test-publish.yml
- tools/yaml-templates/ios-test.yml
Recently there have been an issue where `pnpm-lock.yaml` file is having conflicts by using different `pnpm` versions. To address this issue this repo will be moving to `pnpm v9.0.6` which is the latest version and the change file states that `pnpm v9` has adopted `lockfile v9` format which is more resistance to git conflicts (more about the changelog [here](https://github.com/pnpm/pnpm/releases/tag/v9.0.0)). Also, we will be upgrading `pnpm` version when major bump is available (i.e., v9 -> v10).
> If this Pull Request should close/resolve any issues when merged, use [the special syntax for …
> Upgrade `pnpm` to v9

- change/@microsoft-teams-js-3df1e388-302e-45ea-b24a-b46d2150dd9b.json
- packages/teams-js/scripts/add-npmrc-npmtoken-onebranch.ps1
- packages/teams-js/scripts/view-published-packages-urls-onebranch.ps1
- tools/releases/sdf-release.yml
Update the release yaml to use inline scripts for adding npm token to the .npmrc and listing the npm and cdn release information
1. Successful NPM and CDN releases performed with the updated YAML
No
No
Yes
> Update the SDF release yaml

- apps/teams-test-app/e2e-test-data/otherAppStateChange.json
- apps/teams-test-app/e2e-test-data/search.json
The event input data should be sent in the required format. This PR removed unnecessary array wrapping for the event data in e2e tests.
1. Updated `search` and `otherAppStateChange` e2e tests data in teams-js.
1. …
> Updated `search` and `otherAppStateChange` e2e tests data in teams-js

- tools/releases/ddl-release.yml
The source variable on the teams-js pipeline was incorrectly listed in the DDL release pipeline, updated with the correct path.
1. Update teams-js pipeline source with full path
> Update pipeline source for DDL release

- SECURITY.md
Microsoft OSS guidance suggests that all OSS repositories should have a `SECURITY.md` file that details how to report security issues. I've taken this one from the internal template for what information should be included.
1. Added `SECURITY.md` to help repository users quickly understand how to report security issues.
None
No
No
No, md file only changes don't need changefiles
> Add documentation for reporting security concerns

- tools/yaml-templates/ios-test.yml
This PR is to ALWAYS publish the artifacts on iOS E2E testing pipeline for the convenience of investigating some flaky failures if those happen. You could go to pipeline and click "published artifacts". Then you will find two folders which are called iOSDebugLogs - iosE2ETestPlanA and iOSDebugLogs - iosE2ETestPlanB.
Those folders will always be there for each run but it only worth to take a look into those folders if something fails on iOS E2E pipelines. If all tests are passed successfully, publishing process should only take seconds and I think it is okay. to put always condition on those tasks since sometimes, pipeline will …
> Publish xctest result for screenshots and diagnostic logs

- apps/teams-test-app/src/App.tsx
Added search URL parameter `origins` to send origins to `app.initialize()`.
1. Added a URL search parameter `origins`.
N/A
No
No
> Added url search parameters for insecure e2e testing

- apps/teams-test-app/package.json
- apps/teams-test-app/src/App.tsx
- apps/teams-test-app/src/components/AppAPIs.tsx
- apps/teams-test-app/src/pages/SecondRoute.tsx
- apps/teams-test-app/src/pages/TeamsTestApp.tsx
- apps/teams-test-app/src/pages/TestApp.tsx
- apps/teams-test-app/webpack.common.js
- pnpm-lock.yaml
- tools/releases/ddl-release.yml
This PR adds React Router to enable navigation between tabs when caching is enabled. There is no Nav component because tabs are populated in the appDefinition files. The onResume function is changed to navigate based on the URL provided.
1. add react router to the package
2. add an empty page for testing
3. enable routing in the app.tsx file
4. update webpack config so the …
> Add react router for navigation testing

- tools/yaml-templates/android-test.yml
Adds a new step to the Android pipeline for pulling test result data from the device even when the tests time out.
1. Add new step in android test yaml for pulling test data
1. Tested against corresponding changes in Android repo
No
No
> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md# …
> Always pull Android test artifacts

- tools/yaml-templates/android-test.yml
Updating the Android pipeline to auth against the ISS_PublicPackages feed as well as the Lens feed. This is necessary because Android host SDK is now pulling its upstream dependencies from the internal ISS feed instead of the public google and mavenCentral feeds.
1. Add "ISS_PublicPackages" to the authentication step in the android test yaml
1. Android tests run and pass in pipeline
No, pipeline changes only
No, pipeline changes only
No, pipeline changes only
> Android E2E tests: authenticate to ISS Feed

- .npmrc
- pnpm-lock.yaml
`pnpm` does not automatically install peer dependencies (which is a [recommended](https://nodejs.org/en/blog/npm/peer-dependencies) [behavior](https://javascript-code.dev/articles/206234324) and the default in npm) and this repo doesn't currently enable the setting to fail if conflicting/missing peer dependencies are detected. This change enables automatically installation of peer dependencies and will fail if there are any conflicts. Fortunately, there are none today but this will prevent problems from being accidentally introduced in the future (like in some other repos... <wink wink>)
Added `.npmrc` file with appropriate `pnpm` configuration settings to enable automatic peer dependency installation and failure when it doesn't work
Neither `pnpm i` nor `pnpm install --resolution-only` …
> Enable pnpm to automatically install peers and fail if there are conflicts

- tools/yaml-templates/build-app-host.yml
Add a command in `build-app-host.yml` to remove the preinstall script for app hosting directory. This make sures that we don't run the preinstall script in the App Hosting directory.
1. Add a `sed` command to remove preinstall command from app hosting's `package.json`
Made sure everything builds as expected.
> Unit tests are required for all changes. If no unit tests were …
> Add sed command to remove preinstall in AppHostingDirectory

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-2793e8d4-d3ef-4d16-9b98-afc8ce9bf355.json
- change/@microsoft-teams-js-4f7e8cc9-56bd-4cc3-994e-d0dcac0805c5.json
- change/@microsoft-teams-js-6bbc95da-c538-4e67-9bd2-691fff1e1029.json
- change/@microsoft-teams-js-8bc1eae5-cc68-4cdb-a5ee-9862ac5e5b8d.json
- change/@microsoft-teams-js-95373f3c-2784-40bb-b95f-eb6bf6b2e53a.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
- packages/teams-js/src/internal/videoEffectsUtils.ts
- pnpm-lock.yaml
1. Updated hash values and references for CDN endpoint of TeamsJS for the 2.25.0 release
2. Compiled all change files into `CHANGELOG.md`
3. Bumped up package version to 2.25.0
4. ESLint upgrade autofixed spacing in …
> Releasing 2.25.0 of TeamsJS

- tools/yaml-templates/ios-test.yml
Temporarily enabling iOS E2E tests exclusively for `PR Automated` triggers and disabling them for all other triggers until the iOS E2E issue is resolved.
1. Added a condition in the ios-test.yml file to restrict the run to PR builds only.
1. Tested on a manual build.
N/A
N/A
> Switch iOS E2E trigger to PR builds only

- apps/teams-test-app/e2e-test-data/authentication.json
- change/@microsoft-teams-js-fcf61832-de53-4b49-824d-233e1c99caab.json
- packages/teams-js/src/internal/videoEffectsUtils.ts
- packages/teams-js/src/public/authentication.ts
- packages/teams-js/test/internal/communication.spec.ts
- packages/teams-js/test/public/authentication.spec.ts
In the case of an error returned from `authentication.getUser`, the error message was not being properly unwrapped and so callers couldn't really make heads or tails of it. This change ensures the `SdkError` returned by the host is properly transformed into an `Error` so it can be interpreted by the caller. This was in response to a user report.
Prior to this change, you'd have to know how to dig into multiply nested objects to get the result. Now it's just a standard `Error` with `message`.
I added an E2E test for this (and validated that it ran and passed in these pipelines):
```
✓ - Target Web Host SDK v-latest - getUser API Call - Failure (Not full trust)  - iOS Excluded  - >2.25.0
```
I updated the unit tests to validate this behavior. There were already unit tests, but they were …
> Enable errors to be used be callers of getUser

- .github/workflows/codeql.yml
We've been getting codeql actions deprecations warnings for a while now, this PR updates our workflow to use V3 packages and fixes all 4 warnings:
1. Checks pass and validate that no warnings are showing
Not necessary for workflow change
> update codeql actions to v3

- apps/teams-test-app/e2e-test-data/authentication.json
Updated the getUser test to be in line with the expected changes from the updated getUser function which will enable Micrsoft owned apps the same permissions of full-trust apps. 
1. Add hostSdkVersion boundaries
2. Add tests that cover the new cases with a second boolean variable
1. tests pass locally in the host SDK
Yes
> Update e2e tests with targetted versions for getUser update

- azure-pipelines.yml
- tools/yaml-templates/web-e2e-tests-job.yml
The JS file used to run E2E tests is getting replaced with a TS file. Functionality is currently identical between them, so this change just updates the tests to target the new TS file.
Ensured that all E2E tests ran and passed (see the associated pipeline runs)
> Switch all calls of runAppsWithE2ETest.js to the TS version

- .vscode/settings.json
- tools/yaml-templates/web-e2e-tests-job.yml
The Electron integration tests need the test app and test host to be running in order to function. There was not previously a way to get these running without using the E2E test script and supplying no tests to run and relying on the side effect of it starting these.
I recently introduced the server manager script in the other repo to directly expose this functionality and these changes leverage it.
I also added a comment requested from a previous PR.
1. Ensured that electron tests pass
2. Ensured that failed electron tests fail the pipeline (they actually don't show up in the tests tab but that's a problem that appears to have existed for a long time; I can look into that in the future).
> Use server manager script for electron tests

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-48fab7bb-bf40-4e94-9ff7-d08b07206e8c.json
- change/@microsoft-teams-js-778a55b4-3b28-4ed7-8e7c-c2c77db9e75a.json
- change/@microsoft-teams-js-7daad43b-8a9d-4be7-af67-fb0b0ca71a47.json
- change/@microsoft-teams-js-a5218507-221a-43fb-9564-a80174a8f210.json
- change/@microsoft-teams-js-ab962b64-97fb-4ebd-93de-c638eb3dd8eb.json
- change/@microsoft-teams-js-ae62d2ab-6f4d-48ba-a644-fc76e1bc23c0.json
- change/@microsoft-teams-js-b3cc9e88-9329-4a98-95d5-6878864906cc.json
- change/@microsoft-teams-js-c4732925-47c0-4279-aa4f-0ef18f84e7e9.json
- change/@microsoft-teams-js-e3bcf90d-72f4-4327-b55b-ac2eb8aa27bd.json
- change/@microsoft-teams-js-e8356e20-e744-404a-a4f5-664572111da4.json
- change/@microsoft-teams-js-ff847aa3-b792-4039-a11f-7a47ae19b832.json
- change/@microsoft-teams-js-ff97af92-0973-453d-a291-fbfc0130cd64.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
1. Updated hash values for CDN release
2. Consolidated changefiles into CHANGELOG
> Set-up for 2.27.0 release

- change/@microsoft-teams-js-a1bf0d67-6f27-4b52-bcbb-30f734313db1.json
- packages/teams-js/src/public/sharing.ts
- packages/teams-js/test/public/sharing.spec.ts
Removing validations not valid for content fields. AuthorId and ThreadIds are not valid uuids.
Removing validations for authorId and threadId not valid for content fields.
Yes
Yes
> Removing validations not valid for content fields

- change/@microsoft-teams-js-1257aa2f-91cd-490f-94ba-d9fd85728ddf.json
- packages/teams-js/src/internal/utils.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/test/private/copilot.spec.ts
The `AppEligibilityInformation` interface has properties that can be `null` on it. If the `RuntimeConfig` object sent from host SDK to teams-js contains `null` values for those properties, the `applyRuntimeConfig` function in teams-js will throw an error ("TypeError: Cannot convert undefined or null to object") and cause `app.initialize` to fail.
Additionally, this PR ensures that the `AppEligibilityInformation` interface is consistent with the definition in the host SDK library.
1. Handle the case where `null` values in the `RuntimeConfig` from the host SDK will cause an error, ultimately causing `app.initialize` to fail.
2. Update the `AppEligibilityInformation` interface to match the definition in the host SDK library and add a unit test to validate handling `null` values.
1. Added a …
> Fix a bug where null values in RuntimeConfig cause initialize to fail

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-1257aa2f-91cd-490f-94ba-d9fd85728ddf.json
- change/@microsoft-teams-js-a1bf0d67-6f27-4b52-bcbb-30f734313db1.json
- change/@microsoft-teams-js-ae62d2ab-6f4d-48ba-a644-fc76e1bc23c0.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
Tue, 03 Sep 2024 22:19:52 GMT
- Removed invalid validations for content fields on `IContentResponse` interface
- Fixed a bug with `AppEligibilityInformation` that could cause `app.initialize` to fail.
> Release 2.28.0

- .vscode/settings.json
This adds a configuration to the workspace vscode settings to make vscode recognize the proper eslint configuration file and the relative working directory for each sub-package in the monorepo.
1. Add working directories settings through workspace settings in vscode
I opened the files locally and created apparent error lines that eslint should point out and it work flawlessly. As this change is done through the vscode setting, this does not impact any other outside script other than the editor experience.
Not needed as it related to developer experience instead of a new feature or bug.
No
No
| ![image](https://github.com/user-attachments/assets/fb001f4f-f82d-4781-8996-db3725655a65) | …
> Fix bug where eslint configuration could not resolve tsconfig in VSCode

- package.json
- pnpm-lock.yaml
There is a [vulnerability](https://github.com/advisories/GHSA-4vvj-4cpr-p986) discovered in webpack 3.93.0 which is fixed in 3.94.0. 
Upgrade webpack into 3.94.0 in package.json file in root directory.
> Upgrade webpack into 3.94.0

- apps/teams-test-app/src/pages/TestApp.tsx
There have recently been some bugs exposed when apps reload themselves internally (as opposed to the host reloading the whole app container). This change adds a button to the test app which will trigger an internal reload so that tests can be written which trigger this behavior.
- Manually verified that when I click the button it reloads
- Verified that reloading in this fashion on older host SDKs exposes some of the recently fixed bugs
> Add button to test app to reload itself

- .vscode/settings.json
- change/@microsoft-teams-js-b61435ce-c9da-47bc-9b65-2710406ac8d7.json
- packages/teams-js/src/internal/communication.ts
From having read a lot of logs recently, the messages emitted from the communications module were often confusing or hard to follow. This change fixes the issues seen:
- Message ids logged were originally confusing and inconsistent. This was because the code was only logging some of the ids some of the time (e.g. only the uuids and not the legacy ids). Moreover, when it was logging the UUIDs, it was using the `%i` format specifier, which I _think_ tells it to format it as an integer (although [the official debug docs](https://www.npmjs.com/package/debug) don't list `%i` as an officially supported formatter). This change logs both IDs all the time and it now correctly logs the UUIDs as strings.
- This change now explicitly logs information about when the library is relaying messages to and …
> Improve message logging from communications module

- .vscode/settings.json
- change/@microsoft-teams-js-120060c9-a050-4da3-a0a5-2323e3a78d10.json
- packages/teams-js/src/public/app.ts
When reviewing client logs, it would be helpful to see what version of teamsjs is in use.
Log the version of teamsjs in use when starting
Yes
> Log version on startup

- change/@microsoft-teams-js-b1e62451-f7ad-44d0-b700-d5fe996761f9.json
- packages/teams-js/src/internal/telemetry.ts
- packages/teams-js/src/public/app.ts
Added the teamsjs instance identifier and timestamp to every log line. This will help us debug issues where multiple teamsjs instances are being used (which is an unsupported scenario).
Ensured everything looked right in the logs:
...even in the multi-instance scenario:
Yes
> Added the teamsjs instance identifier and timestamp to every log line

- change/@microsoft-teams-js-81b620f2-8af1-4450-89b0-20600bac843e.json
- packages/teams-js/src/internal/appIdValidation.ts
- packages/teams-js/src/internal/utils.ts
- packages/teams-js/src/private/externalAppAuthentication.ts
- packages/teams-js/src/private/externalAppCardActions.ts
- packages/teams-js/src/private/externalAppCommands.ts
- packages/teams-js/test/internal/appIdValidation.spec.ts
- packages/teams-js/test/internal/utils.spec.ts
- packages/teams-js/test/private/externalAppAuthentication.spec.ts
- packages/teams-js/test/private/externalAppCardActions.spec.ts
- packages/teams-js/test/private/externalAppCommands.spec.ts
- packages/teams-js/test/public/appId.spec.ts
The codebase currently has some duplication in a few areas:
- Multiple different ways of accepting, storing, and validation of app ids
- Multiple (different) ways of identifying the presence of script tags
1. Unify all App Id logic around the `AppId` type -- note: the input parameters for appids unfortunately cannot be changed from `string` to `AppId` at this time since that would be a API-breaking change. 
2. Remove incomplete implementation of HTML entity decoding (since it was missing a lot of other entities) and remove need for such functionality by just looking specifically for encoded script tags (script tag searching was the only function using the entity decoding helper)
3. All related tests that were using a regex to test for a specific substring were updated to be …
> Unify some of the appid code, improve script tag detection and add validation

- apps/teams-test-app/e2e-test-data/meeting.json
This PR disables the E2E test for newer versions of the hostSDK.
> [getMeetingDetailsVerbose] Disable E2E test for newer version of hostSDK

- apps/teams-test-app/e2e-test-data/externalAppCardActionsForCEA.json
- apps/teams-test-app/src/components/privateApis/ExternalAppCardActionsForCEAAPIs.tsx
- change/@microsoft-teams-js-04213847-0138-4547-976c-ae02297702f0.json
- packages/teams-js/src/private/externalAppCardActionsForCEA.ts
- packages/teams-js/test/private/externalAppCardActionsForCEA.spec.ts
1. Added E2E test for externalAppCardActionsForCEA APIs. 
2. Fixed the format issue
<Yes>
<Yes>
<Yes>
> Added E2E tests for externalAppCardActionsForCEA APIs

- apps/teams-test-app/src/components/privateApis/ExternalAppCardActionsAPIs.tsx
- apps/teams-test-app/src/components/privateApis/ExternalAppCardActionsForCEAAPIs.tsx
- change/@microsoft-teams-js-4fe5ca49-b46c-4a6b-b580-bd6035df67e6.json
- packages/teams-js/src/private/externalAppCardActions.ts
- packages/teams-js/src/private/externalAppCardActionsForCEA.ts
- packages/teams-js/src/private/interfaces.ts
- packages/teams-js/test/private/externalAppCardActions.spec.ts
- packages/teams-js/test/private/externalAppCardActionsForCEA.spec.ts
> Revert the changes of moving common data models to interface file for externalAppCardAction(ForCEA) APIs to avoid the breaking changes.
> Revert the changes of moving common data models to interface file for externalAppCardAction(ForCEA) files

- tools/cli/preRelease.js
1. Currently the preRelease script is looking for the CDN hash manifest in a folder that no longer contains it. Moving the pathing to resolve to the new one that we added for the rollup release.
> Fixed CDN hash bug in path of preRelease script

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-04213847-0138-4547-976c-ae02297702f0.json
- change/@microsoft-teams-js-120060c9-a050-4da3-a0a5-2323e3a78d10.json
- change/@microsoft-teams-js-3c6d20f0-0715-499f-8835-457526329b67.json
- change/@microsoft-teams-js-4c2cf5b3-6661-4e5f-925b-7a8a49ad9d91.json
- change/@microsoft-teams-js-4fe5ca49-b46c-4a6b-b580-bd6035df67e6.json
- change/@microsoft-teams-js-75e3c524-ba26-4b6a-b01b-9a1f0e315d91.json
- change/@microsoft-teams-js-81b620f2-8af1-4450-89b0-20600bac843e.json
- change/@microsoft-teams-js-87505803-bfad-44bd-a44d-f2ba244c46ad.json
- change/@microsoft-teams-js-8b361cdc-41c8-48a8-9e4c-cb57a8b80411.json
- change/@microsoft-teams-js-9226f943-a345-4cef-95fe-607b0df82934.json
- change/@microsoft-teams-js-ad734c6e-e931-4790-8795-e2a577ffb281.json
- change/@microsoft-teams-js-b1e62451-f7ad-44d0-b700-d5fe996761f9.json
- change/@microsoft-teams-js-b61435ce-c9da-47bc-9b65-2710406ac8d7.json
- change/@microsoft-teams-js-cee144c2-e3b9-40a5-bb3e-05608280d179.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
- pnpm-lock.yaml
- tools/cli/preRelease.js
Thu, 03 Oct 2024 20:49:08 GMT
- Added support for `externalAppAuthenticationForCEA` capability
- Added support for `externalAppCardActionsForCEA` capability.
- Added logging for current teamsjs instance and timestamps
- Added a Rollup built bundle of Teams-JS
- Added three properties to `ICallDetails`, `originalCallerInfo`, `dialedEntityInfo`, and `callId`, created a new type `ICallParticipantIdentifiers`, and deprecated the `originalCaller` and `dialedEntity` properties
- Updated `pages.navigateToApp` to now optionally accept a more type-safe input object
- Added logging for version on startup
- Updated logging for messages to be …
> Prep for Release 2.29.0

- change/@microsoft-teams-js-0ee21e72-d019-4626-8510-28cc59a46290.json
- packages/teams-js/src/public/app.ts
- packages/teams-js/src/public/publicAPIs.ts
The documentation didn't really explain how or why one would use the `validOrigins` parameter to `initialize` so I updated it to clarify usage.
> Update docs to clarify usage of validOrigins parameter on initialize call

- apps/teams-test-app/src/App.css
- apps/teams-test-app/src/pages/TestApp.tsx
> This PR addresses a long-standing macOS UI testing issue caused by the Mac version of the SDK being unable to test against the latest TeamsJS version. The problem arises from the large number of visible sections and limitations of XCUI applications, which do not display sections during UI tests beyond a certain threshold. To resolve this, we introduce a grouped mode that loads only specific sections in the test app and along with that we also add the groupedMode parameter in the url. We can access the specific section using ?groupedMode=<section_name>.
> 1. Introduction of Grouped Mode: Added a button to toggle between default mode (showing all sections) and grouped mode, which allows loading specific sections dynamically.
> 2. Dynamic Section Loading: Refactored the component structure …
> Fix macOS UI issue by introducing grouped mode to load specific section in test app

- change/@microsoft-teams-js-c869bc74-fed2-4af2-9795-312fd14d1218.json
- packages/teams-js/src/artifactsForCDN/validDomains.json
1. Updated `edgeapi.freya.svc.cloud.microsoft` endpoint to `chatuxmanager.svc.cloud.microsoft`
> Updating edgeapi endpoint to chatuxmanager

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-0ee21e72-d019-4626-8510-28cc59a46290.json
- change/@microsoft-teams-js-1aa01dc3-75e3-43e1-8fa9-36340595f99d.json
- change/@microsoft-teams-js-286cc515-1cef-4d54-9af6-d869e00d96c9.json
- change/@microsoft-teams-js-c84a8a6a-9440-4ec4-a930-b9e6921a4932.json
- change/@microsoft-teams-js-c869bc74-fed2-4af2-9795-312fd14d1218.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
From the changelog:
Mon, 21 Oct 2024 18:11:30 GMT
- Updated `copilot.eligibility.getEligibilityInfo` to be async and get the eligibility info from the host if it is not already available.
- Updated edgeapi.freya.svc.cloud.microsoft to chatuxmanager.svc.cloud.microsoft
- Updated edgeapi endpoint from `edgeapi.svc.cloud.microsoft` to `edgeapi.freya.svc.cloud.microsoft` in valid domains list. Added `work.bing.com` to valid domains list.
- Clarified usage for `validMessageOrigins` parameter on `app.initialize` in documentation
> Prep release 2.30.0

- apps/teams-test-app/src/App.tsx
Though all of API calls from testing host will be string format, but listener in test app will listen to all of messages, including response from Web Host SDK. Some of responses are in JSON format. It does no harm for testing, but in case people want to know what it is, I added one line to stringfy those kind of data.
> Added JSON.Stringfy function to convert potential json format msg

- apps/teams-test-app/src/components/TeamsCoreAPIs.tsx
In cypress is it is complicated to test an alert that comes from an iframe. Instead of checking for the alert, we check the text in the box. OR we verify caching by making sure iframe does or does not exist in the dom.
> Change alert to text in the box for e2e testing

- azure-pipelines.yml
- tools/yaml-templates/ios-test.yml
Migrate image running by iOS E2E test from macOS-12 to macOS-14-arm64. Change Xcode, simulator, simulator OS versions based on what new image provided in YML file.
> Migrate iOS E2E testing to image MacOS-14-arm64

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-0ad87803-4839-4de4-8f4f-5bbd48980fde.json
- change/@microsoft-teams-js-0dfea369-ca36-49f5-87e9-4f2825d7c380.json
- change/@microsoft-teams-js-1596e2e2-4f59-44d4-8689-0de41698434f.json
- change/@microsoft-teams-js-2f4e536b-d22a-4105-903c-024e6d9a51a5.json
- change/@microsoft-teams-js-3257d0cf-4640-4de7-b7a6-c117e6c4ccbf.json
- change/@microsoft-teams-js-35af1950-5f26-4ffe-8c68-6ca569870710.json
- change/@microsoft-teams-js-406034a0-0f82-4635-b418-c6ad95bfa0b0.json
- change/@microsoft-teams-js-42d39be6-18d9-4619-ab76-a1360275873c.json
- change/@microsoft-teams-js-55399555-fdb1-4b61-accb-5ebed9246795.json
- change/@microsoft-teams-js-557212a2-b959-475f-bba1-df08e64a7c81.json
- change/@microsoft-teams-js-5dd2d28d-3280-4f21-9ef4-572a6de474f6.json
- change/@microsoft-teams-js-6a4a3b9d-97ef-4dfe-a79c-ea0f69b290d9.json
- change/@microsoft-teams-js-6c75876b-1e4b-4ca0-a7a2-d94204eae9a7.json
- change/@microsoft-teams-js-7805c977-c283-42e2-9e37-bbbf82239930.json
- change/@microsoft-teams-js-895f30e4-4c57-4645-814a-49fe2ae8e9b8.json
- change/@microsoft-teams-js-9ba1fbf7-8871-42bc-8f38-03e1c4825210.json
- change/@microsoft-teams-js-a4e76c3e-7ab3-4dd4-9a24-c0c909040b64.json
- change/@microsoft-teams-js-b23ef57f-9184-4659-93c8-48d862788dd3.json
- change/@microsoft-teams-js-c23ceb97-a527-4ef9-8714-f4beff7446ec.json
- change/@microsoft-teams-js-d467d82e-564d-4b25-b975-b8d07a91a647.json
- change/@microsoft-teams-js-ee20dd5c-0ffc-4208-bd96-53224dc7e062.json
- change/@microsoft-teams-js-f6526430-887f-46bc-bfb4-8c9750214364.json
- change/@microsoft-teams-js-f9ac3559-b7e4-4cdd-bff9-54aecd663d48.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
Wed, 13 Nov 2024 19:22:01 GMT
- Made the `appInstallDialog`, `authentication`, `barCode`, `calendar`, `call`, and `clipboard` files treeshakable
- Made `externalAppAuthenticationForCEA.ts` throw `Error` objects instead of `SdkErrors`.
- Made the `app`, `appInitialization`, and `settings` files treeshakable
- Made the `copilot`, `hostEntity`, `messageChannels`, and `teams` files treeshakable
- Made the `appEntity`, `conversations`, `copilot`, `externalAppAuthentication`, `externalAppAuthenticationForCEA`, `externalAppCardActions`, `externalAppCardActionsForCEA`, `externalAppCommands`, `files`, `logs`, `meetingRoom`, `notifications`, `otherAppStateChange`, and `remoteCamera` files treeshakable
- Made the `meeting`, `profile`, sharing`, and `stageView` files treeshakable
- Replaced `Buffer` …
> Prepare release 2.31.0

- azure-pipelines.yml
These jobs are failing near-deterministically due to issues outside of our control having to do with the Mac image we've been given. Disabling these for now, and will open a bug for someone to re-enable them once they can be made stable.
Disabled 2 iOS E2E jobs in the pipeline
None
No
No
No, change doesn't affect code we ship to customers
> Disable iOS E2E pipelines until they can be made stable

- change/@microsoft-teams-js-0bfc106c-dcbd-4193-b604-49700784ee6d.json
- packages/teams-js/src/public/nestedAppAuth.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/public/nestedAppAuth.spec.ts
- packages/teams-js/test/public/runtime.spec.ts
The current IsNAAChannelRecommeded function that app developers will call, checks the value of the isNAAChannelRecommended flag in the runtime config. For hosts which are using the host sdks, the config object is sent during app initialization which sets the value of the is IsNAAChannelRecommeded flag in the runtime config correctly. For legacy Teams (i.e. Teams app not using the host SDK), the config object is not sent during the app initialization. The runtime config object is created on the JS SDK side. Therefore, a solution is required to return the value of the isNAAChannelRecommended correctly for the legacy Teams …
> Supporting isNAAChannelRecommended flag for Legacy Teams Mobile Scenario

- .vscode/settings.json
- change/@microsoft-teams-js-bd2fddc6-24a2-4ffc-a0eb-b9c463513e20.json
- packages/teams-js/src/public/dialog/adaptiveCard/adaptiveCard.ts
- packages/teams-js/src/public/dialog/adaptiveCard/bot.ts
- packages/teams-js/src/public/dialog/dialog.ts
- packages/teams-js/src/public/dialog/update.ts
- packages/teams-js/src/public/dialog/url/bot.ts
- packages/teams-js/src/public/dialog/url/parentCommunication.ts
- packages/teams-js/src/public/dialog/url/url.ts
The `dialog` capability and all subcapabilities are no longer in beta. This change updates the documentation to reflect that by removing all `@beta` tags.
Yes
> Remove @beta tag from all dialog capability functions

- apps/teams-test-app/src/components/NestedAppAuthAPIs.tsx
> Add three new API sections to the Teams test app for UI testing:
> 1. SendMessageToNestedAppAuthBridge - Send a NAA message to the nested app auth bridge.
> 2. SendMessageToTopWindow - Send NAA message to the top window.
> 3. AddChildIframeSection - Add a child nested iframe, which can also call APIs 1 and 2.
1. Added SendMessageToNestedAppAuthBridge, SendMessageToTopWindow, AddChildIframeSection in NestedAppAuthAPIs.tsx
1. Yes, locally using SDK UI testing framework. 
N/A
N/A
<Yes/No>
> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the …
> Add Nested App Auth API sections to the teams test app

- azure-pipelines.yml
- tools/yaml-templates/ios-test.yml
It seems like VM providers have finished rolling back and forth and everything is in stable now. Thus, we would like to re-enable E2E testing pipelines and keep monitoring them.
> Re-enable iOS E2E Testing pipelines

- apps/teams-test-app/src/components/NestedAppAuthAPIs.tsx
- apps/teams-test-app/src/public/naa_childIframe.html
> Currently, the same test app is displayed within a nested iframe, which can lead to issues like timeouts for mobile SDKs during testing. Additionally, it may introduce future complications due to initialization steps. This PR removes the dependency on the parent app and replaces it with a custom iframe featuring a minimal design. The custom iframe includes two buttons: one for sending messages to the bridge and another for sending messages to the top window.
1. Added naa_childIframe.html.
2. Updated the nested child iframe source to naa_childIframe.html.
Locally with other SDKs
N/A
N/A …
> Add custom child iframe in teams test app for nested app auth e2e tests

- tools/yaml-templates/ios-test.yml
**Summary**
This pull request addresses an issue with the PublishBuildArtifacts@1 task in the pipeline by zipping the logs directory before publishing. And we changed the logic to only publishing zip files for debugging purpose when E2E test failed.
Based on our observations and experience, we can confirm that when we use new version of Xcode, after E2E test completes and if there is any error, it will create a lot of files all under .xcresult as below (.xcresult has a lot of hidden files on MacOS) 
```
`DebugLogs/output.xcresult/Debug description for `StaticText (Elements matching predicate 'value CONTAINS "Error Error InvalidAuthUrl"')`_1_533C9087-ED7E-4A94-8048-26DD268E2FBA.txt`
```
When we try to publish the artifacts, the task will scan each of them and they may have problems …
> Fix publishBuildArtifact task issue

- change/@microsoft-teams-js-81b04f65-2e91-4e2e-b96e-a861166d5c65.json
- packages/teams-js/src/private/index.ts
A partner team ran into an issue with trying to upgrade to the latest version. The latest version does not have `ConversationResponse` explicitly exported from the index file, so it now must be referenced through `MicrosoftTeams.conversations.ConversationRequest` instead of what they were previously using `MicrosoftTeams.ConversationResponse`. This is a back-compat bug as we don't want any breaking api changes with the treeshaking updates, so I explicitly added `ConversationResponse` to the private index file to facilitate the old reference support.
> noahdarveau/ export conversationResponse

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-07829a41-a760-48a1-a793-df938ea61c13.json
- change/@microsoft-teams-js-0bfc106c-dcbd-4193-b604-49700784ee6d.json
- change/@microsoft-teams-js-81b04f65-2e91-4e2e-b96e-a861166d5c65.json
- change/@microsoft-teams-js-bd2fddc6-24a2-4ffc-a0eb-b9c463513e20.json
- change/@microsoft-teams-js-c78bd0b1-8288-4e22-bd89-252a1218ba5d.json
- change/@microsoft-teams-js-d39b2214-2e37-4bce-8c44-654fc1465efd.json
- change/@microsoft-teams-js-dfb061f5-be4b-47db-98cf-4c1975538b3d.json
- change/@microsoft-teams-js-fc4a8f34-92ca-48dc-9c74-c84d8eed6a89.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
- pnpm-lock.yaml
- Added optional `FeatureSet` field to `AppEligibilityInformation` interface
- Added `store` capability that will enable user to open several types of app store dialogs.. The capability is still awaiting support in one or most host applications. To track availability of this capability across different hosts see https://aka.ms/capmatrix
- Added `nestedAppAuth` capability against a new client version `2.1.1` to support isNAAChannelRecommended for Teams Mobile
- Added `ConversationResponse` to explicit named exports for back-compat
- Resolved an issue with non-necessary polyfills being included
- Backed out `Buffer` removal changes
- Removed `@beta` tag from all functions on `dialog` capability (and all subcapabilities)
> Setting up for release 2.32.0

- tools/yaml-templates/ios-test.yml
As title says, this PR is to skip failure on task to install XCTestHTMLReport and only publish result to artifact when the task succeeded, considering we encounter the error as below every day. Pipeline will be considered to be successful even if XCTestHTMLReport fails to be installed since we have a `continueOnError` tag for that.
```dyld[7806]: terminating because inserted dylib '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' could not be loaded: tried: '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e')), 
'/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (no such …
```
> Skip failure on task to install XCTestHTMLReport and only publish result to artifact when the task succeeded

- change/@microsoft-teams-js-6f5afb78-da58-46be-a695-164d19695294.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/hostToAppTelemetry.ts
- packages/teams-js/src/internal/messageObjects.ts
- packages/teams-js/src/internal/telemetry.ts
- packages/teams-js/src/public/uuidObject.ts
- packages/teams-js/test/internal/communication.spec.ts
- packages/teams-js/test/internal/utils.spec.ts
- packages/teams-js/test/public/app.spec.ts
- packages/teams-js/test/utils.ts
Moved uuidObject.ts from internal to public folder in preparation for exporting it.
The UUID type needs to be exported as part of this PR: https://github.com/OfficeDev/microsoft-teams-library-js/pull/2654/files, and in the spirit of small, isolated changes, I'm doing the move separately from the logical changes in the file that will come as part of the other PR.
1. Move uuidObject.ts from internal to public.
2. Update import references.
1. Unit tests pass.
No, this is just a refactor.
No
Yes
[Added customTelemetry subcapability under copilot](https://github.com/OfficeDev/microsoft-teams-library-js/pull/2654/files)
> Moved uuidObject.ts from internal to public folder in preparation for exporting it

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-05b6fda8-1215-45ac-b8c5-338fe7d7f77e.json
- change/@microsoft-teams-js-355651b0-c6d4-47bb-b923-426b9a9a3bae.json
- change/@microsoft-teams-js-4ed021f2-aea4-4a41-84f5-1d1688d7f234.json
- change/@microsoft-teams-js-6f5afb78-da58-46be-a695-164d19695294.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
Result of `node tools/cli/prerelease.js` command
- Added `customTelemetry` capability under `copilot` to send app loading data to the host.
- Explicitly use browser implementation of `debug` package to resolve polyfill issue.
- Moved uuidObject.ts from internal to public folder in preparation for exporting it.
> 2.33.0 Prerelease

- change/@microsoft-teams-js-88f21fb3-ced0-4b78-9e79-51cb73b00a0f.json
- packages/teams-js/src/public/mail/handoff.ts
This PR updates the validateEmails function from a boolean return type to void. The validateEmails function will no longer return a value, but it will throw an error if any of the email addresses are invalid.
> Updating `validateEmails` function from boolean to void

- change/@microsoft-teams-js-23b4de1d-348c-4748-90ac-78b4fa7158c7.json
- packages/teams-js/src/public/authentication.ts
The `authentication.notifySuccess` function did not explicitly discuss secure usage guidance and this PR adds it.
Separately, I am working with the docs team to get the prose documentation pages ([here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab) and [here](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication)) updated to be more explicit about this.
The final docs now look like this, after feedback from @JoshuaPartlow:
This is obviously the local generation of the docs -- they will be formatted slightly differently on the official site.
> Update authentication.notifySuccess function documentation with secure usage guidance

- apps/teams-test-app/src/App.tsx
- apps/teams-test-app/src/components/AppAPIs.tsx
This change is a preparation for App Initialization E2E test on cache app in Web Host SDK. We would like to mock the scenarios when cache app [call / doesn't call] `app.notifySuccess` after it comes out from cache mode. Thus, we need to make this change to make sure we have option under `customInit` test mode.
1. `onResumeHandler` is used for cache only so no E2E test should be broken because of this change
> [Please Review] Test App calls `App.notifySuccess` automatically within `RegisterOnResumeHandler` if it is not in `customInit` mode

- azure-pipelines.yml
- tools/yaml-templates/android-test.yml
- tools/yaml-templates/build-app-host.yml
- tools/yaml-templates/ios-test.yml
**What is codeql, and what the persistent issues it has currently?**
From what I understand in a briefly way,  it is static analysis tool, runs on source codes for all kind of languages, and also traces the build process during to build, to capture any security  vulnerability issues. It creates a DB during its run, which I believe records the scan result, and the DB will be uploaded in the pipeline to be source of different reporting/dashboards.
CodeQL currently has some issues arm64 macos image, which has been known for a while and in the back of codeQL team. This is not super clear what is the issues to me, and there is an …
> Disable CodeQL from pipeline level and add it in job level

- change/@microsoft-teams-js-eef39838-66eb-4b2d-8333-7b4194fb0b47.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/messageObjects.ts
- packages/teams-js/test/internal/communication.spec.ts
- packages/teams-js/test/utils.ts
This pull requests add a new field to tag messages proxied from child, in order for the Host to differentiate between parent messages and child originated ones.
Yes
No
Yes
> Add field to tag proxied messages.

- change/@microsoft-teams-js-136faa15-4005-4e32-8931-382db3d3ab0f.json
- packages/teams-js/src/public/app/app.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/test/public/app.spec.ts
Adding the `appId` and `manifestVersion` to `AppInfo` so app can get  `appId` and `manifestVersion`  from `getContext()` API.
1. Added `appId?: AppId`
2. Add `manifestVersion?: string`
> [Task] Programmatically access the "real" App ID and Manifest Version 

- apps/typed-dependency-tester/package.json
There was a bug with the typed-dependency-tester that was causing windows runs to fail as it wasn't copying all of the files properly. I had to add the `/E` flag to enable recursive copying. I also updated the path so as to not copy over unnecessary files.
> noahdarveau/windows typed-dependency-tester fix

- change/@microsoft-teams-js-92414722-9f1f-44c2-8b05-2f4c5655b02d.json
- packages/teams-js/src/internal/childCommunication.ts
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/communicationUtils.ts
- packages/teams-js/src/internal/handlers.ts
- packages/teams-js/src/internal/pagesHelpers.ts
- packages/teams-js/src/private/privateAPIs.ts
- packages/teams-js/src/public/pages/config.ts
- packages/teams-js/test/internal/childCommunication.spec.ts
- packages/teams-js/test/internal/communication.spec.ts
- packages/teams-js/test/internal/communicationUtils.spec.ts
- packages/teams-js/test/private/privateAPIs.spec.ts
- packages/teams-js/test/utils.ts
This pull request refactors all the child communication to an isolated module. Although this allows for clear and independent separation for how child proxying works, this is mostly done so in a next PR we can tree shake this module with a feature flag. There is no particular functionality change introduced in this pull request.
1. Refactor child communication to an isolated module.
2. Added proper unit tests to detail how child proxying and child event relaying works.
1. Ran set of tests.
2. Ran child app to see if everything worked as usual.
Yes
No
Yes
A follow-up PR will make add a feature flag for using this module, which would then make it so all child proxying code is removed in the final bundle if not needed.
> Refactor child communication to own module

- apps/teams-test-app/src/components/privateApis/ExternalAppAuthenticationForCEAAPIs.tsx
- change/@microsoft-teams-js-b91fc37f-8189-4031-aec5-bedd6699cba1.json
- packages/teams-js/src/private/externalAppAuthenticationForCEA.ts
- packages/teams-js/test/private/externalAppAuthenticationForCEA.spec.ts
This PR adds "authId" and "connectionName" parameters to the `ExternalAppAuthenticationForCEA.authenticateWithSSOAndResendRequest` API. These parameters are required from the app to complete the original request.
1. Add "authId" and "connectionName" parameters to the `authenticateWithSSOAndResendRequest` function in `packages/teams-js/src/private/externalAppAuthenticationForCEA.ts`.
1. Tested against corresponding changes in the host SDK.
Yes, updated existing tests to use new parameters
No, …
> Add "authId" and "connectionName" properties to ExternalAppAuthenticationForCEA.authenticateWithSSOAndResendRequest

- change/@microsoft-teams-js-ee0a1dbc-9fd6-4e2d-82bd-bc431674f89e.json
- packages/teams-js/src/private/hostEntity/hostEntity.ts
- packages/teams-js/test/private/hostEntity.spec.ts
Add two new enum values for base and streaming Townhalls to support Townhall app filtering.
1. Add new AppTypes enums
> Add two new AppType enums to support Townhall App Filtering

- apps/teams-test-app/src/components/privateApis/ExternalAppAuthenticationForCEAAPIs.tsx
- change/@microsoft-teams-js-12f113ad-4cdf-4b83-a246-5b552959a6fa.json
- packages/teams-js/src/private/externalAppAuthenticationForCEA.ts
- packages/teams-js/test/private/externalAppAuthenticationForCEA.spec.ts
These parameters were recently added to the `authenticateWithSSOAndResendRequest` API. They are required on `authenticateWithSSO` as well. This PR adds `authId` and `connectionName` parameters to `externalAppAuthenticationForCEA.authenticateWithSSO`.
These parameters were recently added to the `authenticateWithSSOAndResendRequest` API. They are required on `authenticateWithSSO` as well. This PR adds `authId` and `connectionName` parameters to `externalAppAuthenticationForCEA.authenticateWithSSO`.
1. Validated against corresponding changes in host SDK
Yes
No
Yes
> Add `authId` and `connectionName` parameters to `externalAppAuthenticationForCEA.authenticateWithSSO`

- change/@microsoft-teams-js-e4e92ce6-5c08-405d-9345-a7464db00ecd.json
- packages/teams-js/src/internal/childCommunication.ts
- packages/teams-js/src/public/featureFlags.ts
- packages/teams-js/src/public/index.ts
- packages/teams-js/test/internal/childCommunication.spec.ts
- packages/teams-js/test/private/privateAPIs.spec.ts
- packages/teams-js/test/public/pages.spec.ts
- packages/teams-js/test/utils.ts
This pull request aligns with the on-going effort of removing and deprecating child proxying in teams-js. This pull request disables child proxying by default and makes it so any app must opt-in through the `activateChildProxyingCommunication` feature flag function.  Additionally, a security issue which could possibly leak data was fixed and also guarded through a feature flag in case any app still needs this pattern which is unlikely.
Although theoretically this would be considered a "breaking change", I find it unreasonable to bump to `3.0.0` as this is mostly considered a security fix that most apps won't have to do anything. As such, will leave the changefile as minor as the pattern can still be used through feature flags.
1. Added scaffolding for build and runtime feature flags in …
> Disable child proxying by default and add feature flag scaffolding

- apps/teams-test-app/e2e-test-data/nestedAppAuth.json
- apps/teams-test-app/src/components/NestedAppAuthAPIs.tsx
- change/@microsoft-teams-js-09be1eb0-4ad8-4284-9bbb-7092ddd0cb2d.json
- packages/teams-js/src/public/nestedAppAuth.ts
- packages/teams-js/test/public/nestedAppAuth.spec.ts
> Added getParentOrigin so that the app can read its parent origin. TeamsJS already maintains the parent origin internally but never exposed it to the app, as it was never required. However, with the deeply nested auth feature, teamsJS need to expose this API to the parent so it can pass the origin to the child app. The child app can then use this origin to initialize the standalone nested app auth bridge. 
> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to- …
> Added `getParentOrigin` API to read the parent origin for nested app auth

- change/@microsoft-teams-js-1f320a4f-42fe-4144-919b-be5cb7cb3055.json
- packages/teams-js/src/internal/nestedAppAuthUtils.ts
- packages/teams-js/test/internal/communication.spec.ts
> This change skips the default nestedAppAuthBridge injection when the app is running inside a nested iframe (i.e., not the top-most window).
> While TeamsJS does support bridge injection into iframes, the nested app auth flow fails in cross-origin scenarios. Although this issue could be addressed, TeamsJS is already on the path to deprecating parent-child communication, making such fixes less sustainable long-term.
> To avoid these issues, we now skip the default nestedAppAuthBridge injection when the app is running inside a nested iframe. This ensures that nested apps can explicitly use the standalone nested app auth bridge, …
> Disable default nested app auth bridge injection for nested child app

- apps/teams-test-app/e2e-test-data/nestedAppAuth.json
> Web SDK pipeline is failing because it attempts to fetch a specific version of TeamsJS before initiating the test. A published TeamsJS version that includes this change should be defined, but since TeamsJS hasn't been published yet, the UI test is being removed for now. It will be added back later once the correct version is available.
> Previous change --> https://github.com/OfficeDev/microsoft-teams-library-js/pull/2757
1. Remove ui test in `nestedAppAuth.json`.
1. <Step 1>
2. <Step 2> …
> Fix pipeline UI test failure caused by newly added `getParentOrigin` API

- apps/teams-test-app/e2e-test-data/nestedAppAuth.json
- apps/teams-test-app/src/components/NestedAppAuthAPIs.tsx
- change/@microsoft-teams-js-291c03f0-c69f-4b98-b14a-e8ae1f8da29d.json
- packages/teams-js/src/public/nestedAppAuth.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/public/nestedAppAuth.spec.ts
> Added API to get the value of isDeeplyNestedAuthSupported from the runtime object. This is required by a nested child app to determine if deeply nested auth is supported. The parent app can read this value and pass it on to its child app.
1. Added `isDeeplyNestedAuthSupported` in Runtime V4.
2. Added UI test in `nestedAppAuth.json`
3. Added unit tests in `nestedAppAuth.spec.ts`
4. Added `CheckIsDeeplyNestedAuthSupported` section in teams test app.
5. Added `isDeeplyNestedAuthSupported()` method in `nestedAppAuth.ts` to get value of isDeeplyNestedAuthSupported from runtime object
1. Pull the changes. 
2. Run the teams test app. …
> Added support for `isDeeplyNestedAuthSupported` to check if deeply nested auth is supported.

- apps/teams-test-app/e2e-test-data/nestedAppAuth.json
- apps/teams-test-app/src/components/NestedAppAuthAPIs.tsx
- change/@microsoft-teams-js-01acb692-27b0-4d62-97cb-4cc57a68dbe9.json
- packages/teams-js/src/public/nestedAppAuth.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/public/nestedAppAuth.spec.ts
> This PR introduces a new capability: canParentManageNAATrustedOrigins. This capability checks whether the parent app has the ability to manage its list of trusted child origins specifically for Nested App Auth (NAA) 
> The goal of this change is to support scenarios where the parent app needs to programmatically determine if it can configure or update the trusted origins of child , enhancing flexibility and control in NAA flows.
1. Added `canParentManageNAATrustedOrigins` in `runtime.ts`
2. Added `canParentManageNAATrustedOrigins()` in `nestedAppAuth.ts`
3. Added unit test
1. Yes, locally. 
Will add later once web SDK release …
> Add `canParentManageNAATrustedOrigins` capability  to check if the parent can manage its list of trusted child origin

- apps/teams-test-app/src/components/NestedAppAuthAPIs.tsx
- change/@microsoft-teams-js-a4a5bbd3-a23b-42e1-9116-d8c0d890969c.json
- packages/teams-js/src/internal/telemetry.ts
- packages/teams-js/src/public/nestedAppAuth.ts
- packages/teams-js/test/public/nestedAppAuth.spec.ts
> This PR adds two new public APIs under the nestedAppAuth capability:
>1. addNAATrustedOrigins(appOrigins: string[])
>2. deleteNAATrustedOrigins(appOrigins: string[])
>These APIs allow a top-level parent app to manage its list of trusted child origins for Nested App Auth (NAA). They are gated by platform support, and the runtime capability flag canParentManageNAATrustedOrigins() must return true in order for these APIs to be used.
1. Added `AddTrustedOrigin` and `DeleteTrustedOrigin ` UI section in teams test app.
2. Exported method `addNAATrustedOrigins` and `deleteNAATrustedOrigins` in `nestedAppAuth.ts`
3. Added unit tests in `nestedAppAuth.spec.ts`
4. Added `NestedAppAuth_ManageNAATrustedOrigins` in `telemetry.ts`
5. 
1. Pulled the latest changes and built the library locally.
2. Ran …
> Add support for manageNAATrustedOrigins API

- change/@microsoft-teams-js-96cc4022-2f5e-470e-b7b6-670472eb2f70.json
- package.json
- packages/teams-js/src/internal/communication.ts
- packages/teams-js/src/internal/nestedAppAuthUtils.ts
- packages/teams-js/src/private/nestedAppAuth/nestedAppAuthBridge.ts
- packages/teams-js/src/public/nestedAppAuth.ts
- packages/teams-js/test/internal/communication.spec.ts
> This PR includes minor NAA updates:
1. Added the apiVersion tag to the NAA request.
2. Added a version constant to track the bridge version.
3. Removed the isNAAChannelRecommended check in the isDeeplyNestedAuthSupported API.
1. Added the apiVersion tag to the NAA request in both the default bridge and the Nested App Auth standalone bridge.
2. Removed the …
> Added `apiVersion` tag in NAA request and removed `isNAAChannelRecommended` check in `isDeeplyNestedAuthSupported` api

- azure-pipelines.yml
The PR pipeline is currently failing on the SDLSources step because it cannot access a required resource in ADO. I'm not entirely sure why yet, but switching to the "Unofficial" 1ES pipeline template has resolved this issue. The Unofficial template is to be used for PR builds anyway, so even if it didn't resolve the issue we should make this change.
1. Switch PR pipeline to Unofficial 1ES pipeline template
2. Switch to windows-latest runner image
1. Tested pipeline with new settings
No, pipeline changes only
No
No, pipeline changes only
Our PR and build pipelines use the same yml, so we will have to create a new file for the build …
> Fix PR pipeline by switching to Unofficial template

- tools/releases/build-release.yml
- tools/releases/build.yml
The teams-js PR pipeline and release build pipeline currently share a yml definition (azure-pipelines.yml). Because we moved the PR pipeline from the Official 1ES template to the Unofficial template, we need to create a new release build definition that uses the Official 1ES template. This PR introduces a new release build pipeline, which was copied from the PR pipeline but has the E2E tests steps removed, as the E2E tests in the PR pipeline cover any changes checked in to teams-js.
1. Introduce new build pipeline which extends the Official 1ES pipeline template and does not run the teams-js E2E tests. This pipeline will generate …
> Create new release build pipeline definition

- apps/teams-test-app/src/components/privateApis/CopilotAPIs.tsx
- change/@microsoft-teams-js-3bf442f2-393a-43fd-9d52-d09851ea25d4.json
- packages/teams-js/src/private/copilot/eligibility.ts
- packages/teams-js/test/private/copilot.spec.ts
New `forceRefresh` argument for the get eligibility information API for forcing a refresh of the eligibility information.
1. Add new argument to the `getEligibilityInfo` API.
1. Ran unit tests.
2. Tested in testing environment.
Yes
No
Yes.
> Added force refresh parameter to get eligbility info API.

- package.json
- tools/releases/build-release.yml
This resolves 2 issues on the build pipeline:
1. The package size of the tree shaken `{ app, authentication, pages }` app exceeds the limit by 4 bytes. I'm not sure where this comes from, since it's using the exact same steps as the PR pipeline, where the build does not exceed the limit.
2. The release pipeline is still blocked by a bug affecting the SDL steps on the Official 1ES template. Switching to the Unofficial template generates a warning but not an error, so we'll be able to temporarily use the Unofficial template just to unblock releases.
Alternatively, instead of making this change, we could continue running the build …
> Unblock release pipeline (temporary fix)

- change/@microsoft-teams-js-3a3fbb36-90e2-4d00-bb1e-7633a46f3f8c.json
- packages/teams-js/src/public/nestedAppAuth.ts
> This PR removes the Beta tag from the nestedAppAuth.isNAAChannelRecommended API. The API has been adopted and is already being used by partners in their production environments without issues. Based on this proven stability, we are promoting it from beta to a fully supported API.
1. Removed the Beta tag annotation from isNAAChannelRecommended API
1. Confirmed no functional changes in the API implementation
No – The functional logic of the API is unchanged. Existing tests already cover the necessary scenarios.
NA
Yes
> Remove `Beta` tag from nestedAppAuth.isNAAChannelRecommended API

- change/@microsoft-teams-js-06b44e75-5613-4594-a024-dfb68a5d7a05.json
- packages/teams-js/src/internal/dialogHelpers.ts
- packages/teams-js/src/private/copilot/copilot.ts
- packages/teams-js/test/public/dialog.spec.ts
- packages/teams-js/test/public/tasks.spec.ts
Unblocked apps on Mobile to call `dialog.url.submit` from dialog by allowing this API from `FrameContext.content`.\nThere is a bug in Teams mobile that returns `frameContext.content in dialog instead of `frameContext.task`. Once the bug is fixed, this change will be reverted.
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no …
> Unblock apps to call dialog.url.submit in mobile

- change/@microsoft-teams-js-96be3430-7bd4-4a40-8554-4be120a97747.json
- package.json
- packages/teams-js/src/public/app/app.ts
- packages/teams-js/src/public/constants.ts
- packages/teams-js/src/public/index.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/test/public/app.spec.ts
Added `renderingSurface` property to `{app.Page.Context}` capability. The `Renderingsurfaces' enum for this property only contains 'copilotSidePanel' for now, but in future more values will be added.
This PR increased the teams-js size bundle size from 57.204Kb to 57.33kb. The size increase is justified as we are adding new code to app.ts file. This change does not break the tree shakability.
> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using- …
> Added `renderingSurface` property to `{app.Page.Context}`

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-80176c7c-66f8-45f3-9112-36b5c735ad45.json
- change/@microsoft-teams-js-ade231c1-27a2-4670-b268-bdfc0daa5b0a.json
- change/@microsoft-teams-js-e51a0655-ec42-4622-baea-265ada0da3db.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
- pnpm-lock.yaml
Prepare release 2.39.0
- Added `{copilot.sidePanel}` capability that will help copilot to receive more context aware data from the hosts. The capability is still awaiting support in one or most host applications. To track availability of this capability across different hosts see https://aka.ms/capmatrix
- Added a new client version `2.1.2` to support isDeeplyNestedAuthSupported for Teams Mobile legacy code
> Prerelease 2.39.0

- change/@microsoft-teams-js-8a2e274f-36a6-4e8e-a1aa-c56ae77741c6.json
- packages/teams-js/src/private/nestedAppAuth/nestedAppAuthBridge.ts
- packages/teams-js/test/private/nestedAppAuthBridge.spec.ts
> This PR removes the message source check validation as it's causing issues in teams, but origin validation is still in place to make sure it's receiving the message from the correct origin.
1. Remove source validation in shouldProcessIncomingMessage()
> Yes
N/A
Yes
> Removed message source check but kept origin validation in nested app auth standalone bridge

- change/@microsoft-teams-js-2bb3cac7-5319-4348-9c43-562b8ff6f3d7.json
- package.json
- packages/teams-js/src/internal/validOrigins.ts
- packages/teams-js/test/internal/validOrigins.spec.ts
This PR reduces latency for the app initialization scenario by relying on the local valid domain list before checking the list on the CDN. It also resolves an issue where teams-js was making multiple CDN fetch requests if it tried to access the valid domains list before prefetching completes.
1. `validateOrigin` checks the fallback domain list before using the CDN list if there is no cached list available.
2. `getValidOriginsListFromCDN` will no longer create a new fetch request if one is already in progress.
1. Unit tests added
> Unit tests are required for all changes. If no unit tests were added as part of this change, please …
> Try fallback valid domains list before CDN list

- apps/teams-test-app/src/components/privateApis/CopilotAPIs.tsx
For better testing, the get eligibility information function adds a checkbox input so we can manipulate the argument.
> Added checkbox input for eligibility API

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-2bb3cac7-5319-4348-9c43-562b8ff6f3d7.json
- change/@microsoft-teams-js-392f75e4-a502-4c9f-a4e5-00dd9e1469cf.json
- change/@microsoft-teams-js-83b007e0-f58a-4802-9aa2-834e67ab29ba.json
- change/@microsoft-teams-js-8a2e274f-36a6-4e8e-a1aa-c56ae77741c6.json
- change/@microsoft-teams-js-b5130390-bcee-440c-8e8e-4302dcdf4203.json
- change/@microsoft-teams-js-d08f708f-cfc9-4ef6-9a54-53c055323e8c.json
- change/@microsoft-teams-js-e3e8e355-5779-4e4a-94c3-2fc4b2fa5c83.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
- pnpm-lock.yaml
Mon, 07 Jul 2025 23:19:06 GMT
- Added `contextType` in `TeamsContent` interface to `{copilot.sidePanel}` capability.
- Added `TeamsContent` interface for `{copilot.sidePanel}` capability.
- Removed message source check but kept origin validation in nested app auth standalone bridge
- Added Outlook OCDI domain to validDomains.json
- Updated valid domains CDN fetch logic to prevent duplicate requests.
- Added `responseToEmailId` to `{copilot.sidePanel.DraftEmailContent}` capability.
> prerelease TJS V2.40.0

- apps/teams-test-app/src/components/privateApis/CopilotAPIs.tsx
- change/@microsoft-teams-js-2ec9c5d0-0fdb-45a7-9c57-58e8b99969c9.json
- package.json
- packages/teams-js/src/internal/telemetry.ts
- packages/teams-js/src/private/copilot/copilot.ts
- packages/teams-js/src/private/copilot/view.ts
- packages/teams-js/src/public/constants.ts
- packages/teams-js/src/public/runtime.ts
- packages/teams-js/test/private/copilot.spec.ts
This pull requests adds a new API and two new rendering surface values, to address some copilot accessibility issues.
1. Adds a new API for requesting the host for closing the copilot side panel. This is only available for the copilot app and is intended to be used for adding hotkeys to this behavior inside of copilot.
2. Added two new rendering surface values to cover two additional surfaces used in Teams for rendering copilot.
This was increased as the runtime new value and the two new enum values increased the bundle size by 6 bytes. As these changes are reasonable between the scope of this change, the size limit was increased by 7 bytes to support this.
1. Ran in a test host and validated the service is called appropriately.
2. Ran unit testing and end-to-end tests.
Yes
Yes.
Yes
> Added copilot view API for closing the side panel

- apps/teams-test-app/src/components/privateApis/ExternalAppAuthenticationForCEAAPIs.tsx
…AuthenticateForCEA APIs
This PR covered the change that updated the button names to a unique string for ExternalAppAuthenticateForCEA APIs to enable the e2e tests in mobile platforms
<Yes>
> Change the button text unique to enable iOS E2E tests for ExternalAppAuthForCEA APIs E2E tests

- change/@microsoft-teams-js-05700e50-9d88-4dc6-8803-d5cc7f5f8a2d.json
- package.json
- packages/teams-js/src/public/app/app.ts
- packages/teams-js/src/public/interfaces.ts
- packages/teams-js/test/public/app.spec.ts
Adds the `messageId` property to the app context for task modules launched from Teams messages. Currently, the `parentMessageId` is available, but tasks launched from reply messages do not have access to the ID of the message from which they are launched. Teams will pass this property in task modules.
1. Add `messageId` to `AppInfo` interface and associated logic to convert from legacy `Context` object.
1. Validated with context passed from test host.
Yes
No
Yes
> Add messageId to app context

- tools/yaml-templates/build-test-publish.yml
Build and PR pipelines are failing on the main branch due to unresolved dependencies, but not on PR builds or branches from main with no changes. This PR adds the `--force` flag to the `pnpm install` step in the build yaml to see if we can force the main branch out of its broken state.
1. Add `--force` flag to `pnpm install` step in build yaml
1. Build passed on manual run
> Force install dependencies on build pipeline

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-9425e335-8d41-4714-9bc8-4a401010fdd8.json
- change/@microsoft-teams-js-f0901ccb-dc1d-43c7-a41c-b5d78cd6c9e4.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
Tue, 19 Aug 2025 15:18:35 GMT
- Added `shortcutRelay` capability to support host shortcuts in apps.
> Prerelease 2.43.0

- tools/releases/prod-release.yml
The CDN publishing step failed on the 2.43.0 release pipeline. This PR disables the NPM publishing step in a new branch off of the 2.43.0 release branch so that we can retry the CDN publishing step without failing on the NPM step (which will fail because we've already published 2.43.0 to NPM)
> Disable NPM publish task on 2.43.0 release branch

- apps/teams-test-app/index_cdn.html
- apps/teams-test-app/package.json
- change/@microsoft-teams-js-61a3bc70-d0e9-4213-a977-ec2e082497ea.json
- change/@microsoft-teams-js-b61ec03b-06dd-424e-b03b-050e3620e0ab.json
- packages/teams-js/CHANGELOG.md
- packages/teams-js/README.md
- packages/teams-js/package.json
- pnpm-lock.yaml
Wed, 27 Aug 2025 21:57:44 GMT
- Added optional `Settings` field to `AppEligibilityInformation` interface
> Release 2.44.0

- change/@microsoft-teams-js-e433db29-a743-4e63-8b17-cd1272e4a323.json
- packages/teams-js/src/private/privateAPIs.ts
- packages/teams-js/test/private/privateAPIs.spec.ts
Added `FrameContexts.sidePanel` to `openFilePreview`'s ensureInitialized call to allow for the use in SidePanel.
> noahdarveau/ OpenFilePreview in sidePanel Frame Context
