OfficeDev/microsoft-teams-library-js

src/MicrosoftTeams.ts
test/MicrosoftTeams.spec.ts

Clarify comments for DeepLinkParameters

Clarify comments for DeepLinkParameters

---

src/MicrosoftTeams.schema.json

This should be close to final except for adding permissions when they come. Also made some style changes  and added some missing descriptions. Please validate those as well.

bot commands, app mentions, and incoming webhooks

---

src/MicrosoftTeams.schema.json
src/MicrosoftTeams.ts
test/MicrosoftTeams.spec.ts

Bump version to v0.5

---

src/MicrosoftTeams.schema.json

Update the bot input menu definition, remove unnecessary fields.

Update bot input menu defintion

---

src/MicrosoftTeams.schema.json

Added URL validation for URLs that didn't have them, grammar tweaks, wording clarifications.

URL validation, edits

---

src/MicrosoftTeams.ts

Adding full screen change handler

adding full screen handler for full screen change

---

package.json
src/MicrosoftTeams.ts

1. Upgrade Typescript to 2.5.0
2. Add new API: getTabsInChannels().

Add new API: getTabsInChannels().

---

src/MicrosoftTeams.ts
test/MicrosoftTeams.spec.ts

update version to "1.1-prerel" so I can release to web for partners to access ahead of time.

update version to "1.1-prerel"

---

src/MicrosoftTeams.ts

Updated inline documentation

---

src/MicrosoftTeams.ts

remove type parameters from JSDocs since DefinitelyTyped views them as redundant

remove type parameters from JSDocs since DefinitelyTyped views them as redundant

---

package.json
typings.json

Spoke to Bill and agreed on this change. Please review and merge if OK so we can see the documentation change reflected with this name.

Changing the package name

---

src/MicrosoftTeams.ts

Add scrollbars parameter to window.open

---

src/MicrosoftTeams.ts

These aren't ready for public consumption yet.

Hiding a few members from docs

---

.travis.yml

Looks like deploy step is causing build failure so remove it as of now till we have auto deploy

removing deploy step to fix master build

---

src/MicrosoftTeams.ts
test/MicrosoftTeams.spec.ts

This change adds the chatId field to the context.

Add chatId to the context

---

src/MicrosoftTeams.schema.json

Add a new scope "groupchat" for configurableTabs and bots.

Update manifest schema to support apps in group chat

---

src/MicrosoftTeams.ts

This will add isTeamArchived paramter to get context that will be used to get information about if team is archived or not

adding isteamArchived to context

---

src/MicrosoftTeams.ts
test/MicrosoftTeams.spec.ts

This is followup CR for  https://github.com/OfficeDev/microsoft-teams-library-js/pull/112

Converting new Arrow function to normal functional syntax to make consistent 

---

src/MicrosoftTeams.ts

Description : 
1. Added 2 new Client Types : android, ios
2. Exposed HostClientType
Test Done :
Tested on sample website with android.

HostClientType exposed

---

src/MicrosoftTeams.schema.json

This change also auto-formats the schema using Prettier.

Add configurationUrl field to connector definition

---

src/MicrosoftTeams.ts

Adding app sideload api for 1P

---

src/MicrosoftTeams.ts

Hide namespaces currently under development, hide internal parameters, added a few doc comments.

Updates for docs

---

src/MicrosoftTeams.ts
test/MicrosoftTeams.spec.ts

Adding a new GetChatMembers API to return all members in the chat.

Adding GetChatMembers API

---

package.json

Ignore js file from Jest Unit test

Ignore js file from Jest Unit test

---

src/MicrosoftTeams.ts

adding sharePoint context to client sdk context with any type

adding sharePoint context to client sdk context

---

src/MicrosoftTeams.ts

removing String interface, Looks like we are not using it now.

removing String interface

---

src/MicrosoftTeams.ts
src/internal/constants.ts
src/internal/utils.ts

Motivation: code organizing into separate logical module, improve code quality, reduce maintenance.
I am thinking to organize sdk into 3 sections
1.Internal : code that we don't export
2. private: code that we export as private API
3. public: code that we export as public
This is 1st step here i am organizing code into three above section in same file also moving some internal constants and utils function in separate file.
Followup will move code from MicrosoftTeams.ts file to separate modules/files.

organizing code in internal private and public sdk section

---

src/internal/utils.ts
src/private/privateAPIs.ts
src/public/appWindow.ts
src/public/publicAPIs.ts
src/public/settings.ts

Motivation: We have some api with generic callback where we throw error.
This change refactor that logic into a function.

refactoring generic callback logic

---

src/public/constants.ts
src/public/index.ts
src/public/interfaces.ts
src/public/publicAPIs.ts

Adding SDK API for tab ready success and fail notification
Tab can notify to host if tab is ready to interact or failed with reason.

Adding SDK API for tab ready success and fail notification

---

src/internal/globalVars.ts
src/internal/internalAPIs.ts
src/private/conversations.ts
src/public/interfaces.ts
test/MicrosoftTeams.spec.ts

We received feedback that thread Id can be confusing to developers. Changing that to channel Id.

Change the name from thread Id to channel id

---

src/public/publicAPIs.ts
test/MicrosoftTeams.spec.ts

Enable execute deep Link API in task module

enable exucute deepLink API in task module

---

README.md
package.json
src/internal/constants.ts
test/public/publicAPIs.spec.ts

With CI/CD these are additional changes required on top of master branch inorder to release prod version of npm package.

preparing release 1.5.1

---

README.md
package.json
src/internal/constants.ts
test/public/publicAPIs.spec.ts

* preparing release 1.5.1
* adding integrity

Update master with release 1.5.1 (#269)

---

README.md
package.json
src/internal/constants.ts
test/public/publicAPIs.spec.ts

SDKV1.5.2 changes to master
changes include to support local.teams.microsoft.com as valid host domain

SDKV1.5.2 changes to master

---

src/internal/constants.ts

Update Client SDK to support Office.com

Adding office host domains to valid Origins

---

src/internal/constants.ts
src/internal/globalVars.ts
src/private/conversations.ts
src/private/privateAPIs.ts
src/public/appWindow.ts
src/public/authentication.ts
src/public/constants.ts
src/public/index.ts
src/public/interfaces.ts
src/public/media.ts
src/public/publicAPIs.ts
src/public/settings.ts
src/public/tasks.ts
test/public/media.spec.ts
test/public/publicAPIs.spec.ts

Exporting frameContext as part of getContext API

Exporting frameContext as part of getContext API

---

README.md
package.json
src/internal/constants.ts
test/public/publicAPIs.spec.ts

preparing sdk 1.7.0

---

yarn.lock

High sev: Dependabot cannot update to the required version

[admin] bump set-value

---

README.md
package.json
src/internal/constants.ts
test/public/publicAPIs.spec.ts

Co-authored-by: Sachin Gupta <saching@microsoft.com>

Updating master branch with latest release.

---

src/public/media.ts

Changes are for adding support for Audio and adding a minimal AudioProps for selectMedia API. 
Also commented out Video and ImageOrVideo enums as they are not planned to be supported. I dont want this to appear in public documentation until we support it and roll out.

Adding AudioProps

---

src/public/media.ts

updating comment for view images

updating comment for view images

---

README.md
src/internal/constants.ts
src/public/index.ts
test/public/publicAPIs.spec.ts

Changes and version number updates for 1.8.0-beta.3

Updates for 1.8.0-beta.3

---

src/public/interfaces.ts

add isMultiWindow to context interface

add isMultiWindow to context interface

---

README.md
package.json
src/internal/constants.ts

version number updates for 1.8.0-beta.4

updates for version 1.8.0-beta.4

---

README.md
package.json
src/internal/constants.ts

updates for 1.8.0-beta.6

---

README.md
package.json
src/internal/constants.ts

preparing for sdk 1.8.0

---

README.md
package.json
src/internal/constants.ts

updates for 1.9.0-beta.0

---

src/private/index.ts
src/private/meetingAudio.ts
test/private/meetingAudio.spec.ts

This is the initial work on the disable audio API. This still has pending unit tests to add. Please provide initial feedback.

Add API for toggle speaker audio

---

src/public/meeting.ts
test/public/meeting.spec.ts

There is a request to update the API contract

Update meeting details contract

---

README.md
package.json
src/internal/constants.ts

Prep for SDK 1.9.0 - update package version and readme file.

Prepare to release version 1.9.0

---

README.md

Changes to align with product terminology. Also includes minor edits and fixes broken links.

Tech writer updates to README

---

src/public/settings.ts

Make EntityId in the settings interface optional

Make EntityId in settings optional

---

README.md
package.json
src/internal/constants.ts

updates for 1.10.1-beta.1 release

updates for 1.10.1-beta.1 release

---

.eslintignore
.sdl/.gdnbaselines
.sdl/.gdnsuppress

Changes require to move build pipeline to SDL V2

getting ready for SDL V2

---

src/private/remoteCamera.ts

Adding additional properties to the Participant interface in the remoteCamera private namespace

Updating the remote camera Participant interface

---

src/public/settings.ts

Added getSettings and setSettings to expectedFrameContexts to enable API calls from side panel.

Enabled getSettings and setSettings API call in side panel.

---

README.md
package.json
src/internal/constants.ts

preparing release 1.10.0

---

README.md
package.json
src/internal/constants.ts

merge latest release to master

preparing release 1.10.0 (#572)

---

src/private/index.ts
src/private/teams.ts

export teams namespace

---

src/public/meeting.ts

This PR makes the `stopSharingAppContentToStage` API private

Privatize stopSharingAppContentToStage API

---

README.md
package.json
src/internal/constants.ts

Prepare to release version 1.11.0

Prepare to release version 1.11.0

---

azure-pipelines-with-e2etests.yml

Update the branch triggers for the e2e pipeline.

Update e2etests pipeline to work with 2.0-preview branch

---

azure-pipelines.yml
packages/bundle-size-tools/src/ADO/AdoSizeComparator.ts
tools/cli/compareBundleAnalysis.js

- Bundle analysis was failing due to invalid base branch. This PR fixes that and passes the base branch directly from CI pipeline.

Bundle Analysis : Parametrize base branch and pass target branch

---

apps/teams-test-app/src/App.tsx
apps/teams-test-app/src/components/MeetingAPIs.tsx
apps/teams-test-app/src/components/privateApis/MeetingRoomAPIs.tsx

MeetingRoomAPIs were included in MeetingAPIs file in test-app. Separating them out since they have separate modules. And Fixing some typos in MeetingAPIs

Creating separate section for MeetingRoom in test-app

---

README.md
apps/teams-test-app/package.json
packages/teams-js/README.md
packages/teams-js/package.json
packages/teams-js/src/internal/constants.ts

* Update version to beta.1
* Update hash

Add the correct hash for the release 2.0.0-beta.1 (#711)

---

.vscode/launch.json
azure-pipelines.yml
packages/teams-js/prepNextDevRelease.js

Let me know if this should point to a new release branch rather than 2.0-preview!

Add prepNextDevRelease.js

---

CHANGELOG.md
README.md
apps/teams-test-app/package.json
package.json
packages/teams-js/README.md
packages/teams-js/package.json
packages/teams-js/src/internal/constants.ts

Update README file to point to 2.0-preview
Update version to 2.0.0-beta.2
Update CHANGELOG to include changes for 2.0.0-beta.1 and 2.0.0-beta.2
Note: I plan to manually generate the integrity hash and update the README file(s) once all the expected code changes are in the release branch.

Update README file, changelog, and bump version

---

apps/teams-test-app/src/components/DialogAPIs.tsx
apps/teams-test-app/src/components/utils/ApiWithTextInput.tsx

- Add BoxAndButton APIs to allow communication between tabs (aka launch pages) and dialogs

Teams Test app changes for dialog communication

---

apps/teams-test-app/src/components/privateApis/FilesAPIs.tsx

Part of the pull from upstream (master) from the week of November 15th, 2021.

Add new files functions to test app

---

azure-pipelines.yml

Remove npm publish from build pipeline

Remove npm publish from build pipeline

---

src/public/authentication.ts
test/public/authentication.spec.ts

add the isExternal parameter
replace oauthRedirectMethod with 'web' in the url for the web flow

oauth external browser

---

apps/teams-test-app/src/components/AppInitialization.tsx
packages/teams-js/tsconfig.json
tsconfig.common.json

add the expected failure test component for use in cyprus tests

add an expectedFailure test component

---

tools/cli/compareBundleAnalysis.js

Incase of known failures in computing bundle analysis, relevant messaging will be posted in the comment and unknown failures will be logged in pipeline.

Surface relevant messaging in bundle analysis comment incase of failures

---

apps/teams-test-app/src/components/privateApis/MonetizationAPIs.tsx
apps/teams-test-app/src/components/utils/ApiWithTextInput.tsx

Added in callback capability for the monetization API depending on if we are in Teams JS v1 mode or TeamsJSv2 mode

Backwards compatibility for monetization API

---

apps/teams-test-app/src/components/LocationAPIs.tsx

Added in callback capability for the location API depending on if we are in Teams JS v1 mode or TeamsJSv2 mode.

Backwards compatibility for location API

---

packages/teams-js/src/public/meeting.ts

update the comments in meeting.ts to reflect the actual argument types passed into the functions

fix code comments to match updated API

---

azure-pipelines.yml

- Change service connection name for posting comments with external account

Change service connection for posting comment

---

azure-pipelines.yml

Parallelizing security and build tasks
Moving arrow SDL retention to release pipeline
Moving cloudroll deployment to release pipeline

Updating yaml pipeline and parallel security tasks

---

apps/teams-test-app/src/components/PagesAPIs.tsx
apps/teams-test-app/src/components/PagesConfigAPIs.tsx
apps/teams-test-app/src/components/utils/ApiWithoutInput.tsx

Added in callback capability for the settings API. 
Added default `noHostSdkMsg` for ApiWithoutInput.tsx.

Backwards compatibility for settings API

---

src/public/interfaces.ts

update context interface with mySite properties

Add MySite* values to context interface

---

packages/teams-js/src/internal/internalAPIs.ts
packages/teams-js/src/internal/mediaUtil.ts
packages/teams-js/src/private/legacy.ts
packages/teams-js/src/public/location.ts
packages/teams-js/src/public/media.ts
packages/teams-js/src/public/people.ts
packages/teams-js/test/public/media.spec.ts

accidentally merged before resolving all feedback and want to finish before remerging OfficeDev/microsoft-teams-library-js#870

Revert "update function to throw errors"

---

azure-pipelines.yml

Added in an E2E test for testing callback/backwards compatibility mode against latest version of the sdk

Added in E2E test for Backwards Compatibility

---

apps/teams-test-app/src/components/AppInitialization.tsx

Fixed `NotifyFailure` to match v1 e2e tests check.
Modified `NotifyExpectedFailure` since the current code doesn't really do the test work.

Fixed an bug with NotifyFailure and NotifyExpectedFailure in test app

---

tools/yaml-templates/build-test-publish.yml

Just figured out there's a step missed in aggregating changefiles that should be done before beachball is enforced. Commenting out until that's done.

Temporarily remove enforceBeachball step

---

azure-pipelines.yml
change/@microsoft-teams-js-eb072478-2fb7-4472-8af2-5c8fbfa6e30d.json
change/@microsoft-teams-js-f11bf3ab-5159-4a30-8cfe-6a1ef412b684.json

Ubuntu build fails due to difference in capital letters in the yarn script. This fixes the issue
Also changed the wording in the beachball change files

Fixing build step capital letters

---

src/public/index.ts
src/public/stageView.ts
test/public/stageView.spec.ts

Adding the openStageView API.  The design doc can be found here: https://microsoft-my.sharepoint-df.com/:w:/p/rile/ETE2H4uz1tFEpkM7PctZYZwBC2JxxHPkegcYi_vYaAAUVA?e=vTn4cc

Added open stage view API

---

src/public/tasks.ts
test/public/tasks.spec.ts

This reverts commit 90a1b0329c209547fd382d820ce6d295f58b45d2.

Revert "Restrict updateTask and submitTask to FrameContext.task (#658)"

---

change/@microsoft-teams-js-379b337f-b227-4571-bd72-a0d10286ef77.json
packages/teams-js/src/public/stageView.ts
packages/teams-js/test/public/stageView.spec.ts

* promisify stageView functions
* add appropriate tests
* maintain backwards compatability

promisify stageView

---

change/@microsoft-teams-js-b80ee3ad-b996-4147-b9a9-34e6609afbb1.json
packages/teams-js/src/private/files.ts
packages/teams-js/test/private/files.spec.ts

promisify getFileDownloads and add new tests/fix existing ones

promisify getFileDownloads

---

apps/teams-test-app/src/components/DialogAPIs.tsx
change/@microsoft-teams-js-98fef2b0-325a-446a-b919-f2859d40b092.json
packages/teams-js/src/public/dialog.ts
packages/teams-js/test/public/dialog.spec.ts

In Dialogs, 
ParentAppWindow.postMessage becomes dialog.sendMessageToParent(message: any): void
ParentAppWindow.addEventListener becomes dialog.registerOnMessageFromParent

Lakhveer/move functions:  Copied ParentAppWindow functionality into dialog capability

---

CONTRIBUTING.md

Adding info to the CONTRIBUTING.md file for how to fork the repository to contribute to the teams-js repo.

Update contribution guide with info about forks

---

apps/teams-test-app/src/components/DialogAPIs.tsx
change/@microsoft-teams-js-f4f055db-c85c-4ea2-b470-278759a1aafb.json
packages/teams-js/src/public/dialog.ts
packages/teams-js/src/public/interfaces.ts
packages/teams-js/src/public/runtime.ts
packages/teams-js/src/public/tasks.ts
packages/teams-js/test/public/dialog.spec.ts
packages/teams-js/test/public/tasks.spec.ts

1. Created a sub capability named update in dialogs. Moved resize functions in there and added isSupported function. 
2. Made changes in tasks.update, so it would keep working as it was before.
3. Fixed Unit testing and test-app file to support the sub capability.

Lakhveer/updateResize Adding a sub capability named update in dialogs.

---

change/@microsoft-teams-js-2519cd0a-0e06-49b5-b79d-338d4042a1a3.json
packages/teams-js/src/private/privateAPIs.ts

Change code comment to explain that this function cannot be deleted since it is callable externally

change comment for initialize private apis

---

packages/teams-js/CHANGELOG.md

Small edit to add clarity to a previously published changelog comment.

Update the changelog to add clarity

---

src/public/navigation.ts
test/public/publicAPIs.spec.ts

Adding meetingStage FrameContext in returnFocus api

Initiliazing for all FrameConexts for returnFocus api

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-10f21f18-2cce-4647-8722-185870be6e0c.json
change/@microsoft-teams-js-71b9a8ca-81d8-4efb-8b64-10ba4b61c302.json
change/@microsoft-teams-js-79bbe9e1-d12c-494a-aa68-2951956c6b49.json
change/@microsoft-teams-js-7f49308b-b9f3-442f-b596-a6bcbbde04d6.json
change/@microsoft-teams-js-852c2ecf-d960-4bca-a5cd-c20448ab354e.json
change/@microsoft-teams-js-a1c16808-8fc1-4d4d-8638-ff5b68c0e802.json
change/@microsoft-teams-js-aa2116d9-a745-445b-8ff6-e9acf702cd08.json
change/@microsoft-teams-js-bbb6446d-d812-43b0-b0ad-75c83296fde3.json
change/@microsoft-teams-js-d4e00e8a-dd35-4b09-b584-9b0b94751254.json
change/@microsoft-teams-js-ee0877f5-a59f-4ca2-a51c-a21f9c37d769.json
change/@microsoft-teams-js-eeea34b8-feb0-4048-a0db-ba1db75fa6ca.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Co-authored-by: erinha <erinha@users.noreply.github.com>

Releasing 2.0.0-beta.5 (#1106)

---

apps/teams-test-app/src/components/privateApis/FilesAPIs.tsx
apps/teams-test-app/src/components/privateApis/PrivateAPIs.tsx
change/@microsoft-teams-js-33f6b6c7-d739-4b71-9f00-dcdceea01935.json
packages/teams-js/src/private/files.ts
packages/teams-js/src/private/index.ts
packages/teams-js/src/private/privateAPIs.ts
packages/teams-js/src/public/runtime.ts
packages/teams-js/test/private/files.spec.ts
packages/teams-js/test/private/privateAPIs.spec.ts

For GA release, we want to revert it back and going to treat it as only back-compat

Reverting Files capability to v1 state

---

CONTRIBUTING.md
change/@microsoft-teams-js-564f452b-e760-4a7a-bc80-fbc7288b70fb.json

Adds detail about adding an isSupported() function for version checked APIs addition guidance. Also fixes broken link in CONTRIBUTING.md.

Add to version checked APIs guidance

---

change/@microsoft-teams-js-288b4aeb-d82e-48a5-9d09-73197b7f2265.json
change/@microsoft-teams-js-393fc2b1-d5c9-413a-98d5-b44bf8a88903.json
change/@microsoft-teams-js-6cfdd495-e295-4ae6-b1a2-1721a2f1eae8.json
change/@microsoft-teams-js-7bb78d87-087d-498a-aede-24ea1245c3c3.json
change/@microsoft-teams-js-8c586dc2-c336-435e-b50a-873289757f26.json
change/@microsoft-teams-js-927f99f5-92fd-4a8b-979f-11b6a9e7a6e2.json
change/@microsoft-teams-js-a1117fe3-9c1f-4d89-8020-c75903495d39.json
change/@microsoft-teams-js-d69fae7a-9ac3-4420-a310-29a0e3a9d117.json
change/@microsoft-teams-js-fad26258-8531-4882-98d5-8df4e225fba8.json
packages/teams-js/CHANGELOG.md

Cleaning up the CHANGELOG and change files that will end up the CHANGELOG for consistency before the next release.

Update CHANGELOG and change files for consistency

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-288b4aeb-d82e-48a5-9d09-73197b7f2265.json
change/@microsoft-teams-js-393fc2b1-d5c9-413a-98d5-b44bf8a88903.json
change/@microsoft-teams-js-6cfdd495-e295-4ae6-b1a2-1721a2f1eae8.json
change/@microsoft-teams-js-7bb78d87-087d-498a-aede-24ea1245c3c3.json
change/@microsoft-teams-js-86fc38c9-ff0e-4536-8c12-d1da2ed891f0.json
change/@microsoft-teams-js-8c586dc2-c336-435e-b50a-873289757f26.json
change/@microsoft-teams-js-927f99f5-92fd-4a8b-979f-11b6a9e7a6e2.json
change/@microsoft-teams-js-a1117fe3-9c1f-4d89-8020-c75903495d39.json
change/@microsoft-teams-js-d69fae7a-9ac3-4420-a310-29a0e3a9d117.json
change/@microsoft-teams-js-fad26258-8531-4882-98d5-8df4e225fba8.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Merging release branch back into main.

Releasing 2.0.0-beta.7 (#1175)

---

change/d.json
packages/teams-js/README.md

This updates the links to documentation resources and installation instructions in the README.

Update README in preparation for releasing 2.0.0

---

apps/teams-test-app/src/components/MeetingAPIs.tsx
change/@microsoft-teams-js-f64aa406-62eb-4eb3-92bd-760dfc43fe75.json
packages/teams-js/src/public/meeting.ts
packages/teams-js/test/public/meeting.spec.ts

This PR updates the raise hand interface to match the interface.

update raiseHandStateChangedEvent interface

---

change/@microsoft-teams-js-b58082cb-6568-4c24-89f6-c55c4ec296ff.json
packages/teams-js/src/public/video.ts

Mark video APIs as beta. 
Resolves MicrosoftDocs/msteams-docs#6121

Mark video APIs as beta

---

change/@microsoft-teams-js-3e90cf0a-ad19-48b6-aa04-d66b3595072e.json
packages/teams-js/src/public/barCode.ts

marking bar code with beta tag for potential error fixes or changes since this is a new capability

marking bar code with beta tag

---

change/@microsoft-teams-js-0cceb483-48e4-4214-92f0-88ffa362f792.json
change/@microsoft-teams-js-adfbff51-25bd-4c3e-a634-5980e8eb69a0.json
change/@microsoft-teams-js-e08b2a2a-5a00-4e48-9366-4595b5a723d0.json
change/@microsoft-teams-js-f4036f1c-1557-4a30-85f6-dbb365663b39.json
change/@microsoft-teams-js-f64aa406-62eb-4eb3-92bd-760dfc43fe75.json
yarn.lock

Apparently the yarn.lock file also needs updating.

Updated change file comments for consistency before releasing v2.1.0

---

azure-pipelines.yml
tools/yaml-templates/android-test.yml
tools/yaml-templates/build-test-publish.yml

Make Test results easier to read in ADO

---

apps/sample-app/src/components/Calendar.tsx
apps/sample-app/src/components/Meetings.tsx
apps/sample-app/src/components/PeopleAvatars.tsx
apps/sample-app/src/components/utils.tsx

(initializing calendar params just once, making a util function to show relevant meetings + avatars)

code clean up

---

change/@microsoft-teams-js-ab358d74-77a1-451e-b779-36fd3b922ac7.json
packages/teams-js/src/public/app.ts
packages/teams-js/src/public/index.ts
packages/teams-js/src/public/interfaces.ts
packages/teams-js/src/public/publicAPIs.ts
packages/teams-js/test/public/app.spec.ts

* propogate action items to app context 
* add action items to context test

add action items to teams-sdk

---

apps/teams-test-app/src/App.tsx
apps/teams-test-app/src/components/Links.tsx

> Add a new file Links.tsx in test app which contains all the links and boxes for redirection APIs by the browser to help us test the behaviour.

Added links and BoxButtons for browser API in test app

---

change/@microsoft-teams-js-ab358d74-77a1-451e-b779-36fd3b922ac7.json
change/@microsoft-teams-js-c5770fed-2b55-42a7-987b-1618dd76629b.json
packages/teams-js/src/public/app.ts
packages/teams-js/src/public/interfaces.ts

update the changefile with more detail and add beta tags to new interfaces

update changefile and add beta tags to new interfaces

---

change/@microsoft-teams-js-b1a9e7fa-9c73-4ac2-938e-eea5efd0b9f3.json
packages/teams-js/src/public/interfaces.ts

PR feedback for #1276 that was accidentally merged too quickly.

More doc updates for global Context interface

---

change/@microsoft-teams-js-20f1c31d-4466-4278-b140-f9454214c18b.json
change/@microsoft-teams-js-d548f18c-2998-4465-94f5-1d4edfde9668.json

Made two tweaks to change files so the changelog will appear correctly formatted for 2.2.0 release.

Update change files for 2.2.0 release

---

change/@microsoft-teams-js-25542701-233b-493c-9626-0f340a97b4b4.json
packages/teams-js/src/public/app.ts

Elaborate on some of the context properties. The reference documentation seemed terse.

Elaborate on some of the context properties

---

apps/sample-app/src/App.tsx
apps/sample-app/src/components/Meetings.tsx
apps/sample-app/src/components/PeopleAvatars.tsx
apps/sample-app/src/components/utils.tsx

-  Used getContext for outlook/office theme
-  Changed PeopleAvatar.tsx for action menu code to be readable
-  Added link in comment to learn more about 'app' namespace
- Make MeetingList look better

added non-teams theme + readable code

---

change/@microsoft-teams-js-ac50d7db-93a5-4b32-9b41-acdc7acdea59.json
packages/teams-js/src/public/runtime.ts
packages/teams-js/src/public/webStorage.ts
packages/teams-js/test/public/runtime.spec.ts
packages/teams-js/test/public/webStorage.spec.ts

Adding missing hostClient types

Bug fix teams.fullTrust.joinedTeams should be supported on web, desktop, and iOS

---

.github/pull_request_template.md

This will add a PR template to help contributors submit PRs with information to guide reviewers and ensure all the required steps have been taken.

Adding a pull request template for the repo

---

CONTRIBUTING.md

Update the CONTRIBUTING.md file to clarify the different types of a change when creating the change file. We've received feedback that the descriptions listed are a bit confusing. 
Unfortunately I couldn't figure out how to change the descriptions when prompted by `yarn changefile`, but I can at least update the documentation here.
1. Updated CONTRIBUTING.md to clarify different change types.
N/A - no code changes
No code changes so no UTs added.
No
No, no code changes

Clarify different types of change in change files

---

change/@microsoft-teams-js-19d1a5ee-d78e-4439-9a2e-9d784f2fe434.json
packages/teams-js/src/private/index.ts
packages/teams-js/src/private/videoEx.ts
packages/teams-js/src/public/video.ts
packages/teams-js/test/private/videoEx.spec.ts

1. extend video API to support audio-based avatar
2. update doc comments

changes for audio-based avatar

---

apps/teams-test-app/src/components/GeoLocationAPIs.tsx
apps/teams-test-app/src/components/PagesAPIs.tsx
packages/teams-js/src/public/geoLocation.ts

Change some of titles in test App:
1. 'location' to 'geoLocation' under geoLocationAPIs.2. 
2. 'shareDeepLink's to be either 'shareDeepLink (Core)' or 'shareDeepLink (Pages)' 
as it's hard to do UI Test Apps if there are duplicate names.
1. 'location' to 'geoLocation' under geoLocationAPIs file.
2. shareDeepLink's to be either 'shareDeepLink (Core)' or 'shareDeepLink (Pages)'  in PagesAPIs file
build successfully and checked by eyes.
Only displayed titles are changed.

Kx/change titles for iOS UI tests

---

change/@microsoft-teams-js-b0014b0d-df3d-47ef-a22d-aac24742b89b.json
packages/teams-js/src/public/app.ts

Update the documentation for the `app.initialize` function to clarify that it needs to have completed before calling other library methods.
Ensure all existing tests pass.
No, there are no unit tests for the content of documentation.
No.
Yes
> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).
| <img width="455" alt="image" src="https://user-images.githubusercontent.com/36546967/193091680-f8ea1e06-2864-48bc-b97a-7fc6f1cbeb6f.png"> | <img width="574" alt="image" src="https://user-images.githubusercontent.com/36546967/193091424-2da0ae88-cdd2-4d8d-a98d-eca5cde5da47.png">
|

Initialize docs

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1c28affe-7a82-4351-9ab2-71be2c99fbe8.json
change/@microsoft-teams-js-2cfa7e83-7b34-4723-8d88-4e9a4e2f9b77.json
change/@microsoft-teams-js-3d42bacc-ebe5-46c9-82ff-61a56c6863e5.json
change/@microsoft-teams-js-428c45d4-9a6f-46ff-8c5a-33db61803db2.json
change/@microsoft-teams-js-5b701dc1-c6e8-4d61-acde-7b786b791a59.json
change/@microsoft-teams-js-68e20fff-dd6d-40c6-9246-1e859e1f6c84.json
change/@microsoft-teams-js-77a3844e-9b9a-4495-90e6-a62d763f22dd.json
change/@microsoft-teams-js-7a2e000c-6c51-4469-9ba1-e3dc2a4ce51c.json
change/@microsoft-teams-js-7e2d7681-be7b-4c3c-b196-470aa65092c4.json
change/@microsoft-teams-js-8b731aef-816c-49f6-9435-5b79bc5b99ca.json
change/@microsoft-teams-js-8ef7fda3-a2fe-40ff-9ca2-1a367cb59003.json
change/@microsoft-teams-js-98d7ca14-14e6-4abe-b79a-c08d1da0dc2c.json
change/@microsoft-teams-js-ab0f025f-cb65-450c-92a8-8000cb58057b.json
change/@microsoft-teams-js-b0014b0d-df3d-47ef-a22d-aac24742b89b.json
change/@microsoft-teams-js-b68fd0f2-0c02-4b54-ad32-6649673c33ac.json
change/@microsoft-teams-js-b967e73c-a65d-47ce-bd4d-9bbcd0d343a5.json
change/@microsoft-teams-js-c62c8ace-ae6f-458f-a76c-94ddcb79a220.json
change/@microsoft-teams-js-ced9c7db-ddda-4b9e-806f-1bf25773315f.json
change/@microsoft-teams-js-ea1fbc8a-654d-4410-8191-321b66d8f2d8.json
change/@microsoft-teams-js-f23c5eb2-1636-4234-b6ed-e18dbca67463.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Co-authored-by: noahdarveau-MSFT <noahdarveau-MSFT@users.noreply.github.com>
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no unit tests were added as part of this …

Releasing2.4.0 (#1379)

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1c28affe-7a82-4351-9ab2-71be2c99fbe8.json
change/@microsoft-teams-js-2cfa7e83-7b34-4723-8d88-4e9a4e2f9b77.json
change/@microsoft-teams-js-3d42bacc-ebe5-46c9-82ff-61a56c6863e5.json
change/@microsoft-teams-js-428c45d4-9a6f-46ff-8c5a-33db61803db2.json
change/@microsoft-teams-js-5b701dc1-c6e8-4d61-acde-7b786b791a59.json
change/@microsoft-teams-js-68e20fff-dd6d-40c6-9246-1e859e1f6c84.json
change/@microsoft-teams-js-77a3844e-9b9a-4495-90e6-a62d763f22dd.json
change/@microsoft-teams-js-7a2e000c-6c51-4469-9ba1-e3dc2a4ce51c.json
change/@microsoft-teams-js-7e2d7681-be7b-4c3c-b196-470aa65092c4.json
change/@microsoft-teams-js-8b731aef-816c-49f6-9435-5b79bc5b99ca.json
change/@microsoft-teams-js-8ef7fda3-a2fe-40ff-9ca2-1a367cb59003.json
change/@microsoft-teams-js-98d7ca14-14e6-4abe-b79a-c08d1da0dc2c.json
change/@microsoft-teams-js-ab0f025f-cb65-450c-92a8-8000cb58057b.json
change/@microsoft-teams-js-b0014b0d-df3d-47ef-a22d-aac24742b89b.json
change/@microsoft-teams-js-b68fd0f2-0c02-4b54-ad32-6649673c33ac.json
change/@microsoft-teams-js-b967e73c-a65d-47ce-bd4d-9bbcd0d343a5.json
change/@microsoft-teams-js-c62c8ace-ae6f-458f-a76c-94ddcb79a220.json
change/@microsoft-teams-js-ced9c7db-ddda-4b9e-806f-1bf25773315f.json
change/@microsoft-teams-js-ea1fbc8a-654d-4410-8191-321b66d8f2d8.json
change/@microsoft-teams-js-f23c5eb2-1636-4234-b6ed-e18dbca67463.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Reverts OfficeDev/microsoft-teams-library-js#1380

Revert "Releasing2.4.0 (#1379)"

---

tools/cli/preRelease.js

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Adding in temporary logic for 2.4.1 release

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1c28affe-7a82-4351-9ab2-71be2c99fbe8.json
change/@microsoft-teams-js-27d23c6b-df82-4548-81df-6efc35e67daa.json
change/@microsoft-teams-js-2cfa7e83-7b34-4723-8d88-4e9a4e2f9b77.json
change/@microsoft-teams-js-428c45d4-9a6f-46ff-8c5a-33db61803db2.json
change/@microsoft-teams-js-5b701dc1-c6e8-4d61-acde-7b786b791a59.json
change/@microsoft-teams-js-5fa91684-dbe2-4923-9f98-74504681a200.json
change/@microsoft-teams-js-68e20fff-dd6d-40c6-9246-1e859e1f6c84.json
change/@microsoft-teams-js-77a3844e-9b9a-4495-90e6-a62d763f22dd.json
change/@microsoft-teams-js-7a2e000c-6c51-4469-9ba1-e3dc2a4ce51c.json
change/@microsoft-teams-js-7e2d7681-be7b-4c3c-b196-470aa65092c4.json
change/@microsoft-teams-js-8b731aef-816c-49f6-9435-5b79bc5b99ca.json
change/@microsoft-teams-js-8ef7fda3-a2fe-40ff-9ca2-1a367cb59003.json
change/@microsoft-teams-js-98d7ca14-14e6-4abe-b79a-c08d1da0dc2c.json
change/@microsoft-teams-js-ab0f025f-cb65-450c-92a8-8000cb58057b.json
change/@microsoft-teams-js-b0014b0d-df3d-47ef-a22d-aac24742b89b.json
change/@microsoft-teams-js-b68fd0f2-0c02-4b54-ad32-6649673c33ac.json
change/@microsoft-teams-js-b967e73c-a65d-47ce-bd4d-9bbcd0d343a5.json
change/@microsoft-teams-js-c62c8ace-ae6f-458f-a76c-94ddcb79a220.json
change/@microsoft-teams-js-ced9c7db-ddda-4b9e-806f-1bf25773315f.json
change/@microsoft-teams-js-ea1fbc8a-654d-4410-8191-321b66d8f2d8.json
change/@microsoft-teams-js-f23c5eb2-1636-4234-b6ed-e18dbca67463.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

> Releasing Version 2.4.1
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#cha …

Releasing 2.4.1

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1c28affe-7a82-4351-9ab2-71be2c99fbe8.json
change/@microsoft-teams-js-27d23c6b-df82-4548-81df-6efc35e67daa.json
change/@microsoft-teams-js-2cfa7e83-7b34-4723-8d88-4e9a4e2f9b77.json
change/@microsoft-teams-js-428c45d4-9a6f-46ff-8c5a-33db61803db2.json
change/@microsoft-teams-js-56160f41-efc0-4ca0-823d-b5e4cdd07b40.json
change/@microsoft-teams-js-5b701dc1-c6e8-4d61-acde-7b786b791a59.json
change/@microsoft-teams-js-5fa91684-dbe2-4923-9f98-74504681a200.json
change/@microsoft-teams-js-68e20fff-dd6d-40c6-9246-1e859e1f6c84.json
change/@microsoft-teams-js-77a3844e-9b9a-4495-90e6-a62d763f22dd.json
change/@microsoft-teams-js-7a2e000c-6c51-4469-9ba1-e3dc2a4ce51c.json
change/@microsoft-teams-js-7e2d7681-be7b-4c3c-b196-470aa65092c4.json
change/@microsoft-teams-js-8b731aef-816c-49f6-9435-5b79bc5b99ca.json
change/@microsoft-teams-js-8ef7fda3-a2fe-40ff-9ca2-1a367cb59003.json
change/@microsoft-teams-js-98d7ca14-14e6-4abe-b79a-c08d1da0dc2c.json
change/@microsoft-teams-js-ab0f025f-cb65-450c-92a8-8000cb58057b.json
change/@microsoft-teams-js-b0014b0d-df3d-47ef-a22d-aac24742b89b.json
change/@microsoft-teams-js-b68fd0f2-0c02-4b54-ad32-6649673c33ac.json
change/@microsoft-teams-js-b967e73c-a65d-47ce-bd4d-9bbcd0d343a5.json
change/@microsoft-teams-js-c62c8ace-ae6f-458f-a76c-94ddcb79a220.json
change/@microsoft-teams-js-ced9c7db-ddda-4b9e-806f-1bf25773315f.json
change/@microsoft-teams-js-ea1fbc8a-654d-4410-8191-321b66d8f2d8.json
change/@microsoft-teams-js-f23c5eb2-1636-4234-b6ed-e18dbca67463.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
tools/cli/preRelease.js

1. Cleanup of changelogs from 2.3.0 to 2.4.1 
<No>
<No>
> Ensure the change …

Jadahiya/release 2.4.1

---

apps/teams-test-app/index_cdn.html
packages/teams-js/README.md

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Fixing integrity hash for release/2.4.1 branch

---

packages/teams-js/CHANGELOG.md
packages/teams-js/README.md

1. Modified changelog with a description of what's new in 2.4.2 release

Modified changelog for 2.4.2 release

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-07f5d520-5217-4b90-9daf-95ed983a24b3.json
change/@microsoft-teams-js-0830da79-7354-448b-9614-d0abd78d9617.json
change/@microsoft-teams-js-41b18e06-19da-4fea-93ce-49b0c3c117cb.json
change/@microsoft-teams-js-51980b95-c86a-4b3c-a2d0-1b9e475014b3.json
change/@microsoft-teams-js-56160f41-efc0-4ca0-823d-b5e4cdd07b40.json
change/@microsoft-teams-js-57a0030b-c4bf-427f-9a3f-cf218d6c4bc3.json
change/@microsoft-teams-js-641a08f6-cc03-48aa-83ff-146e18827a82.json
change/@microsoft-teams-js-6b4cf445-bd05-4fee-9742-a0af0d156bb2.json
change/@microsoft-teams-js-6e04c4d1-c386-4a3e-a2e7-19c0241219e4.json
change/@microsoft-teams-js-8835237b-4a82-4082-b65a-5db37e32c03e.json
change/@microsoft-teams-js-8b6459b8-aa6f-4f83-a71c-47b3d6022114.json
change/@microsoft-teams-js-a5a46554-add3-4b49-88e9-5cbf91e29cb2.json
change/@microsoft-teams-js-aae38f79-2917-4a2b-a1d7-658cfaa9fc24.json
change/@microsoft-teams-js-bbdd096a-35d5-4a5b-89be-ed1856a9f0e4.json
change/@microsoft-teams-js-bda11bf1-d293-4609-8bd2-4b93817d7b6d.json
change/@microsoft-teams-js-db4c1ae0-ce9d-45a5-a3f1-2f9c8d825f1d.json
change/@microsoft-teams-js-e66e0985-d2e0-4985-9859-4d3abfa7dd8d.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1.  Cleanup changes after releasing version 2.5.0

Jadahiya/release 2.5.0

---

tools/yaml-templates/build-test-publish.yml

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Disabling github comments to unblock PRs

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-45469888-55eb-44b9-b72b-cb92a212e84b.json
change/@microsoft-teams-js-568e65eb-c395-49e8-8173-62ed708f8c2c.json
change/@microsoft-teams-js-6364da81-f8f2-4864-b4b8-305ef45c6548.json
change/@microsoft-teams-js-848281b2-f558-438a-a404-c6b53ae7d496.json
change/@microsoft-teams-js-89daba45-3c93-4c72-8407-3a0a2478fb7a.json
change/@microsoft-teams-js-9e642ffe-0bf6-4775-a92f-99a31e897e32.json
change/@microsoft-teams-js-aae38f79-2917-4a2b-a1d7-658cfaa9fc24.json
change/@microsoft-teams-js-cc4b3c12-cbf1-4531-a77a-fe0f5c58b446.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1.  Cleaning up changelogs for v 2.6.0 release 
2. Updated references from v2.5.0 to v2.6.0 in documentation

Release 2.6.0 Cleanup

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-227aa403-f230-4912-aeee-22d7e6e697d6.json
change/@microsoft-teams-js-57c14eb2-51df-4f2a-b20a-c99a73f235d4.json
change/@microsoft-teams-js-7a9b3643-9d22-468d-9033-1cb93374d3a0.json
change/@microsoft-teams-js-7c96f1b9-e26e-4ac8-85be-f7b602a68543.json
change/@microsoft-teams-js-f0915011-4fe3-4e9d-8fd3-ae5c39163889.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Merged main and 2.7.0 cleanup

Noahdarveau/merge 2.7.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-7a9b3643-9d22-468d-9033-1cb93374d3a0.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Fri, 06 Jan 2023 04:15:12 GMT
- Reverted webpack globalObject: this

Ran Prerelease Workflow for 2.7.1 Release

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-7a9b3643-9d22-468d-9033-1cb93374d3a0.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Release 2.7.1 cleanup
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Release 2.7.1 Cleanup

---

packages/teams-js/src/public/chat.ts
tools/yaml-templates/security.yml

The eslint step of the "Security Tasks" job in the ADO pipeline was not properly configured. It didn't use the right parser (so it tried to parse the source as pure JavaScript), it didn't know we were using modules, and it was configured for the wrong ecmaScript version.
In addition, it also was not set to fail on fatal errors, which means that non-linting errors, like invalid configurations, would be ignored by the ESLint step, which means no one noticed this problem.
With this change, security lint failures and security runs of eslint for the "Security Tasks" job in the pipeline will now fail the pipeline.
Update the YAML for the Security Tasks to properly configure eslint:
- Use the TypeScript parser
- Indicate that we use modules
- Use the ECMA version 2018
- Fail eslint on fatal …

Properly configure eslint step of Security Tasks job in ADO pipeline

---

change/@microsoft-teams-js-d4f9a6b2-5995-4f8a-9d52-e52a245d9b00.json
packages/teams-js/package.json
yarn.lock

The version of the debug package was pinned to a particular version unintentionally. This change unpins it.
Ensure all tests pass and that logging still works.

Unpin the version of the debug package; it was originally pinned unintentionally

---

azure-pipelines.yml

This PR switches our electron E2E test argument in the pipeline to use our new playwright tests.
Validated that the pipeline ran successfully and playwright tests passed multiple times.

Update pipeline to use updated E2E electron test

---

change/@microsoft-teams-js-1a7ee762-10bc-4370-be3c-99f1794bfb5f.json
packages/teams-js/src/public/authentication.ts
packages/teams-js/src/public/video.ts

Updated various parts of the `authentication` capability documentation to make it clearer (hopefully!)
I generated the docs locally, proofread them, and validated that all the links appear to work.

Elaborated on various areas of authentication documentation

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-4198e29c-7895-44dc-b3f2-395019812786.json
change/@microsoft-teams-js-a257fe1e-8443-4003-9e8a-6743b9e78bfe.json
change/@microsoft-teams-js-afa61b73-ad24-489f-adb2-fe74e5dee74f.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
yarn.lock

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Release version 2.9.1

---

azure-pipelines.yml
tools/yaml-templates/build-app-host.yml

While migrating from `yarn` to `pnpm` package manager, the app hosting sdk need to change the pipeline to build it using `pnpm`. This PR enables the pipeline to use `pnpm` instead of `yarn`. 
Updated the pipeline …

Update tasks for app hosting sdk

---

.github/workflows/main.yml

Change the `pnpm` version to 7.30.1 in prod pipeline.

Update pnpm version to 7.30.1 in main pipeline

---

README.md
azure-pipelines.yml
package.json
src/internal/constants.ts

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Prep for 1.13.0 Release

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-04be2fe1-06e4-4f4b-ad33-425646831a7e.json
change/@microsoft-teams-js-0921e3b3-3094-48eb-9bc3-26740e08336f.json
change/@microsoft-teams-js-1058e57b-5e01-431c-ba43-eb534418fdba.json
change/@microsoft-teams-js-1fc71ef4-b682-4c27-93b4-abb417e0cde5.json
change/@microsoft-teams-js-22894b05-013f-48a0-a3eb-6b35b5c28bbe.json
change/@microsoft-teams-js-3adbd356-cd9d-4e1d-81f3-e10c19920ba6.json
change/@microsoft-teams-js-3d5f23b3-2638-4210-845e-6be7d58972c1.json
change/@microsoft-teams-js-41c6df5e-9fff-4e5e-b7b5-e745ecb0e9e9.json
change/@microsoft-teams-js-566f31c2-a1bc-4ac2-b16a-06ce2ca5f7ef.json
change/@microsoft-teams-js-62f8babe-f36f-41b4-a8c1-6e646820f0bc.json
change/@microsoft-teams-js-77061c12-8716-4a1d-8a14-c09b9d1041e4.json
change/@microsoft-teams-js-856c0e77-b263-4d92-ba73-eeb35a3c66b1.json
change/@microsoft-teams-js-a0800215-912f-43ae-9644-fddd101c0c0d.json
change/@microsoft-teams-js-a3518cde-f992-4b64-886c-862f65b00fc6.json
change/@microsoft-teams-js-a9e5b9b0-bee5-4f5c-8e2e-00c7cce00d9d.json
change/@microsoft-teams-js-ad46a5c7-5cc0-4176-8539-0b126be3e1f5.json
change/@microsoft-teams-js-d6954dd2-027c-4a76-b6b4-7f9eb86a815a.json
change/@microsoft-teams-js-d97c927c-f016-4d37-9962-c6987cb2c597.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
tools/cli/preRelease.js

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Releasing v2.10.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-04be2fe1-06e4-4f4b-ad33-425646831a7e.json
change/@microsoft-teams-js-0921e3b3-3094-48eb-9bc3-26740e08336f.json
change/@microsoft-teams-js-1058e57b-5e01-431c-ba43-eb534418fdba.json
change/@microsoft-teams-js-1fc71ef4-b682-4c27-93b4-abb417e0cde5.json
change/@microsoft-teams-js-3adbd356-cd9d-4e1d-81f3-e10c19920ba6.json
change/@microsoft-teams-js-41c6df5e-9fff-4e5e-b7b5-e745ecb0e9e9.json
change/@microsoft-teams-js-566f31c2-a1bc-4ac2-b16a-06ce2ca5f7ef.json
change/@microsoft-teams-js-56d0fb20-7990-4940-b6cb-018c84155436.json
change/@microsoft-teams-js-77061c12-8716-4a1d-8a14-c09b9d1041e4.json
change/@microsoft-teams-js-7b36e446-77f3-407f-a298-cc8a71712cd0.json
change/@microsoft-teams-js-856c0e77-b263-4d92-ba73-eeb35a3c66b1.json
change/@microsoft-teams-js-a0800215-912f-43ae-9644-fddd101c0c0d.json
change/@microsoft-teams-js-a3518cde-f992-4b64-886c-862f65b00fc6.json
change/@microsoft-teams-js-a9e5b9b0-bee5-4f5c-8e2e-00c7cce00d9d.json
change/@microsoft-teams-js-d6954dd2-027c-4a76-b6b4-7f9eb86a815a.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
tools/cli/preRelease.js

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Prep for 2.10.1 release

---

azure-pipelines.yml
tools/yaml-templates/build-app-host.yml
tools/yaml-templates/ios-test.yml

Add in azure pipelines to remove the pnpm store.
Deleted the store so that we can clear the entire cache.

Add command in azure pipelines to delete pnpm store

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-04be2fe1-06e4-4f4b-ad33-425646831a7e.json
change/@microsoft-teams-js-0921e3b3-3094-48eb-9bc3-26740e08336f.json
change/@microsoft-teams-js-1fc71ef4-b682-4c27-93b4-abb417e0cde5.json
change/@microsoft-teams-js-3adbd356-cd9d-4e1d-81f3-e10c19920ba6.json
change/@microsoft-teams-js-41c6df5e-9fff-4e5e-b7b5-e745ecb0e9e9.json
change/@microsoft-teams-js-566f31c2-a1bc-4ac2-b16a-06ce2ca5f7ef.json
change/@microsoft-teams-js-56d0fb20-7990-4940-b6cb-018c84155436.json
change/@microsoft-teams-js-77061c12-8716-4a1d-8a14-c09b9d1041e4.json
change/@microsoft-teams-js-7b36e446-77f3-407f-a298-cc8a71712cd0.json
change/@microsoft-teams-js-856c0e77-b263-4d92-ba73-eeb35a3c66b1.json
change/@microsoft-teams-js-a0800215-912f-43ae-9644-fddd101c0c0d.json
change/@microsoft-teams-js-a3518cde-f992-4b64-886c-862f65b00fc6.json
change/@microsoft-teams-js-a9e5b9b0-bee5-4f5c-8e2e-00c7cce00d9d.json
change/@microsoft-teams-js-d6954dd2-027c-4a76-b6b4-7f9eb86a815a.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
tools/cli/preRelease.js

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Release 2.10.1 Changelog cleanup

---

packages/teams-js/test/public/webStorage.spec.ts

Unit Test Case update: webStorage.spec.ts

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
apps/teams-test-app/src/components/GeoLocationAPIs.tsx
change/@microsoft-teams-js-7b36e446-77f3-407f-a298-cc8a71712cd0.json
change/@microsoft-teams-js-be8ebe71-3afc-4cba-b70e-aa45d1cec1d3.json
change/@microsoft-teams-js-c00663b4-25a1-4901-9b76-f2011b177646.json
change/@microsoft-teams-js-d05993aa-ef4b-4b2b-8924-3d4065c12821.json
change/@microsoft-teams-js-e88ee082-6fb3-4779-9727-777bd3b56814.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Releasing 2.11.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
apps/teams-test-app/src/components/GeoLocationAPIs.tsx
change/@microsoft-teams-js-7b36e446-77f3-407f-a298-cc8a71712cd0.json
change/@microsoft-teams-js-be8ebe71-3afc-4cba-b70e-aa45d1cec1d3.json
change/@microsoft-teams-js-c00663b4-25a1-4901-9b76-f2011b177646.json
change/@microsoft-teams-js-d05993aa-ef4b-4b2b-8924-3d4065c12821.json
change/@microsoft-teams-js-e88ee082-6fb3-4779-9727-777bd3b56814.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1.  Updating changelog and integrity hash values for 2.11.0 release.

Changelog cleanup for release 2.11.0 (#1727)

---

packages/teams-js/test/public/geoLocation.spec.ts

Update Unit Test Case: geolocation.spec.ts

---

packages/teams-js/test/public/authentication.spec.ts

Unit Test Case update: auth

---

azure-pipelines.yml
tools/yaml-templates/build-test-publish.yml
tools/yaml-templates/security.yml

1. Added new tags variable to pipeline following internal guidance
2. Added in SBOM generation and publishing tasks
1. Ran pipelines, confirmed that policies passed and that the SBOM artifact was properly generated

Adding in SBOM check to pipeline

---

package.json
pnpm-lock.yaml

1. Resolving the string_decoder package that is included with Webpack to 1.3.0 or above

Updating string_decoder in package.json and pnpm-lock file

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-277568ef-041e-4cc5-8169-6c0f16f39cef.json
change/@microsoft-teams-js-605a9adb-a799-4b74-be77-6ff1aabdf372.json
change/@microsoft-teams-js-623bd4b5-7341-4b40-8392-62413766d29a.json
change/@microsoft-teams-js-6fa795d7-0fc0-4847-8537-676a2be140ee.json
change/@microsoft-teams-js-a26c1e08-e775-4b10-9284-03bd7bc8c64c.json
change/@microsoft-teams-js-eb9caea7-2288-488f-b152-71a2a872e637.json
change/@microsoft-teams-js-fdf3465b-f6f4-4631-b88c-9bcf27caf0ec.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Releasing 2.12.0

---

apps/teams-test-app/README.md

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Updating README with v1 test app instructions

---

change/@microsoft-teams-js-5297bcd2-1f8c-476c-9a47-9007a4b1bb85.json
packages/teams-js/src/private/conversations.ts
packages/teams-js/src/public/app.ts
packages/teams-js/src/public/appInstallDialog.ts
packages/teams-js/src/public/calendar.ts
packages/teams-js/src/public/chat.ts
packages/teams-js/src/public/geoLocation.ts
packages/teams-js/src/public/mail.ts
packages/teams-js/src/public/pages.ts
packages/teams-js/src/public/people.ts
packages/teams-js/src/public/profile.ts
packages/teams-js/src/public/secondaryBrowser.ts

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Removing import aliasing of communications functions

---

README.md

1. Updating README with references to how to submit a pull request and a reference to building individual apps.

Updating Getting Started in root README

---

change/@microsoft-teams-js-521260e3-aa09-4bcd-a9c9-3f0cabcc51a4.json
packages/teams-js/src/public/stageView.ts

1. Update `title` as optional in `stageViewParams` to match the deep link contract.

Update title as optional in stageViewParams

---

apps/teams-test-app/e2e-test-data/marketplace.json

A recent check-in PR in Web Host SDK side added marketplace capability and thus new testing json data is added in web Host SDK side. e2e-test-data under teams-test-app needs to keep updating for migration purpose as well.
1. marketplace.json (testing json data) is added and specifically label it to run on web platform only.

Add testing Json data for marketplace capability

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-521260e3-aa09-4bcd-a9c9-3f0cabcc51a4.json
change/@microsoft-teams-js-5297bcd2-1f8c-476c-9a47-9007a4b1bb85.json
change/@microsoft-teams-js-740ff9ff-e96f-4b69-b8e0-d5d425f18633.json
change/@microsoft-teams-js-b8262513-d58f-4a86-9784-c732d9be6fc9.json
change/@microsoft-teams-js-d2dd363b-e9f0-4ea2-ac07-2f772a296990.json
change/@microsoft-teams-js-dfa943bb-061a-490f-9c87-be8069f3586e.json
change/@microsoft-teams-js-e646b065-a018-43a0-9323-e7647c23b227.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Releasing 2.13.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-23dce31e-9df6-4cbb-a51d-c701370f0b40.json
change/@microsoft-teams-js-521260e3-aa09-4bcd-a9c9-3f0cabcc51a4.json
change/@microsoft-teams-js-5297bcd2-1f8c-476c-9a47-9007a4b1bb85.json
change/@microsoft-teams-js-740ff9ff-e96f-4b69-b8e0-d5d425f18633.json
change/@microsoft-teams-js-b8262513-d58f-4a86-9784-c732d9be6fc9.json
change/@microsoft-teams-js-d2dd363b-e9f0-4ea2-ac07-2f772a296990.json
change/@microsoft-teams-js-dfa943bb-061a-490f-9c87-be8069f3586e.json
change/@microsoft-teams-js-e646b065-a018-43a0-9323-e7647c23b227.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updating CDN endpoint and cleaning up CHANGELOG

Cleanup for 2.13.0 release

---

.github/workflows/runtimeCheck.yml
packages/teams-js/src/public/runtime.ts

Adding a step to the runtime versioning check so that the GitHub bot won't keep adding the same comment to your PR every time it's updated.
1. Check comments on PR for bot for the runtime change message before posting it.
1. Ran changes against this PR with multiple pushes. Only one comment was left by the github bot.
No
No
No

Check for duplicate comment when running the runtime.ts check

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-23dce31e-9df6-4cbb-a51d-c701370f0b40.json
change/@microsoft-teams-js-33fc2e0b-a980-483b-998c-f0cc73805956.json
change/@microsoft-teams-js-4885f2ff-afee-4756-9192-4731c184d1ba.json
change/@microsoft-teams-js-7c9a6aae-faac-439e-9929-82bb4fb2f573.json
change/@microsoft-teams-js-94b44717-e417-43af-846a-5afe86c8f2bb.json
change/@microsoft-teams-js-cc1d35f9-c5f8-4d2b-9161-2d3c53d6d593.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1.  Updating version information to 2.14.0.
2.  Updating hash values for CDN release
3.  Removing list of changefiles and adding them to the changelog

Releasing 2.14.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-23dce31e-9df6-4cbb-a51d-c701370f0b40.json
change/@microsoft-teams-js-33fc2e0b-a980-483b-998c-f0cc73805956.json
change/@microsoft-teams-js-4885f2ff-afee-4756-9192-4731c184d1ba.json
change/@microsoft-teams-js-7c9a6aae-faac-439e-9929-82bb4fb2f573.json
change/@microsoft-teams-js-94b44717-e417-43af-846a-5afe86c8f2bb.json
change/@microsoft-teams-js-cc1d35f9-c5f8-4d2b-9161-2d3c53d6d593.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Ensuring changefiles, hash values, and endpoints are correctly updated for 2.14.0 release

Cleanup for 2.14.0 Release

---

.github/policies/resourceManagement.yml

Modify the message generated when an issue is closed. Added details to request feedback from developers.
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no unit …

Update resourceManagement.yml with modified message for closed issue

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-160c4fe1-6197-4ca0-b2da-23878826bebe.json
change/@microsoft-teams-js-1ca9663b-733f-4143-80b8-7dfa2ffbebe0.json
change/@microsoft-teams-js-366e2b27-1f0c-4e02-a0e0-b7236f076835.json
change/@microsoft-teams-js-6a495705-6f79-4d54-9a4c-ba9a154c0406.json
change/@microsoft-teams-js-7edb88fb-c70a-4a3c-a006-20d9bae87fd6.json
change/@microsoft-teams-js-af7d5389-9795-4d64-8917-672139b9b1e7.json
change/@microsoft-teams-js-b3109727-ff31-4dcb-bafc-b21748d8ce7b.json
change/@microsoft-teams-js-bbc2d237-0493-4993-a622-1e2121db3775.json
change/@microsoft-teams-js-cc1d35f9-c5f8-4d2b-9161-2d3c53d6d593.json
change/@microsoft-teams-js-d4042098-142c-4713-8226-3d5b8f2ced29.json
change/@microsoft-teams-js-f0a3858b-d453-42bf-9bbc-255012803b04.json
change/@microsoft-teams-js-f73124e4-b3fd-4cb2-89d4-e382d5346294.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1.  Updating changelog and hash values for 2.15.0 release

Releasing 2.15.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-160c4fe1-6197-4ca0-b2da-23878826bebe.json
change/@microsoft-teams-js-1ca9663b-733f-4143-80b8-7dfa2ffbebe0.json
change/@microsoft-teams-js-366e2b27-1f0c-4e02-a0e0-b7236f076835.json
change/@microsoft-teams-js-6a495705-6f79-4d54-9a4c-ba9a154c0406.json
change/@microsoft-teams-js-7edb88fb-c70a-4a3c-a006-20d9bae87fd6.json
change/@microsoft-teams-js-8c914365-53e4-445d-b0fb-8d3f6d0521be.json
change/@microsoft-teams-js-af7d5389-9795-4d64-8917-672139b9b1e7.json
change/@microsoft-teams-js-b3109727-ff31-4dcb-bafc-b21748d8ce7b.json
change/@microsoft-teams-js-bbc2d237-0493-4993-a622-1e2121db3775.json
change/@microsoft-teams-js-cc1d35f9-c5f8-4d2b-9161-2d3c53d6d593.json
change/@microsoft-teams-js-d4042098-142c-4713-8226-3d5b8f2ced29.json
change/@microsoft-teams-js-f0a3858b-d453-42bf-9bbc-255012803b04.json
change/@microsoft-teams-js-f73124e4-b3fd-4cb2-89d4-e382d5346294.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updated changelog for release 2.15.0

Cleanup for Release 2.15.0

---

.github/policies/resourceManagement.yml

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Fixed typo in resourceManagement.yml

---

change/@microsoft-teams-js-76452e95-a0b8-40d0-884d-1c3b327a5b2f.json
packages/teams-js/src/public/meeting.ts

This PR makes no code changes; it simply updates the reference docs for some APIs in the `meeting` namespace. Changes are intended to add more clarity around the purpose of our APIs, as well as link to concept docs, where possible.
1. Updated reference docs in `meeting` namespace
N/A
No, no changes to code were made, only reference docs
No
Yes

Updated meeting namespace typedocs

---

apps/teams-test-app/src/components/BarCodeAPIs.tsx

We are deleting an unnecessary e2e test from host repo. This PR deletes the corresponding component from test-app.
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no …

Delete unnecessary Web API test Element

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1db265e1-1b99-420b-b091-137d838d3982.json
change/@microsoft-teams-js-4849a883-419e-4fcb-8636-a7fbbe3d76c2.json
change/@microsoft-teams-js-48e1c129-06b5-414f-baa9-d52bff52751e.json
change/@microsoft-teams-js-4dccb2aa-4ca1-4b62-a68b-68237502f40e.json
change/@microsoft-teams-js-76452e95-a0b8-40d0-884d-1c3b327a5b2f.json
change/@microsoft-teams-js-8c914365-53e4-445d-b0fb-8d3f6d0521be.json
change/@microsoft-teams-js-a4ccc81c-7f19-4868-9ef6-939f153d51e8.json
change/@microsoft-teams-js-c5fcf08d-bba5-47b6-bb82-6918fd013bf5.json
change/@microsoft-teams-js-eb7c23cc-f3c2-48ab-bb88-79bc142ae5be.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updated CHANGELOG and hash values for 2.16.0 release

Releasing 2.16.0

---

apps/teams-test-app/e2e-test-data/clipboard.json
azure-pipelines.yml

As a follow up to this [PR](https://github.com/OfficeDev/microsoft-teams-library-js/pull/1977) enable the e2e test cases.

Enable e2e test cases.

---

change/@microsoft-teams-js-693e5412-2ef1-43d1-8121-788dbcc3db99.json
packages/teams-js/src/public/app.ts

Update documentation for teamsSku property to list possible values
No, no tests validate the documentation contents.
No, no tests validate the documentation contents.
Yes

Update documentation for teamsSku property to list possible values

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1db265e1-1b99-420b-b091-137d838d3982.json
change/@microsoft-teams-js-280a0451-ca07-4c4d-b152-9f7679a94fd6.json
change/@microsoft-teams-js-4849a883-419e-4fcb-8636-a7fbbe3d76c2.json
change/@microsoft-teams-js-48e1c129-06b5-414f-baa9-d52bff52751e.json
change/@microsoft-teams-js-4dccb2aa-4ca1-4b62-a68b-68237502f40e.json
change/@microsoft-teams-js-76452e95-a0b8-40d0-884d-1c3b327a5b2f.json
change/@microsoft-teams-js-8c914365-53e4-445d-b0fb-8d3f6d0521be.json
change/@microsoft-teams-js-a4ccc81c-7f19-4868-9ef6-939f153d51e8.json
change/@microsoft-teams-js-c5fcf08d-bba5-47b6-bb82-6918fd013bf5.json
change/@microsoft-teams-js-eb7c23cc-f3c2-48ab-bb88-79bc142ae5be.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updated CHANGELOG and hash values for 2.16.0 release

Cleanup for 2.16.0 release

---

package.json
packages/teams-js/test/utils.ts
pnpm-lock.yaml

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Updating package versions for dependabot

---

change/@microsoft-teams-js-1f9bb602-83c2-4b09-a307-176491fe5051.json
packages/teams-js/src/internal/mediaUtil.ts
packages/teams-js/src/internal/typeCheckUtilities.ts
packages/teams-js/src/public/monetization.ts
packages/teams-js/src/public/navigation.ts
packages/teams-js/src/public/pages.ts
packages/teams-js/src/public/people.ts
packages/teams-js/src/public/publicAPIs.ts
packages/teams-js/src/public/settings.ts
packages/teams-js/src/public/tasks.ts
packages/teams-js/src/public/teamsAPIs.ts

The long journey to enabling the `strictNullChecks` compiler option requires incrementally fixing violations. This change fixes some of those violations.
No functionality or API changes are intended; any fixes are either internal only or making explicit the existing implicit behavior. Rather than describe the general nature of the fixes here, I put comments about each type of change directly into this PR at the lines where they applied.
Ensure all existing tests pass.
No, as no behavior changes were made or intended.
No, as no behavior changes were made or intended.
Yes
More fixes of this sort, and then eventually permanently enabling the `strictNullChecks` compiler option!

Fix some locations that violate strictNullChecks

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-04cac70a-42d1-49ad-a0d1-b008d3e03c1d.json
change/@microsoft-teams-js-063ed744-1e82-4803-8244-c2acd5aeeb43.json
change/@microsoft-teams-js-14cf15d3-97d3-400f-a8a9-b40ea99f56a4.json
change/@microsoft-teams-js-1f9bb602-83c2-4b09-a307-176491fe5051.json
change/@microsoft-teams-js-252e0ab1-300c-4234-8b5c-76c706f3edec.json
change/@microsoft-teams-js-280a0451-ca07-4c4d-b152-9f7679a94fd6.json
change/@microsoft-teams-js-2fa564a4-011e-483c-b49f-4f2d2405da60.json
change/@microsoft-teams-js-693e5412-2ef1-43d1-8121-788dbcc3db99.json
change/@microsoft-teams-js-79b01e32-a70f-4798-9d2a-8112e7c5495f.json
change/@microsoft-teams-js-7ebef344-0a7e-4f6d-8a75-7adec5ad1f57.json
change/@microsoft-teams-js-c7d07f0d-ee14-4921-af8d-6750b0307503.json
change/@microsoft-teams-js-f497aa57-1549-40c6-a0f7-89b4c59a2e1f.json
change/@microsoft-teams-js-fd2fe2b1-7f23-493a-8cad-78ced187ec23.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
packages/teams-js/src/public/secondaryBrowser.ts

1. Updated hash values for release 2.17.0 and merged change files into CHANGELOG.md

Releasing 2.17.0

---

apps/teams-test-app/e2e-test-data/visualMedia.image.json
apps/teams-test-app/src/components/VisualMediaAPIs.tsx

Implementing the backCompat for visualMedia API
1. Added the visualMedia.image.json file to tested captureImages and uploadImages

Add backCompat for visualMedia API

---

change/@microsoft-teams-js-39cb25bf-5581-473d-b98e-3567c5cd61f5.json
packages/teams-js/src/internal/globalVars.ts
packages/teams-js/src/internal/handlers.ts
packages/teams-js/src/private/files.ts
packages/teams-js/src/private/logs.ts
packages/teams-js/src/public/app.ts
packages/teams-js/src/public/runtime.ts

More `strictNullChecks` violations are being fixed in this change. This is continuing the journey from the previous PRs (but no prior knowledge needed to review this one!)
I've annotated the specific changes directly on the code in the PR.
Ensured all existing tests continued to pass.
Yes.
#2012, #2014, #2020
Keep plugging away at these violations incrementally until we can enable `strictNullChecks` for the project.

Fix more violations of strictNullChecks (part 4)

---

apps/teams-test-app/src/components/AppAPIs.tsx
change/@microsoft-teams-js-e7f8db77-4e11-480e-9721-7446d9b7e985.json
packages/teams-js/src/public/app.ts
packages/teams-js/test/public/app.spec.ts

The app.lifecycle subcapability has two handlers that can be registered to suspend and resume apps. Even though the handlers are supported by hubs, there is no guarantee that app will be suspended (instead of termination). It can confusing for developers who see isSupported is true but registering the handlers still does not suspended and resumed their app (in some cases).  We are taking the isSUpported check from this sub-capability. With this, developers are welcome to …

Deleted isSupported check from app.lifecycle

---

change/@microsoft-teams-js-a0b652a7-f986-41ad-aae0-0018d63fb974.json
packages/teams-js/src/public/runtime.ts

In app.lifecycle, we are not using isSupported function anymore and for that reason, we don't need lifecycle in the runtime. Below is the PR where I added app.lifecycle in. https://github.com/OfficeDev/microsoft-teams-library-js/pull/1878/files#diff-ba08515b57305c27d5e577f96c6a48bc66b71e123004834e9f95198d9b7bf1de
This is the PR where we deleted isSupported: https://github.com/OfficeDev/microsoft-teams-library-js/pull/2042/files#diff-85dddae2b8eeec9b3e380ecace89b971146adc5 …

deleted app and app.lifecycle from runtime

---

change/@microsoft-teams-js-550edce9-f4ae-4f7d-bb34-492674dd06e2.json
packages/teams-js/src/public/teamsAPIs.ts

Updated Urls to point to the correct documentation.
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain …

Caching comment urls updated

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-05e52c9d-b6a9-4c68-bc24-0d98a2a71d04.json
change/@microsoft-teams-js-0ccadb81-a77a-4d7d-b078-d827dc6040f2.json
change/@microsoft-teams-js-0eab053d-5d3a-441c-99f2-b63a8fd47f90.json
change/@microsoft-teams-js-134533ca-fcbe-44f6-a617-de49c1129126.json
change/@microsoft-teams-js-162b7ca7-85cf-4fe6-b75d-2f978e74d906.json
change/@microsoft-teams-js-17e23500-2b46-429a-83cc-62548c0a1e5e.json
change/@microsoft-teams-js-2443616f-a3e6-497a-a102-0a5a6e3b7a6a.json
change/@microsoft-teams-js-2982475b-f77f-44fe-8106-e56b04b27ddc.json
change/@microsoft-teams-js-52e4ec21-7735-45e1-882f-112e465ccc8d.json
change/@microsoft-teams-js-550edce9-f4ae-4f7d-bb34-492674dd06e2.json
change/@microsoft-teams-js-695c9d26-51c8-4718-a014-760e6fb65a42.json
change/@microsoft-teams-js-71f0dd2d-88b0-4651-9a93-2a52e32a466e.json
change/@microsoft-teams-js-8ba4132c-1eca-4abe-b91e-4fbbe5625dad.json
change/@microsoft-teams-js-9f9754ac-4921-4f0b-a615-4498501e1ee1.json
change/@microsoft-teams-js-a0b652a7-f986-41ad-aae0-0018d63fb974.json
change/@microsoft-teams-js-a112250a-1d93-463d-8972-f4560c0b412d.json
change/@microsoft-teams-js-c3df01e9-c149-4dc2-9616-646164bd03cd.json
change/@microsoft-teams-js-e156a031-732a-4f22-8c0c-51d49568bff1.json
change/@microsoft-teams-js-ff815d37-beb3-4aba-a561-f6802208de9d.json
change/@microsoft-teams-js-ffdf93d1-4a5d-4c9c-abbd-620b88478b53.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updated CHANGELOG with Release Notes
2. Updated integrity hash for CDN release
3. Updated version to 2.19.0

Releasing 2.19.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-05e52c9d-b6a9-4c68-bc24-0d98a2a71d04.json
change/@microsoft-teams-js-0ccadb81-a77a-4d7d-b078-d827dc6040f2.json
change/@microsoft-teams-js-0eab053d-5d3a-441c-99f2-b63a8fd47f90.json
change/@microsoft-teams-js-134533ca-fcbe-44f6-a617-de49c1129126.json
change/@microsoft-teams-js-162b7ca7-85cf-4fe6-b75d-2f978e74d906.json
change/@microsoft-teams-js-17e23500-2b46-429a-83cc-62548c0a1e5e.json
change/@microsoft-teams-js-2443616f-a3e6-497a-a102-0a5a6e3b7a6a.json
change/@microsoft-teams-js-2982475b-f77f-44fe-8106-e56b04b27ddc.json
change/@microsoft-teams-js-52e4ec21-7735-45e1-882f-112e465ccc8d.json
change/@microsoft-teams-js-550edce9-f4ae-4f7d-bb34-492674dd06e2.json
change/@microsoft-teams-js-695c9d26-51c8-4718-a014-760e6fb65a42.json
change/@microsoft-teams-js-71f0dd2d-88b0-4651-9a93-2a52e32a466e.json
change/@microsoft-teams-js-8ba4132c-1eca-4abe-b91e-4fbbe5625dad.json
change/@microsoft-teams-js-9f9754ac-4921-4f0b-a615-4498501e1ee1.json
change/@microsoft-teams-js-a0b652a7-f986-41ad-aae0-0018d63fb974.json
change/@microsoft-teams-js-a112250a-1d93-463d-8972-f4560c0b412d.json
change/@microsoft-teams-js-c3df01e9-c149-4dc2-9616-646164bd03cd.json
change/@microsoft-teams-js-e156a031-732a-4f22-8c0c-51d49568bff1.json
change/@microsoft-teams-js-ff815d37-beb3-4aba-a561-f6802208de9d.json
change/@microsoft-teams-js-ffdf93d1-4a5d-4c9c-abbd-620b88478b53.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

* Releasing2.19.0
* Updated CHANGELOG
---------
1. Updating hash values and CHANGELOG for version 2.19.0 release

Cleanup for release 2.19.0

---

apps/blazor-test-app/Blazor-Test-App.csproj
package.json
pnpm-lock.yaml

1.  Updated version resolutions of Blazor dependencies to ones without a security vulnerability.
1.  Ensured SSR/Blazor apps work correctly
2.  Ensured that `pnpm test` succeeds

Fixing blazor app vulnerabilities

---

tools/yaml-templates/android-test.yml

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

added authentication to android test pipeline

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-12adf1d8-9273-468e-ac29-c8839a34e6d9.json
change/@microsoft-teams-js-406400e8-b79d-4d2f-960b-9082457579ac.json
change/@microsoft-teams-js-45d8d28e-ff3b-4d90-85de-b1a52b5f8d79.json
change/@microsoft-teams-js-530df73c-c69f-4902-bc2c-473fea1f9d6d.json
change/@microsoft-teams-js-5681fcee-94b0-459c-ac25-ec6377394b5d.json
change/@microsoft-teams-js-6a7d3368-138b-40f7-86c3-0d9e78441ff5.json
change/@microsoft-teams-js-6a7d8dc2-3cbe-416f-a18f-d5f187d613ec.json
change/@microsoft-teams-js-8fa5d255-6960-4bce-a06f-19369f4b72c7.json
change/@microsoft-teams-js-a8488fc1-1f5f-4495-817b-b1bc0c3d1af7.json
change/@microsoft-teams-js-ab5a447e-3b93-4887-9994-0e1f19a3ad61.json
change/@microsoft-teams-js-af8156ce-ea39-4f8f-8743-ab3cc4ad2894.json
change/@microsoft-teams-js-b477c203-eb01-4b83-be45-ce40782b23a3.json
change/@microsoft-teams-js-b73c1251-c8b2-4c56-acf1-6bf1d0574a48.json
change/@microsoft-teams-js-d1b21769-c65c-4536-a016-0f0231541e66.json
change/@microsoft-teams-js-d4db6147-97e1-4101-86d9-3b4e7cac6e9a.json
change/@microsoft-teams-js-d9617ed2-a75c-4b55-9d97-cfc291e1329f.json
change/@microsoft-teams-js-df05fe73-7cc1-4fd6-ba71-b2d4b326d29c.json
change/@microsoft-teams-js-eec7b9ec-93cc-4eaf-a206-1c22ced0d691.json
change/@microsoft-teams-js-f0d42b8f-a493-43e3-82bd-4acd8f2350d1.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updated hash value and version number for 2.20.0 release
2. Consolidated changefiles into CHANGELOG

Releasing 2.20.0

---

azure-pipelines.yml

1. Updated the pipeline per 1ES documentation to removed unblocking errors regarding not extending from office org specific template
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no unit …

updated pipeline to remove 1ES Warning

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-12adf1d8-9273-468e-ac29-c8839a34e6d9.json
change/@microsoft-teams-js-406400e8-b79d-4d2f-960b-9082457579ac.json
change/@microsoft-teams-js-45d8d28e-ff3b-4d90-85de-b1a52b5f8d79.json
change/@microsoft-teams-js-530df73c-c69f-4902-bc2c-473fea1f9d6d.json
change/@microsoft-teams-js-5681fcee-94b0-459c-ac25-ec6377394b5d.json
change/@microsoft-teams-js-6a7d3368-138b-40f7-86c3-0d9e78441ff5.json
change/@microsoft-teams-js-6a7d8dc2-3cbe-416f-a18f-d5f187d613ec.json
change/@microsoft-teams-js-6c572f38-28cd-415b-b897-5b13f4dad233.json
change/@microsoft-teams-js-8fa5d255-6960-4bce-a06f-19369f4b72c7.json
change/@microsoft-teams-js-a8488fc1-1f5f-4495-817b-b1bc0c3d1af7.json
change/@microsoft-teams-js-ab5a447e-3b93-4887-9994-0e1f19a3ad61.json
change/@microsoft-teams-js-af8156ce-ea39-4f8f-8743-ab3cc4ad2894.json
change/@microsoft-teams-js-b477c203-eb01-4b83-be45-ce40782b23a3.json
change/@microsoft-teams-js-b73c1251-c8b2-4c56-acf1-6bf1d0574a48.json
change/@microsoft-teams-js-d1b21769-c65c-4536-a016-0f0231541e66.json
change/@microsoft-teams-js-d4db6147-97e1-4101-86d9-3b4e7cac6e9a.json
change/@microsoft-teams-js-d9617ed2-a75c-4b55-9d97-cfc291e1329f.json
change/@microsoft-teams-js-df05fe73-7cc1-4fd6-ba71-b2d4b326d29c.json
change/@microsoft-teams-js-eec7b9ec-93cc-4eaf-a206-1c22ced0d691.json
change/@microsoft-teams-js-f0d42b8f-a493-43e3-82bd-4acd8f2350d1.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Clean-up for 2.20.0 release

---

change/@microsoft-teams-js-e551f18c-3f83-46d2-9be7-9f56341f85df.json
packages/teams-js/src/internal/telemetry.ts
packages/teams-js/src/public/authentication.ts
packages/teams-js/test/internal/communication.spec.ts

Remove testing telemetry version number and correct faulty tag on API

Remove testing telemetry version number and correct faulty tag on API

---

.github/workflows/codeql.yml
.github/workflows/main.yml
.github/workflows/postrelease.yml
.github/workflows/prerelease.yml

We are incorporating Node 20 into our pipelines to ensure that we avoid introducing any breaking changes to TeamsJS going forward. Additionally, we are proactively updating our GitHub actions, as they transition from Node 16 to Node 20.
1. Add Node 20 to pipelines
2. Update github actions as per the [guideline](https://github.blog/changelog/2023-09-22-github-actions-transition …

Add Node 20 and update GitHub actions.

---

README.md

This PR fixes the build status in the ReadMe file.

Update ReadME build badge

---

change/@microsoft-teams-js-51aca499-6581-470b-94fd-dc0c221a7a9e.json
package.json
packages/teams-js/src/internal/utils.ts
packages/teams-js/test/internal/utils.spec.ts
packages/teams-js/webpack.config.js
pnpm-lock.yaml

This PR fixes the `atob` function issues by using `Buffer.from(str)`. In `atob` function some of the special characters are not completely processed for ex. `Update...` will `Updateâ€¦`  where `...` are 3 different characters. To resolve this issue we use `Buffer.from(str)` for texts and `atob` for images in `base64ToBlob` function. Another notable change here is Polyfill for `buffer` in webpack as it was removed from `webpack 5` here is the link for the web pack [changelog](https://github.com/webpack/changelog-v5).
> If this Pull Request should close/resolve any issues when merged, use [the special syntax for …

Update base64ToBlob logic to accept special characters

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-16f5e9b8-9162-4db5-bdd1-bebbda9ab9d4.json
change/@microsoft-teams-js-3261febf-9d87-4383-bfef-0a5b53d1f145.json
change/@microsoft-teams-js-417fbdc2-6202-44b4-ae50-e5ac26af42d8.json
change/@microsoft-teams-js-50106ba4-7db7-4113-ae30-1fa99d4cc0b3.json
change/@microsoft-teams-js-51aca499-6581-470b-94fd-dc0c221a7a9e.json
change/@microsoft-teams-js-5cc77b90-8226-4b99-8dd7-e9f697b4c5d9.json
change/@microsoft-teams-js-6c572f38-28cd-415b-b897-5b13f4dad233.json
change/@microsoft-teams-js-e551f18c-3f83-46d2-9be7-9f56341f85df.json
change/@microsoft-teams-js-fefddd9f-aeb9-4319-aab0-a86b1dae58b6.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updated Changelog and hash values for version 2.21.0 release

Releasing 2.21.0

---

change/@microsoft-teams-js-d9e3628f-5c3e-4118-a863-0ab8f281c73d.json
packages/teams-js/src/public/stageView.ts

Documentation change: Making StageView.open api documentation to be visible to 
1. Removing hidden annotation from API doc.
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no unit tests were …

[StageView.Open API] Making stageView open api public

---

apps/teams-test-app/e2e-test-data/externalAppCommands.json

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Added E2E test case for externalAppCommands capability

---

apps/teams-test-app/src/components/privateApis/ExternalAppCommandsAPIs.tsx

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Implementing the same testing input for e2e tests

---

change/@microsoft-teams-js-47a6b471-9f3d-4ff2-b1f4-5abd45fa23d4.json
packages/teams-js/src/internal/utils.ts
packages/teams-js/src/private/externalAppAuthentication.ts
packages/teams-js/src/private/externalAppCardActions.ts
packages/teams-js/src/private/externalAppCommands.ts
packages/teams-js/test/internal/utils.spec.ts
packages/teams-js/test/private/externalAppAuthentication.spec.ts
packages/teams-js/test/private/externalAppCardActions.spec.ts
packages/teams-js/test/private/externalAppCommands.spec.ts

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

add appId validation in all externalApp* capabilities

---

change/@microsoft-teams-js-8074484a-4a1f-420d-bb74-6a6eaca6e5f0.json
packages/teams-js/src/internal/utils.ts
packages/teams-js/test/internal/utils.spec.ts
packages/teams-js/test/private/externalAppAuthentication.spec.ts
packages/teams-js/test/private/externalAppCardActions.spec.ts

Added appId minimum length validation for copilot related APIs, and fixed unit tests
related PR: https://github.com/OfficeDev/microsoft-teams-library-js/pull/2250/files
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. …

app id validation. Id >= 5 && fix unit tests

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1f05f3e0-286f-4831-8747-649c0e47e551.json
change/@microsoft-teams-js-23031b9f-4c4f-460b-8d82-3e0cdbb78e6c.json
change/@microsoft-teams-js-2759cb8f-9b8e-42d5-91f1-9328285f396e.json
change/@microsoft-teams-js-3bedb513-c927-46e9-af3c-f3c58b360def.json
change/@microsoft-teams-js-403152af-20dc-40f4-9458-66daf3d17725.json
change/@microsoft-teams-js-46bb0b2e-b9eb-4242-8a86-665f5cb915ba.json
change/@microsoft-teams-js-47a6b471-9f3d-4ff2-b1f4-5abd45fa23d4.json
change/@microsoft-teams-js-4b3cb97d-1886-4e30-b100-4bb8503a447d.json
change/@microsoft-teams-js-66c6dadf-b3af-4de0-b855-89376c0f873a.json
change/@microsoft-teams-js-748322a6-3048-4fa4-8094-56a73c844b71.json
change/@microsoft-teams-js-8074484a-4a1f-420d-bb74-6a6eaca6e5f0.json
change/@microsoft-teams-js-813c7ff8-bec9-41f4-bc67-1768f0e492e2.json
change/@microsoft-teams-js-889e1105-9a8b-468a-94d7-ed8253cdf569.json
change/@microsoft-teams-js-a7a48879-4729-4864-a7dd-eb3c1ee29044.json
change/@microsoft-teams-js-d240675e-a8ab-4255-8393-16b2cf38801e.json
change/@microsoft-teams-js-d9e3628f-5c3e-4118-a863-0ab8f281c73d.json
change/@microsoft-teams-js-eb4eaf72-20cf-4baa-a24f-7d749ce379c1.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Changelog updated for 2.22.0 release
2. Hash values for CDN releases of 2.22.0 are updated

Releasing 2.22.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1f05f3e0-286f-4831-8747-649c0e47e551.json
change/@microsoft-teams-js-23031b9f-4c4f-460b-8d82-3e0cdbb78e6c.json
change/@microsoft-teams-js-2759cb8f-9b8e-42d5-91f1-9328285f396e.json
change/@microsoft-teams-js-3bedb513-c927-46e9-af3c-f3c58b360def.json
change/@microsoft-teams-js-403152af-20dc-40f4-9458-66daf3d17725.json
change/@microsoft-teams-js-46bb0b2e-b9eb-4242-8a86-665f5cb915ba.json
change/@microsoft-teams-js-47a6b471-9f3d-4ff2-b1f4-5abd45fa23d4.json
change/@microsoft-teams-js-4b3cb97d-1886-4e30-b100-4bb8503a447d.json
change/@microsoft-teams-js-66c6dadf-b3af-4de0-b855-89376c0f873a.json
change/@microsoft-teams-js-748322a6-3048-4fa4-8094-56a73c844b71.json
change/@microsoft-teams-js-8074484a-4a1f-420d-bb74-6a6eaca6e5f0.json
change/@microsoft-teams-js-813c7ff8-bec9-41f4-bc67-1768f0e492e2.json
change/@microsoft-teams-js-889e1105-9a8b-468a-94d7-ed8253cdf569.json
change/@microsoft-teams-js-a7a48879-4729-4864-a7dd-eb3c1ee29044.json
change/@microsoft-teams-js-d9e3628f-5c3e-4118-a863-0ab8f281c73d.json
change/@microsoft-teams-js-eb4eaf72-20cf-4baa-a24f-7d749ce379c1.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1.  Cleaning up changefiles into the CHANGELOG.md
2.  Changed references from version 2.21.0 to 2.22.0
3.  Updated integrity hashes in documentation

Cleanup for Release 2.22.0 

---

tools/yaml-templates/ios-test.yml

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Change IOSSdkScheme to IOSSdkSchemeForTest to resolve future variable names conflict

---

apps/teams-test-app/e2e-test-data/webStorage.json

Add new E2E tests for validating the `webStorage` capability
Related PR: #2289 
I verified in the test results that these new tests are running (and passing).

Add webstorage E2E tests

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-2e69f235-a19e-464e-a73b-0a34da8993bd.json
change/@microsoft-teams-js-3df1e388-302e-45ea-b24a-b46d2150dd9b.json
change/@microsoft-teams-js-40968a44-8220-4162-a289-038e99f5bee3.json
change/@microsoft-teams-js-4460db5d-e36a-40b9-8df7-0c61833d18d8.json
change/@microsoft-teams-js-4b3cb97d-1886-4e30-b100-4bb8503a447d.json
change/@microsoft-teams-js-4eaf03ba-f263-4d77-a94d-71f3644f739f.json
change/@microsoft-teams-js-51421b73-089f-43de-9076-75563e1f064c.json
change/@microsoft-teams-js-723b7387-886b-45e4-9191-9bc13fc83599.json
change/@microsoft-teams-js-7e590cca-780e-4ab0-95c7-f9e7754eb678.json
change/@microsoft-teams-js-963791e4-c448-4a4e-8a36-6c2c5b9b2035.json
change/@microsoft-teams-js-a11eae80-b237-4cf2-94ab-fb8e719e3dcb.json
change/@microsoft-teams-js-b63da2d9-3e02-4b83-9664-78aa8f49c713.json
change/@microsoft-teams-js-d2040181-a9a1-42d2-9080-35acb3a380cd.json
change/@microsoft-teams-js-db145a5b-781f-4fe0-8c46-6f556d1ad77f.json
change/@microsoft-teams-js-e5a96ec6-71dd-43aa-99ed-7318779446d9.json
change/@microsoft-teams-js-f6daee5c-d395-44ed-a4f3-670c3bbc44fe.json
change/@microsoft-teams-js-fd3f7fa2-bb9f-476d-bfdb-91a78f32d4f4.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updating integrity hashes for 2.23.0 release
2. Updated CHANGEFILE and cleaned up changelogs

Releasing 2.23.0

---

apps/ssr-test-app/package.json
pnpm-lock.yaml

1. A security vulnerability has been detected in next-js version <14.1.1. Updating to remove the vulnerability.
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no unit tests were added as part …

updated Next version

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-2e69f235-a19e-464e-a73b-0a34da8993bd.json
change/@microsoft-teams-js-3df1e388-302e-45ea-b24a-b46d2150dd9b.json
change/@microsoft-teams-js-40968a44-8220-4162-a289-038e99f5bee3.json
change/@microsoft-teams-js-4460db5d-e36a-40b9-8df7-0c61833d18d8.json
change/@microsoft-teams-js-4b3cb97d-1886-4e30-b100-4bb8503a447d.json
change/@microsoft-teams-js-4eaf03ba-f263-4d77-a94d-71f3644f739f.json
change/@microsoft-teams-js-51421b73-089f-43de-9076-75563e1f064c.json
change/@microsoft-teams-js-723b7387-886b-45e4-9191-9bc13fc83599.json
change/@microsoft-teams-js-7e590cca-780e-4ab0-95c7-f9e7754eb678.json
change/@microsoft-teams-js-963791e4-c448-4a4e-8a36-6c2c5b9b2035.json
change/@microsoft-teams-js-a11eae80-b237-4cf2-94ab-fb8e719e3dcb.json
change/@microsoft-teams-js-a126340b-95a4-431b-8c9d-0071a17f2328.json
change/@microsoft-teams-js-b63da2d9-3e02-4b83-9664-78aa8f49c713.json
change/@microsoft-teams-js-d2040181-a9a1-42d2-9080-35acb3a380cd.json
change/@microsoft-teams-js-db145a5b-781f-4fe0-8c46-6f556d1ad77f.json
change/@microsoft-teams-js-e5a96ec6-71dd-43aa-99ed-7318779446d9.json
change/@microsoft-teams-js-f6daee5c-d395-44ed-a4f3-670c3bbc44fe.json
change/@microsoft-teams-js-fd3f7fa2-bb9f-476d-bfdb-91a78f32d4f4.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. Updating changelog for main branch with the release notes for version 2.23.0
2. Cleaning up changefiles 
3. Updated hash values and documentation for the CDN release of 2.23.0 of TeamsJS

Cleanup for release 2.23.0

---

apps/teams-test-app/e2e-test-data/dialog.url.parentCommunication.json

Restricting dialog-parent communication APIs to version > 2.23.0, since it will be added to test app in the next version
related PR: https://github.com/OfficeDev/microsoft-teams-library-js/pull/2315
1. <Change 1>
2. …

Fixing e2e for dialog-parent communication

---

change/@microsoft-teams-js-4db0f880-658e-402b-b854-de13e7bc38ae.json
packages/teams-js/src/internal/globalVars.ts
packages/teams-js/src/internal/handlers.ts
packages/teams-js/src/public/app.ts

1. I found more instances of importing from an index file rather than from the file directly and have corrected them. See [this PR](https://github.com/OfficeDev/microsoft-teams-library-js/pull/2307) for a brief …

Removed more instances of importing from index.ts files

---

CODE_OF_CONDUCT.md

See more information here: https://aka.ms/opensource/campaigns/coc-template
Starting on 6/15, all open source Microsoft repositories will need to include this Code of Conduct template. I've added it ahead of time.
1. Added CODE_OF_CONDUCT.md
None
No
No
No, md file only so no changefile necessary

Add OSS Code of Conduct

---

change/@microsoft-teams-js-02195148-1a67-4aaa-9eb2-a6bf157cb57e.json
packages/teams-js/src/public/app.ts
packages/teams-js/src/public/pages.ts
packages/teams-js/src/public/publicAPIs.ts

This library has a lot of link navigation functions and it can be confusing to know what they all are or how to use them. In this change I updated the documentation for all of them to clarify intended use and link between them for easy navigation.
Yes

Update all link navigation functions to clarify appropriate usage

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-02195148-1a67-4aaa-9eb2-a6bf157cb57e.json
change/@microsoft-teams-js-2884d1fc-c964-4e5b-858b-3d946100c192.json
change/@microsoft-teams-js-4db0f880-658e-402b-b854-de13e7bc38ae.json
change/@microsoft-teams-js-5e7e369c-e6b5-445f-871f-841e22dc4197.json
change/@microsoft-teams-js-a126340b-95a4-431b-8c9d-0071a17f2328.json
change/@microsoft-teams-js-acd75970-b390-4cfe-b488-4bd6f51f723e.json
change/@microsoft-teams-js-ace1fe2b-0c05-48f6-b3b4-bdecfe1fb665.json
change/@microsoft-teams-js-ec870a0b-890d-4ada-b33b-301c1c28a8d3.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
tools/yaml-templates/android-test.yml

1. Updating CHANGELOG for 2.24.0 release
2. Updating hash values for 2.24.0 CDN release

Releasing 2.24.0

---

apps/teams-test-app/webpack.common.js
packages/teams-js/src/public/clipboard.ts

Added SSL config to teams test app for internal testing
1. Added SSL config to teams test app for internal testing
N/A

Added SSL config to teams test app for internal testing

---

tools/yaml-templates/ios-test.yml

Added and installed localhost certificates in pipelines for iOS E2E tests.
1. Added and installed localhost certificates in pipelines for iOS E2E tests.

Added and installed localhost certificates in ios-test.yml pipelines for E2E tests

---

change/@microsoft-teams-js-5dc9a9b4-40e6-4c9f-a580-8d6720cfc50f.json
packages/teams-js/src/internal/utils.ts
packages/teams-js/src/public/pages.ts
packages/teams-js/test/internal/utils.spec.ts
packages/teams-js/test/public/pages.spec.ts

Expose chat id as part of navigateToApp API
1. Add optional chat id to navigateToApp API
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
<Yes/No>
> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).
| < image1 > | < image2 > |

Add chatId to navigateToApp api

---

apps/teams-test-app/e2e-test-data/video.sharedFrame.json

#2383 updated E2E tests but neglected to specify version constrains for the TeamsJS SDK. Our internal tests are failing because we're running them against an unsupported version of this SDK
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2> …

Update version constraint in video.sharedFrame test

---

apps/teams-test-app/e2e-test-data/authentication.json

This change updates the versions which we should be testing the new getUser tests on. We've pushed it back because we're doing a patch release. 
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
<Yes/No>
> List the next or remaining steps in implementing the overall feature in …

Swap getUser auth test fixes to an earlier patch version

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-142eccf1-7044-4c9b-b363-1b7d828c2184.json
change/@microsoft-teams-js-1504ddf2-8a88-4f2a-80a7-84b8efeb180f.json
change/@microsoft-teams-js-20c797d3-df8d-4eb9-a37c-7269e59c02e8.json
change/@microsoft-teams-js-385a0467-ba06-419f-842e-89301a76c1e8.json
change/@microsoft-teams-js-5dc9a9b4-40e6-4c9f-a580-8d6720cfc50f.json
change/@microsoft-teams-js-80426639-8e57-48b5-b260-c80b8ce77169.json
change/@microsoft-teams-js-a5609caa-58c7-4c39-8d31-d34da9607b2f.json
change/@microsoft-teams-js-a8f9bbfe-abed-45eb-89dd-475510d7eb5a.json
change/@microsoft-teams-js-b3cc9e88-9329-4a98-95d5-6878864906cc.json
change/@microsoft-teams-js-cbfc373a-83b3-4276-bde7-0cb028ecc6f6.json
change/@microsoft-teams-js-f3565dc3-79ee-4e1a-97fb-fd15120450a5.json
change/@microsoft-teams-js-fcf61832-de53-4b49-824d-233e1c99caab.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Description
Summarize the changes, including the goals and reasons for this change. Be sure to call out any technical or behavior changes that reviewers should be aware of.
If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.
Main changes in the PR:
1. Updated hash values and CHANGELOG for 2.26.0 release

Setting up for release of 2.26.0

---

apps/teamsjs-diagnostic-app/package.json
pnpm-lock.yaml

This package was flagged on the Android pipeline. Upgrading to fix the CG alert

Upgrade package with CG vulnerability

---

apps/teams-test-app/e2e-test-data/hostEntity.tab.json

Added version to hostEntity.tab.json
1. Added version >2.26.0 to hostEntity.tab.json
1. Tested E2Es
> Unit tests are required for all changes. If no unit tests were added as part of this change, please explain why …

Added version to hostEntity.tab.json

---

apps/teams-test-app/e2e-test-data/hostEntity.tab.json
apps/teams-test-app/e2e-test-data/stageView.json
change/@microsoft-teams-js-a5218507-221a-43fb-9564-a80174a8f210.json
packages/teams-js/src/public/stageView.ts
packages/teams-js/test/public/stageView.spec.ts

Added a new param to the stage open API
1. Aded messageId to the stage open API
2. <Change 2>
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no unit tests were added as part of this change, …

Added messageId on the stage open API to popout channel meeting tab content.

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-1257aa2f-91cd-490f-94ba-d9fd85728ddf.json
change/@microsoft-teams-js-a1bf0d67-6f27-4b52-bcbb-30f734313db1.json
change/@microsoft-teams-js-ad734c6e-e931-4790-8795-e2a577ffb281.json
change/@microsoft-teams-js-ae62d2ab-6f4d-48ba-a644-fc76e1bc23c0.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Cleanup 2.28.0 Release

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-04213847-0138-4547-976c-ae02297702f0.json
change/@microsoft-teams-js-120060c9-a050-4da3-a0a5-2323e3a78d10.json
change/@microsoft-teams-js-3c6d20f0-0715-499f-8835-457526329b67.json
change/@microsoft-teams-js-4c2cf5b3-6661-4e5f-925b-7a8a49ad9d91.json
change/@microsoft-teams-js-4fe5ca49-b46c-4a6b-b580-bd6035df67e6.json
change/@microsoft-teams-js-75e3c524-ba26-4b6a-b01b-9a1f0e315d91.json
change/@microsoft-teams-js-81b620f2-8af1-4450-89b0-20600bac843e.json
change/@microsoft-teams-js-87505803-bfad-44bd-a44d-f2ba244c46ad.json
change/@microsoft-teams-js-8b361cdc-41c8-48a8-9e4c-cb57a8b80411.json
change/@microsoft-teams-js-9226f943-a345-4cef-95fe-607b0df82934.json
change/@microsoft-teams-js-ad734c6e-e931-4790-8795-e2a577ffb281.json
change/@microsoft-teams-js-b1e62451-f7ad-44d0-b700-d5fe996761f9.json
change/@microsoft-teams-js-b61435ce-c9da-47bc-9b65-2710406ac8d7.json
change/@microsoft-teams-js-c84a8a6a-9440-4ec4-a930-b9e6921a4932.json
change/@microsoft-teams-js-cee144c2-e3b9-40a5-bb3e-05608280d179.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

Merging 2.29.0 changes to main branch. The [release/2.29.0](https://github.com/OfficeDev/microsoft-teams-library-js/pull/2541) branch was locked due to a push that happened after the branch was created. This PR copies over all the changes and merge into main
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
> Unit tests are required for all changes. If no unit tests were …

2.29.0 post release cleanup

---

apps/tree-shaking-test-app/package.json
package.json
pnpm-lock.yaml

Bumping Rollup to the most recent version.

bumping rollup version

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-0ee21e72-d019-4626-8510-28cc59a46290.json
change/@microsoft-teams-js-1aa01dc3-75e3-43e1-8fa9-36340595f99d.json
change/@microsoft-teams-js-286cc515-1cef-4d54-9af6-d869e00d96c9.json
change/@microsoft-teams-js-3257d0cf-4640-4de7-b7a6-c117e6c4ccbf.json
change/@microsoft-teams-js-c84a8a6a-9440-4ec4-a930-b9e6921a4932.json
change/@microsoft-teams-js-c869bc74-fed2-4af2-9795-312fd14d1218.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Merging 2.30.0 release changes into the main branch. Additional changes were merged into main after creating the `release/2.30.0` branch, so merging from a proxy branch.

2.30.0 post-release cleanup

---

azure-pipelines.yml

The brownouts is over. We are adding the test back and continue to work through the fix this week.
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No> …

add test back since brownout is done

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-0ad87803-4839-4de4-8f4f-5bbd48980fde.json
change/@microsoft-teams-js-0dfea369-ca36-49f5-87e9-4f2825d7c380.json
change/@microsoft-teams-js-1596e2e2-4f59-44d4-8689-0de41698434f.json
change/@microsoft-teams-js-2f4e536b-d22a-4105-903c-024e6d9a51a5.json
change/@microsoft-teams-js-3257d0cf-4640-4de7-b7a6-c117e6c4ccbf.json
change/@microsoft-teams-js-35af1950-5f26-4ffe-8c68-6ca569870710.json
change/@microsoft-teams-js-406034a0-0f82-4635-b418-c6ad95bfa0b0.json
change/@microsoft-teams-js-42d39be6-18d9-4619-ab76-a1360275873c.json
change/@microsoft-teams-js-55399555-fdb1-4b61-accb-5ebed9246795.json
change/@microsoft-teams-js-557212a2-b959-475f-bba1-df08e64a7c81.json
change/@microsoft-teams-js-5dd2d28d-3280-4f21-9ef4-572a6de474f6.json
change/@microsoft-teams-js-6a4a3b9d-97ef-4dfe-a79c-ea0f69b290d9.json
change/@microsoft-teams-js-6c75876b-1e4b-4ca0-a7a2-d94204eae9a7.json
change/@microsoft-teams-js-7805c977-c283-42e2-9e37-bbbf82239930.json
change/@microsoft-teams-js-818caaaa-86eb-4e3d-a84a-0d61028d0307.json
change/@microsoft-teams-js-895f30e4-4c57-4645-814a-49fe2ae8e9b8.json
change/@microsoft-teams-js-9ba1fbf7-8871-42bc-8f38-03e1c4825210.json
change/@microsoft-teams-js-a4e76c3e-7ab3-4dd4-9a24-c0c909040b64.json
change/@microsoft-teams-js-b23ef57f-9184-4659-93c8-48d862788dd3.json
change/@microsoft-teams-js-c23ceb97-a527-4ef9-8714-f4beff7446ec.json
change/@microsoft-teams-js-d467d82e-564d-4b25-b975-b8d07a91a647.json
change/@microsoft-teams-js-e65fa5c8-93f1-4296-b6e3-c44e178f9fca.json
change/@microsoft-teams-js-ee20dd5c-0ffc-4208-bd96-53224dc7e062.json
change/@microsoft-teams-js-f6526430-887f-46bc-bfb4-8c9750214364.json
change/@microsoft-teams-js-f9ac3559-b7e4-4cdd-bff9-54aecd663d48.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Reopening this PR on a new branch since changes went into main before I merged in the release branch

Merge 2.31.0 release into the main branch

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-05b6fda8-1215-45ac-b8c5-338fe7d7f77e.json
change/@microsoft-teams-js-34795ff8-7c04-4032-9f88-44d9d83b8337.json
change/@microsoft-teams-js-355651b0-c6d4-47bb-b923-426b9a9a3bae.json
change/@microsoft-teams-js-4ed021f2-aea4-4a41-84f5-1d1688d7f234.json
change/@microsoft-teams-js-6f5afb78-da58-46be-a695-164d19695294.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Cleanup after releasing 2.33.0
1. Made branch off of `release/2.33.0` and merged main into it
2. Created changefile following documented instructions

Trharris/cleanup release 2.33.0

---

change/@microsoft-teams-js-ea7c4e5c-5826-4103-a2b8-f539b122546f.json

This change was incorrectly marked 'major'. Fixing.
1. Mark change type as minor
N/A
No, no code change
No code change
Not required

Correctly mark this change type as minor

---

apps/teams-test-app/src/components/privateApis/CopilotAPIs.tsx
change/@microsoft-teams-js-f28f77ed-15f6-48fc-8639-5b6530ac5e7b.json
packages/teams-js/src/private/copilot/customTelemetry.ts
packages/teams-js/test/private/copilot.spec.ts

The PR corrects corrects the return function for the API sendCustomTelemetry in copilot API.
The related PR can be found [here](https://github.com/OfficeDev/microsoft-teams-library-js/pull/2654).
1. CopilotAPI.tsx -> I have updated the file to check for isCustomTelemetrySupported
2. customTelemetry.ts -> Added isSupported()
1. <Step 1>
2. <Step 2>
No
> Ensure the change file …

Correction to custom telemetry for copilot

---

azure-pipelines.yml

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Comment out iOS E2E testing pipeline

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-004c3787-cd9d-4a4a-9d47-788052951e1e.json
change/@microsoft-teams-js-136faa15-4005-4e32-8931-382db3d3ab0f.json
change/@microsoft-teams-js-1d296820-79fa-4063-8661-65d0debc58cf.json
change/@microsoft-teams-js-23b4de1d-348c-4748-90ac-78b4fa7158c7.json
change/@microsoft-teams-js-34795ff8-7c04-4032-9f88-44d9d83b8337.json
change/@microsoft-teams-js-4bee70fb-f07b-4024-afe7-96b79ba217c8.json
change/@microsoft-teams-js-585a4c58-b352-4c2d-9bb6-36db75e05820.json
change/@microsoft-teams-js-61f74ab4-102e-4a46-88bb-55dbf245fbc1.json
change/@microsoft-teams-js-6eb66bba-172e-49d4-bef9-e346269d6a56.json
change/@microsoft-teams-js-88f21fb3-ced0-4b78-9e79-51cb73b00a0f.json
change/@microsoft-teams-js-b4a088d1-148f-4742-ac87-fbf17d9b268e.json
change/@microsoft-teams-js-ceda76cc-75d3-40de-8b4b-cb392a240254.json
change/@microsoft-teams-js-ea7c4e5c-5826-4103-a2b8-f539b122546f.json
change/@microsoft-teams-js-eef39838-66eb-4b2d-8333-7b4194fb0b47.json
change/@microsoft-teams-js-f28f77ed-15f6-48fc-8639-5b6530ac5e7b.json
change/@microsoft-teams-js-f87ded40-b4aa-4082-abe7-83f1e7907d1f.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

Wed, 05 Feb 2025 16:57:29 GMT
- Added functions for opening different types of stores along with ics filtering
- Updated `validateEmails` function to `void` type for `mail.handoff` sub-capability.
- Added the`mail.handoff.composeMailWithHandoffId` function that allows passing a handoff id to the compose mail window.
- Add visionOS client type support for Teams SDK. This change will enable app developers to find out if app is running on visionOS
- Added the new parameters to `app.getContext` named `appId` and `manifestVersion`
- Updated the sendCustomTelemetryData function in  `copilot.customTelemetry` capability.
- Decoupled prefetch of CDN resources from the initialization workflow and added fallback when resources could not be …

Prerelease work for 2.34.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-004c3787-cd9d-4a4a-9d47-788052951e1e.json
change/@microsoft-teams-js-136faa15-4005-4e32-8931-382db3d3ab0f.json
change/@microsoft-teams-js-1d296820-79fa-4063-8661-65d0debc58cf.json
change/@microsoft-teams-js-23b4de1d-348c-4748-90ac-78b4fa7158c7.json
change/@microsoft-teams-js-34795ff8-7c04-4032-9f88-44d9d83b8337.json
change/@microsoft-teams-js-4bee70fb-f07b-4024-afe7-96b79ba217c8.json
change/@microsoft-teams-js-585a4c58-b352-4c2d-9bb6-36db75e05820.json
change/@microsoft-teams-js-61f74ab4-102e-4a46-88bb-55dbf245fbc1.json
change/@microsoft-teams-js-6eb66bba-172e-49d4-bef9-e346269d6a56.json
change/@microsoft-teams-js-88f21fb3-ced0-4b78-9e79-51cb73b00a0f.json
change/@microsoft-teams-js-b4a088d1-148f-4742-ac87-fbf17d9b268e.json
change/@microsoft-teams-js-ceda76cc-75d3-40de-8b4b-cb392a240254.json
change/@microsoft-teams-js-dba89e78-5dff-49d2-9425-9086b9d71cbc.json
change/@microsoft-teams-js-ea7c4e5c-5826-4103-a2b8-f539b122546f.json
change/@microsoft-teams-js-eef39838-66eb-4b2d-8333-7b4194fb0b47.json
change/@microsoft-teams-js-f28f77ed-15f6-48fc-8639-5b6530ac5e7b.json
change/@microsoft-teams-js-f87ded40-b4aa-4082-abe7-83f1e7907d1f.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

Since merges to main happened in the middle of the release, this is a cleanup branch to handle that per step #11 in the release workflow.

Cleanup release 2.34.0 with merges from main

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-0ef83a8d-b487-4415-b721-d9356e512557.json
change/@microsoft-teams-js-12f113ad-4cdf-4b83-a246-5b552959a6fa.json
change/@microsoft-teams-js-2ec25d83-8460-43ca-ae3b-41f2ec1d4b7e.json
change/@microsoft-teams-js-92414722-9f1f-44c2-8b05-2f4c5655b02d.json
change/@microsoft-teams-js-b91fc37f-8189-4031-aec5-bedd6699cba1.json
change/@microsoft-teams-js-ce65abd1-c746-4271-990d-553f17260449.json
change/@microsoft-teams-js-dba89e78-5dff-49d2-9425-9086b9d71cbc.json
change/@microsoft-teams-js-ee0a1dbc-9fd6-4e2d-82bd-bc431674f89e.json
change/@microsoft-teams-js-ef0d7630-bc28-4b98-901d-c6412b3a421b.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No>
> Ensure …

Pre-release for Release 2.35.0 

---

apps/ssr-test-app/package.json
package.json
pnpm-lock.yaml

Resolving a CG alert by upgrading the next-js version used in SSR test app

Upgrade next-js version in ssr-test-app

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-3bf442f2-393a-43fd-9d52-d09851ea25d4.json
change/@microsoft-teams-js-d8fe5150-7dac-4fdf-8867-5fe2df61360a.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

Updating changelogs and `package.json` for version 2.37.0

Prelease of version 2.37.0

---

tools/releases/prod-release.yml

The CDN team suggested we should try the IsolatedThreads option in the CDN release task to resolve our release issue.

Try IsolatedThreads option in CDN release task

---

tools/releases/build-release.yml
tools/releases/prod-release.yml

1CDN team has provided some steps to unblock the CDN release, the first step is to remove the isolated threads option that we had previously set

CDN release fixes

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-06b44e75-5613-4594-a024-dfb68a5d7a05.json
change/@microsoft-teams-js-2d20cf0b-3ef5-4d6a-a6b0-b3110792b83f.json
change/@microsoft-teams-js-3a3fbb36-90e2-4d00-bb1e-7633a46f3f8c.json
change/@microsoft-teams-js-96be3430-7bd4-4a40-8554-4be120a97747.json
change/@microsoft-teams-js-e51a0655-ec42-4622-baea-265ada0da3db.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Prerelease 2.38.0

---

change/@microsoft-teams-js-392f75e4-a502-4c9f-a4e5-00dd9e1469cf.json
packages/teams-js/src/private/copilot/sidePanelInterfaces.ts

Added hidden tags and an optional attribute to copilot.sidePanel Interfaces

Adding @hidden tags to sidePanel Interface

---

change/@microsoft-teams-js-b5130390-bcee-440c-8e8e-4302dcdf4203.json
packages/teams-js/src/artifactsForCDN/validDomains.json

Adding the Outlook OCDI domain to the valid domains list

Add Outlook OCDI domain to validDomains.json

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-2bb3cac7-5319-4348-9c43-562b8ff6f3d7.json
change/@microsoft-teams-js-392f75e4-a502-4c9f-a4e5-00dd9e1469cf.json
change/@microsoft-teams-js-8a2e274f-36a6-4e8e-a1aa-c56ae77741c6.json
change/@microsoft-teams-js-b5130390-bcee-440c-8e8e-4302dcdf4203.json
change/@microsoft-teams-js-e3e8e355-5779-4e4a-94c3-2fc4b2fa5c83.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
packages/teams-js/src/internal/validOrigins.ts
pnpm-lock.yaml

1. Updating CDN hashes and bumping versions from 2.39.0 to 2.39.1

Setting up prerelease for version 2.39.1

---

change/@microsoft-teams-js-83b007e0-f58a-4802-9aa2-834e67ab29ba.json
packages/teams-js/src/private/copilot/sidePanelInterfaces.ts

"Added `contextType` in `TeamsContent` interface to `{copilot.sidePanel}` capability.",

"Added `contextType` in `TeamsContent` interface to `{copilot.sidePanel}` capability.",

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-0007aa6a-1242-4aac-8bae-8c8459e7b413.json
change/@microsoft-teams-js-2bb3cac7-5319-4348-9c43-562b8ff6f3d7.json
change/@microsoft-teams-js-392f75e4-a502-4c9f-a4e5-00dd9e1469cf.json
change/@microsoft-teams-js-83b007e0-f58a-4802-9aa2-834e67ab29ba.json
change/@microsoft-teams-js-8a2e274f-36a6-4e8e-a1aa-c56ae77741c6.json
change/@microsoft-teams-js-b5130390-bcee-440c-8e8e-4302dcdf4203.json
change/@microsoft-teams-js-d08f708f-cfc9-4ef6-9a54-53c055323e8c.json
change/@microsoft-teams-js-e3e8e355-5779-4e4a-94c3-2fc4b2fa5c83.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

cleanup release for Teams-JS V2.40.0 release

Kangxuanye/cleanup release 2.40.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-0007aa6a-1242-4aac-8bae-8c8459e7b413.json
change/@microsoft-teams-js-2ec9c5d0-0fdb-45a7-9c57-58e8b99969c9.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

Version bump to 2.41.0 for copilot new APIs.

Prerelease version 2.41.0

---

change/@microsoft-teams-js-60feb6d6-eb46-4998-a1d1-e4924a3a2c0e.json
package.json
packages/teams-js/src/artifactsForCDN/validDomains.json

Added support for new consumer domains in the validdomains list for the Catalyst Consumer WXP feature.
1. Updated validDomains configuration to include new consumer domains.
1. <Step 1>
2. <Step 2>
No.
No.
Yes.

Updated validDomains list to support the catalyst consumer domains

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-05700e50-9d88-4dc6-8803-d5cc7f5f8a2d.json
change/@microsoft-teams-js-60feb6d6-eb46-4998-a1d1-e4924a3a2c0e.json
change/@microsoft-teams-js-8665d57b-ce86-4934-8fa1-73b9eeeb2501.json
change/@microsoft-teams-js-d26394d9-5998-4add-af88-fa1403a92723.json
change/@microsoft-teams-js-ffac6edd-3706-413b-9503-d081e14d3a12.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

Thu, 07 Aug 2025 04:45:52 GMT
- Updated validDomains list to support the catalyst consumer domains
- Added `messageId` to app context.
- Add Outlook DoD domains to validDomains
- Fixed the typo from `NonAdult` to `NotAdult` in `LegalAgeGroupClassification` Enum.
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
> Unit …

preprelease 2.42.0

---

pnpm-lock.yaml

I regened the pnpm-lock file. I think that may be the cause of the CI pipeline failures

noahdarveau/regen pnpm-lock file

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-05700e50-9d88-4dc6-8803-d5cc7f5f8a2d.json
change/@microsoft-teams-js-60feb6d6-eb46-4998-a1d1-e4924a3a2c0e.json
change/@microsoft-teams-js-8665d57b-ce86-4934-8fa1-73b9eeeb2501.json
change/@microsoft-teams-js-9425e335-8d41-4714-9bc8-4a401010fdd8.json
change/@microsoft-teams-js-d26394d9-5998-4add-af88-fa1403a92723.json
change/@microsoft-teams-js-ffac6edd-3706-413b-9503-d081e14d3a12.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

Reopening this PR from a proxy branch since some changes have been checked into main since this release

Merge release 2.42.0 back to main

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-61a3bc70-d0e9-4213-a977-ec2e082497ea.json
change/@microsoft-teams-js-9425e335-8d41-4714-9bc8-4a401010fdd8.json
change/@microsoft-teams-js-f0901ccb-dc1d-43c7-a41c-b5d78cd6c9e4.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json

Merging release 2.43.0 branch to main

Merge release 2.43.0

---

apps/teams-test-app/index_cdn.html
apps/teams-test-app/package.json
change/@microsoft-teams-js-4a504e66-3825-4af1-b723-86337f403fee.json
change/@microsoft-teams-js-a18e12ca-431b-4b20-92ac-e6b9ed4f2a51.json
change/@microsoft-teams-js-e433db29-a743-4e63-8b17-cd1272e4a323.json
packages/teams-js/CHANGELOG.md
packages/teams-js/README.md
packages/teams-js/package.json
pnpm-lock.yaml

Wed, 10 Sep 2025 22:10:41 GMT
- Added `{authenticateWithConnector}  and { getUserAuthenticationStateForConnector}` to  `externalAppAuthentication` capability that will authenticate the user and get user authentication status for copilot connectors. The capability is still awaiting support in one or most host applications. To track availability of this capability across different hosts see https://aka.ms/capmatrix
- Added `sidePanel` to `openFilePreview`'s ensureInitialized FrameContexts

Releasing 2.45.0

---

apps/teams-test-app/src/components/privateApis/ExternalAppAuthenticationAPIs.tsx
change/@microsoft-teams-js-88216a56-3ec5-42b0-b7a5-db37b54879df.json
packages/teams-js/src/internal/telemetry.ts
packages/teams-js/src/private/externalAppAuthentication.ts
packages/teams-js/test/private/externalAppAuthentication.spec.ts
pnpm-lock.yaml

I am adding a new method to externalAppAuthentication for connectors. This API wil disconnect the connector.
1. <Change 1>
2. <Change 2>
1. <Step 1>
2. <Step 2>
<Yes/No>
<Yes/No> …

externalAppauthentication disconnectConnector
